### ISSUE TITLE
TypeError: props.date.getTime is not a function

### ISSUE THREAD

**Issue by Benzer1406** [henninghall/react-native-date-picker#100]
I just installed the library and get the error:
![IMG_2089](https://user-images.githubusercontent.com/33852084/63339713-7d919a80-c313-11e9-9d4e-8d05108c9f1a.png)

**Comment by Benzer1406** [comment]
I passed in an object that didn't contain a time, it only contained a date.

**Comment by DhanAzam93** [comment]
did you solve it ?

**Comment by suparerkk** [comment]
in date mode why do we need time?

**Comment by henninghall** [comment]
@suparerkk  Could you send a code sample that produces this error?

**Comment by hamfatfat** [comment]
below is the error handled
ERROR  TypeError: props.date.getTime is not a function. (In 'props.date.getTime()', 'props.date.getTime' is undefined)

This error is located at:
    in DatePickerIOS (at src/index.js:22)
    in DatePickerWrapper (at SearchScreen.js:79)
    in BVLinearGradient (at react-native-linear-gradient/index.ios.js:54)
    in LinearGradient (at SearchScreen.js:79)
    in RCTView (at View.js:34)
    in View (at SearchScreen.js:78)
    in RCTView (at View.js:34)
    in View (at SearchScreen.js:77)
    in RCTView (at View.js:34)
    in View (at ImageBackground.js:61)
    in ImageBackground (at SearchScreen.js:74)
    in SearchScreen (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:620)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:120)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:613)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:495)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at MainNavigation.js:17)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at MainNavigation.js:16)
    in MainNavigation (at App.js:72)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:34)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at App.js:71)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at App.js:69)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
