### ISSUE TITLE
RNDatePicker" was not found in the UIManager.

### ISSUE THREAD

**Issue by wm20111003** [henninghall/react-native-date-picker#107]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.60.0]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by wm20111003** [comment]
![image](https://user-images.githubusercontent.com/10558850/64064490-afb8cb80-cc34-11e9-9a99-a410097a5426.png)
react-native: 0.60.0  跑起来报错

**Comment by wm20111003** [comment]
I solved it!
In RN 0.60+ need cocopod install;
Podfile config it:

pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

cd ios && pod install

**Comment by yilakt** [comment]
> pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

So after doing this, my build fails. Any suggestions?

**Comment by henninghall** [comment]
@yilakt what error message do you get?

**Comment by yilakt** [comment]
> @yilakt what error message do you get?

It was telling me module wasn't found. I think it was an issue more with my config than the repo. But I ended up going with  "@react-native-community/datetimepicker": "^2.1.0"  / RNDateTimePicker for the time being.

**Comment by cjmarecek** [comment]
I have the same error but I'm running ubuntu 18.04, I can not just install cocoapods. or can I?

**Comment by cdesch** [comment]
I ran into the same issue. I cannot do the CocoPods install because it an Expo Project. 

```
requireNativeComponent: "RNDatePicker" was not found in the UIManager.
- node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:2 in getNativeComponentAttributes
- node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:26:4 in createReactNativeComponentClass$argument_1
- ... 8 more stack frames from framework internals

```

**Comment by henninghall** [comment]
@cjmarecek I don't think you could run an ios app on linux without some weird hacky tricks. 
@cdesch [Can I use expo?](https://github.com/henninghall/react-native-date-picker#can-i-use-expo)

**Comment by Dabrown18** [comment]
I just got the same error message as the above message

**Comment by ajiehatajie** [comment]
same issue with rn 62.2

**Comment by subhani-ali** [comment]
+1

**Comment by pratius** [comment]
+1

**Comment by iaforek** [comment]
Is this issue connected to this by any chance?

> Can I use expo?
> Unfortunately, expo does not support this date picker at the moment. Upvote this feature request if you would like to have it included.

https://github.com/henninghall/react-native-date-picker#can-i-use-expo

**Comment by venux92** [comment]
> pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

Thank you, got this error today on `v4.3.3` and it solved the issue.

**Comment by duykhanh0409** [comment]
I'm still facing this issue but for android version, does someone have Any suggestions? Thanks so much

**Comment by fahad-islam** [comment]
@duykhanh0409 I am still facing this issue. Have you figured out any solution?

**Comment by Artz8489** [comment]
> @duykhanh0409 I am still facing this issue. Have you figured out any solution?

Try to install react-native-date-picker": "^4.3.3" this particular version & then add pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker' inn Pod file .It should fix

**Comment by octa230** [comment]
We need help, I don't even know how to reproduce the error 

NSDate *date = [self convertToNSDate:json];
  53 |     if (date) {
> 54 |         [(RNDatePicker *)view setDate:date];
     |                               ^ no visible @interface for 'RNDatePicker' declares the selector 'setDate:'
  55 |     }
  56 | }

**Comment by paschaldev** [comment]
I have the same problem @octa230 

Any luck with a fix?

**Comment by octa230** [comment]
You probably have 2 date packages. Uninstall one of them

**Comment by moneszarrugh** [comment]
Got it working by running development build instead of expo go.

**Comment by Mnigos** [comment]
Anyone got luck solving this? It's not working for me. 

<img width="440" height="905" alt="Image" src="https://github.com/user-attachments/assets/f5e00dd4-40da-424f-835a-61f61a20e654" />
