### ISSUE TITLE
my app doesn't compile after installing react-native-date-picker

### ISSUE THREAD

**Issue by Yasir5247** [henninghall/react-native-date-picker#108]
- Android, IOS
- React: 16.8.6
 - React Native version: 0.60.5
 - react-native-date-picker version:  "^2.5.0"

Error Message:
> Configure project :react-native-date-picker
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

1- I have followed the example project and cross checked all the files in the example project with mine (like, build gradlew app/build gradle) etc.

**Comment by Yasir5247** [comment]
SOLVED: 

by adding: 

android {
  defaultConfig {
    .......
    multiDexEnabled true   <---------This line
  }
  ......
}

**Comment by RM-Eric** [comment]
The above solution worked for me too, but in case anyone is wondering, the file where that change needs to be made is in android/app/build.gradle
