### ISSUE TITLE
Native component for RNDatePicker does not exist.

### ISSUE THREAD

**Issue by zeritte** [henninghall/react-native-date-picker#11]
Hi, I just loved the idea of cross-platform wheel date picker. However, after installation steps, I get that error. Here is my package.json and error ss:
<img width="457" alt="screen shot 2018-09-13 at 04 37 32" src="https://user-images.githubusercontent.com/35241861/45462056-cc4fb100-b70e-11e8-9e68-0803ed784efd.png">
![screen shot 2018-09-13 at 04 37 37](https://user-images.githubusercontent.com/35241861/45462057-cce84780-b70e-11e8-9a52-f4eb3d25da7a.png)

**Comment by henninghall** [comment]
Hi! Expo does not support native components. If you still want to use this component you will need to reject from expo or trying their "early/alpha support" for native code. Read more here:
https://docs.expo.io/versions/latest/introduction/faq#how-do-i-add-custom-native-code

**Comment by henninghall** [comment]
There is now a [feature request you can upvote 👍](https://expo.canny.io/feature-requests/p/support-react-native-date-picker) if you still are interested of using react-native-date-picker with expo!

**Comment by henninghall** [comment]
Expo is now supported https://github.com/henninghall/react-native-date-picker#using-expo
