### ISSUE TITLE
How to automatically move to the next year when you are scrolling months? 

### ISSUE THREAD

**Issue by yernandus** [henninghall/react-native-date-picker#110]
Right now I have my minimumDate set to September 9 and when I want to chose January it does not let me do that thinking that it is earlier than minimumDate. Can we automatically move to the next year 2020?

**Comment by henninghall** [comment]
Is this feature missing on Android, iOS or both?

**Comment by henninghall** [comment]
I checked it out and since this feature is missing in the iOS datepicker there is unfortunately not much we can do about it. We need to keep the iOS version based on DatePickerIOS and I want to keep the pickers as similar as possible so to only implement it in android would not make sense.
