### ISSUE TITLE
Is there any way to disable the cylinder animation?

### ISSUE THREAD

**Issue by martianatwork** [henninghall/react-native-date-picker#115]
Basically I want to remove the animations and have a basic scroller.

**Comment by martianatwork** [comment]
Okay, I found it. It's the npv_TextSizeSelected value in layout, hopefully I will create a PR to fix this from react-native

**Comment by henninghall** [comment]
Sure, to have the possibility to remove the animation via an optional property would work. I will definitely look at your PR when you have one ready!

**Comment by martianatwork** [comment]
@henninghall Hey, I just checked the source code and the `NumberPickerView` doesn't contain any public API for the `DEFAULT_TEXT_SIZE_NORMAL_SP & DEFAULT_TEXT_SIZE_SELECTED_SP`  Which are being used in our case.

I'm not an experienced android dev so if you can guide me then I will get it done.
