### ISSUE TITLE
Prop `fadeToColor` doesn't accepts rgba color

### ISSUE THREAD

**Issue by grifotv** [henninghall/react-native-date-picker#116]
**Describe the bug**
Prop `fadeToColor` doesn't accepts rgba color.

**Expected behavior**
Ideally it should accept any valid color, such as `rgba`.

**To Reproduce**
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
      fadeToColor="rgba(34, 28, 128, 1)"
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version `0.59.10`
 - react-native-date-picker version `2.7.0`

**Comment by henninghall** [comment]
Fixed in v3.1.0
