### ISSUE TITLE
shadow top and bottom datepicker in android

### ISSUE THREAD

**Issue by kimivn** [henninghall/react-native-date-picker#128]
Hi all, i have an issue as image below in android app. I want remove shadow top and bottom datepicker. Have any solution for this one ? Thanks all.
<img width="419" alt="Screen Shot 2019-11-19 at 10 58 37 PM" src="https://user-images.githubusercontent.com/14310335/69163150-4c965100-0b20-11ea-84b7-2a385d440713.png">

**Comment by henninghall** [comment]
Unfortunately background with patterns are not supported on Android yet. You could set fadeToColor prop to "#000000“ to make it look a bit better but will probably not look perfect on you background. What you can do is modify the source code and remove the shadows in a fork/patch.

**Comment by henninghall** [comment]
This issue https://github.com/henninghall/react-native-date-picker/issues/143 covers this problem.

**Comment by vinuhub** [comment]
@henninghall Thanks, it's work for me.
