### ISSUE TITLE
[android] custom height breaks picker's infinite scroll

### ISSUE THREAD

**Issue by lukebars** [henninghall/react-native-date-picker#129]
**Describe the bug**
When custom height is set on the DatePicker, iOS works fine, but android breaks the infinite scroll feature (see attached image below) 

**Expected behavior**
Same scrolling as without custom height.

**To Reproduce**

Just add the style={{height: 500}} and watch. Sometimes you need to refresh or reinstall / rebuild the app.
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      mode="time"
      onDateChange={onDateChange}
      minuteInterval={5}
      style={{ height: 500 }}
      {...rest}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 61.2
 - react-native-date-picker version 2.7.0
![image](https://user-images.githubusercontent.com/46403446/69527625-62b76d80-0f75-11ea-89db-81803516f308.png)

**Comment by lukebars** [comment]
@henninghall maybe you are aware of this problem since you introduced height customisation?

**Comment by henninghall** [comment]
Hi thanks for reporting this, I was not aware of it!

**Comment by sagarrs** [comment]
same issue, any solution ?

**Comment by henninghall** [comment]
A workaround until this is fixed would be to make the containing div smaller.

**Comment by henninghall** [comment]
I've decided not to fix this. I will be seen as a limitation of the iosClone variant of the picker. The workaround will be to set the height to a slightly smaller value.
