### ISSUE TITLE
date and locale crash in android

### ISSUE THREAD

**Issue by SnowChasm** [henninghall/react-native-date-picker#13]
hey, I have a problem with this:
I use this code in my project, <DatePicker locale='zh' mode='date' date={new Date()} />
in ios, this work fine, but in android, the app will crash.
When I remove the locale, this work fine.

I also found a bug about dateime mode in android:
My code is <DatePicker locale='zh' minuteInterval={5} date={new Date()} mode='datetime' />
When I select a time, the time's year is 2015, not current 2018.
And the date params is not use.

**Comment by henninghall** [comment]
Hi

Thanks for reporting this. I have tried but I don't manage to reproduce it. The app simply won't crash for me, it shows the Chinese localized picker as expected. Do you mind sending the crash log from Android studio?

**Comment by henninghall** [comment]
Hi @SnowChasm 

Thanks for reporting this. I have tried but I don't manage to reproduce it. The app simply won't crash for me, it shows the Chinese localized picker as expected. Do you mind sending the crash log from Android studio?

**Comment by henninghall** [comment]
@SnowChasm Could you also provide your phone model and android version?

**Comment by SnowChasm** [comment]
I am sorry for my late reply.
this is the android studio crash log
<img width="975" alt="2018-09-19 10 32 18" src="https://user-images.githubusercontent.com/15647853/45727713-717af580-bbf7-11e8-95bc-fa0165f051a2.png">
the phone model is "YQ601 - 5.1.1", and android version is "5.1.1"

**Comment by SnowChasm** [comment]
cool!
I will have a try~

**Comment by henninghall** [comment]
Released a fix for this in v2.0.4
