### ISSUE TITLE
how to set show years when modle is datatime.

### ISSUE THREAD

**Issue by jiangchunyun** [henninghall/react-native-date-picker#134]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
It is not possible. It would not fit on the screen so you will need to find another way to display this in your UI.
