### ISSUE TITLE
[Android] mode = {"time"} not working in Android

### ISSUE THREAD

**Issue by sagarrs** [henninghall/react-native-date-picker#137]
In date picker **mode = {"time"}** is not working in Android, but works fine in IOS

**Expected behavior**
the time mode should be working in Android

**To Reproduce**

    export default class App extends Component {

      state = { date: new Date() }

      render = () =>
        <DatePicker
          mode={'time'}
          date={this.state.date}
          onDateChange={date => this.setState({ date })}
          style={{ width: 100, height: 170 }}
        />
    }
```
 - OS: [Android version 9 Pie]
 - React Native version [0.61.4]
 - react-native-date-picker version [^1.0.2]

**Comment by henninghall** [comment]
@sagarrs What exactly isn't working for you? Could you add a screenshot of the problem?

**Comment by sagarrs** [comment]
![ios-android](https://user-images.githubusercontent.com/17675875/71541181-12b83600-297b-11ea-820e-06d2dffbf3d7.jpg)

@henninghall here is a screenshot side by side

    state = { date: new Date() }
    render(){
        return(
            <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                <View style={{flexDirection: 'row'}}>
                    <View>
                        <DatePicker
                            mode={'time'}
                            date={this.state.date}
                            onDateChange={date => this.setState({ date })}
                            style={{ width: 100, height: 170 }}
                            />
                    </View>
                    <View style={{paddingLeft: 40}}>
                        <DatePicker
                            mode={'time'}
                            date={this.state.date}
                            onDateChange={date => this.setState({ date })}
                            style={{ width: 100, height: 170 }}
                            />
                    </View>
                </View>
            </View>
        )
    }

**Comment by henninghall** [comment]
Thanks! I don't manage to reproduce it. Which version of `react-native-date-picker` are you using? Version 1.7.2 that you mentioned never existed.

**Comment by sagarrs** [comment]
> Thanks! I don't manage to reproduce it. Which version of `react-native-date-picker` are you using? Version 1.7.2 that you mentioned never existed.

hi @henninghall i am sorry its "@henninghall/react-native-date-picker": "^1.0.2"

**Comment by henninghall** [comment]
Can you try the latest version (2.7.1)?

**Comment by ezranbayantemur** [comment]
It's still occurring. My code is
```
<DatePicker
    style={{ height: Dimensions.get("window").height / 6 }}
    locale="tr"
    mode="time"
    date={this.state.startTime}
    onDateChange={startTime => console.log(startTime)}
/>
```
It's not logging on console when change time. Looks like onDateChange method is not triggered on Android with "time" mode.
