### ISSUE TITLE
Invalid argument supplied to oneOf, expected an array.

### ISSUE THREAD

**Issue by Spacarar** [henninghall/react-native-date-picker#146]
**Describe the bug**
Console warning when importing this plugin. I don't remember seeing this before the recent update (to suppress "DatePickerIOS has been merged with DatePickerAndroid") but may have been present in prior releases.

**Expected behavior**
no warnings/errors on startup

**To Reproduce**
I'm seeing this error regardless of whether I actually render a date-picker. it appears to be showing up just based on import alone.

Traces back to:  `/node_modules/react-native-date-picker/propTypes.js line 18`
`minuteInterval: PropTypes.oneOf(
    1 | 2 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30
  )`

**Smartphone (please complete the following information):**
running on simulator: iPad (5th generation) iOS 13.1
Mac OSX 10.15.2 Catalina
react-native version: 0.61.5
prop-types version: 15.7.2
react-native-date-picker version: 2.7.1

**Comment by Spacarar** [comment]
Looking back in the releases this does appear to be caused by the latest release only.

specifically this commit changes `minuteInterval` from `1` to `1 | 2 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30` which seems like it should be changed to `[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30]`

https://github.com/henninghall/react-native-date-picker/pull/138/commits/2d8deb21377fa66c9a5542cf074ae2fc32f9782f

**Comment by henninghall** [comment]
Thanks for reporting this! Do you mind creating a PR? 🙂
