### ISSUE TITLE
Invariant Violation: Native component for "DatePickerManager" does not exist

### ISSUE THREAD

**Issue by MassivDash** [henninghall/react-native-date-picker#15]
I tried to use this lib, on existing project that uses Expo, RN (0.55.3), unfortunately I have encountered   

"Invariant Violation: Native component for "DatePickerManager" does not exist"

The installation and react-native-linking did not throw any errors, the project runs as usual but, crashes when I try to display the date picker.

**Comment by henninghall** [comment]
There is now a [feature request you can upvote 👍](https://expo.canny.io/feature-requests/p/support-react-native-date-picker) if you still are interested in using react-native-date-picker with expo!
