### ISSUE TITLE
Invariant Violation: View config not found for name DatePickerManager

### ISSUE THREAD

**Issue by sailywebvillee** [henninghall/react-native-date-picker#151]
Hello @henninghall ,

**Describe the bug**
A clear and concise description of what the bug is.  -
I am getting the error when  i am trying to use this library  - 
Invariant Violation: View config not found for name DatePickerManager  - 
As I am using the same basic function of the library. Please check the error message in screenshot 

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]  - Android 
 - React Native version [e.g. 0.61.5]   - 0.61.5
 - react-native-date-picker version [e.g. 2.7.3]  - 2.7.3

![device-2020-01-08-174443](https://user-images.githubusercontent.com/35765903/71977387-ad97f680-323e-11ea-9ee8-41d3ccc934e5.png)

**Comment by henninghall** [comment]
Looks like the library is not linked correctly. Try running `react-native link react-native-date-picker` or link the files manually. 

Or are you running expo? It does not support this library yet.

**Comment by sailywebvillee** [comment]
Thanks @henninghall & yes I again tried to link the library it is working fine now
