### ISSUE TITLE
Android always displays 12h format even when changing device settings to use 24h format

### ISSUE THREAD

**Issue by grifotv** [henninghall/react-native-date-picker#157]
**Describe the bug**
The 24h format device preference in Android is correctly taken into account as it affects the AM/PM wheel visibility. However, the hour wheel **always** shows 12 hours now in the latest release (`2.7.4`).

In version `2.7.3` it behaves correctly, so it looks like it's a regression bug introduced by these changed #156.

![24h-bug](https://user-images.githubusercontent.com/435351/73024574-c18a4d80-3e25-11ea-8cc5-68226465f201.png)

**Expected behavior**
Work as it was before as per README description:

> On Android the 12/24h format is determined by the device setting. When using 12h mode the AM/PM part of the picker will be displayed.

**To reproduce**
Bug present in any Android AKAIK when using `mode="time"` or `mode="datetime"` with any `locale` as well as the 24h format device preference.

**Smartphone**
 - OS: Android
 - React Native version `0.61.5`
 - react-native-date-picker version `2.7.4`

**Comment by henninghall** [comment]
Thanks a lot for reporting this. Reverted that commit and released 2.7.5.
