### ISSUE TITLE
Need to Highlight or Mark specific date

### ISSUE THREAD

**Issue by Miteshdv** [henninghall/react-native-date-picker#158]
*New Requirement**
Need to Highlight or Mark specific date

Add example code 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      highlightDate={['22-10-2019']}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
Since this feature does not exist in UIDatePicker it is unfortunately out of scope for this component.
