### ISSUE TITLE
Invariant Violation: Invariant Violation: Native component for "DatePickerManager" does not exist

### ISSUE THREAD

**Issue by vatex** [henninghall/react-native-date-picker#16]
I use Expo.io and this error occurs: "Invariant Violation: Invariant Violation: Native component for "DatePickerManager" does not exist"

**Comment by MassivDash** [comment]
I had the same issue, if you using expo unfortunately you will have to eject since expo does not support native components

**Comment by vatex** [comment]
@MassivDash Thank you for response

**Comment by henninghall** [comment]
There is now a [feature request you can upvote 👍](https://expo.canny.io/feature-requests/p/support-react-native-date-picker) if you still are interested in using react-native-date-picker with expo!
