### ISSUE TITLE
Strange behavior on android

### ISSUE THREAD

**Issue by billel-boudchicha** [henninghall/react-native-date-picker#161]
Hi and thank you for taking the time to build this component it's exactly what we want for our app.
Anyway we found a strange behavior on Android(only) where using the DatePicker in `mode="time` and also setting `locale="fr"` for(24 format) . The **onDateChange** not triggering.

So as per [Documentation](https://github.com/henninghall/react-native-date-picker#how-do-i-change-the-1224h-or-ampm-format) I think the locale prop does nothing in `mode="time"` in android, but it is needed for iOS, so to fix this we are  using it conditionally. 

Or maybe we are missing something .

**Comment by henninghall** [comment]
Hi, which version of the app are you using?

**Comment by billel-boudchicha** [comment]
Hi @henninghall thank you for your response , we were using `2.7.5`, and upgrading to `2.7.6`, fix the problem. (sorry for this)
So if i understand well in Android the Picker always follows the phone's locales, even if you explicitly change it ?. 
Anyway thank you for your time.
closing it

**Comment by henninghall** [comment]
Great! Hmm no it should only use the phone default if you don't specify it, did you see another behavior?
