### ISSUE TITLE
Invalid date when scrolling

### ISSUE THREAD

**Issue by Stanley521** [henninghall/react-native-date-picker#163]
![WhatsApp Image 2020-02-18 at 19 57 37](https://user-images.githubusercontent.com/36833134/74738306-3320b480-5289-11ea-917d-8dadc5e167ba.jpeg)
`<DatePicker
                            mode={'date'}
                            locale={'en-GB'}
                            maximumDate={ new Date() }
                            date={ datePickerValue}
                            onDateChange={date => {
                                console.log(date)
                            }}
                        />`
using this prop I'm able to scroll to 30 February, is there any solution to this?

**Comment by henninghall** [comment]
Hi, thanks for reporting this. If you update the state properly in onDateChange this should not be possible. Like this: 

```jsx
    <DatePicker
      mode={'date'}
      locale={'en-GB'}
      date={this.state.date}
      onDateChange={date => {
        this.setState({ date })
      }}
    />
```

Does it help?

**Comment by Stanley521** [comment]
Sorry for the late reply!  It did go to 1st March but I was hoping that the 30 and 31 didn't show up at all, is there any option for it?

For example, if I'm scrolling from January to December, I'm expecting the year to scroll down to 2019, but it stays in 2020.

Is this doable?

**Comment by henninghall** [comment]
Ah okay. This is how the underlying iOS native picker UIDatePicker works so there is unfortunately nothing we can do about it.
