### ISSUE TITLE
Wrong day description in pt-BR

### ISSUE THREAD

**Issue by viniciuscasarin** [henninghall/react-native-date-picker#164]
The string that represents the day is wrong, it has an wrong extra word.
Ex.: "qui 12 de mar de" should be "qui 12 de mar" without the last "de"

My component is like this:
`                                <DatePicker
                                    date={this.state.date}
                                    onDateChange={date => this.setState({date})}
                                    locale="pt-BR"
                                />`
 - OS: Android
 - React Native version: 0.61.5
 - react-native-date-picker version: 2.7.6

**Comment by viniciuscasarin** [comment]
![image](https://user-images.githubusercontent.com/24192460/74774170-fb5a4280-5271-11ea-8a23-463028254d71.png)
i forgot to upload the print, hehe

**Comment by henninghall** [comment]
Hi! Thanks for reporting this, I will have a look at it! 🔎

**Comment by henninghall** [comment]
Fixed and released in v2.7.7
