### ISSUE TITLE
How to set state date on choose outside datepicker?

### ISSUE THREAD

**Issue by kittipat3699** [henninghall/react-native-date-picker#174]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
You could for instance use `this.setState({ date: <new date> })` at another place in you component or lift the date state up from you component and use `date={props.date}` and call a callback function `onDateChange={props.onDateChange}` that changes the date prop.
