### ISSUE TITLE
OnChosenDate not called when using "nb_NO" or "fr"

### ISSUE THREAD

**Issue by Marvedog** [henninghall/react-native-date-picker#178]
**Describe the bug**
When using "time" mode, onChosenDate does not get called when using "nb_NO" or "fr" locales. It works with "en" and without locales for some reason.

**Expected behavior**
Well, it should call onChosenDate either way.

**To Reproduce**
```javascript
    <DatePicker
      date={date} 
      mode={"time"}      
      minuteInterval={1}
      onDateChange={date => onChangeDate(date)}
    />
```

**Smartphone (please complete the following information):**
 - OS: Both
 - React Native version [0.61.5]
 - react-native-date-picker version [2.7.9]

**Comment by henninghall** [comment]
Hi, what version are you actually using? 2.7.9 doesn't exist 🙂

**Comment by Marvedog** [comment]
Hehe sloppy writing. 2.7.8 !

**Comment by henninghall** [comment]
I have tried but I don't manage to reproduce the problem. Could you send a full runnable sample?
Just to confirm, you encountered this issue on both android and ios?

**Comment by henninghall** [comment]
Reopens when questions are answered 🙂
