### ISSUE TITLE
I used galaxy tabA (2016) to debug, but it got an error

### ISSUE THREAD

**Issue by quybv90** [henninghall/react-native-date-picker#179]
![image](https://user-images.githubusercontent.com/18332821/78734048-63bfc900-7971-11ea-87f6-85fdda1fe904.png)

**Comment by henninghall** [comment]
1. Are you only getting the error during debugging, not in a release build? 
2. How does your component code look like, what props are you using?
3. Could you set a breakpoint in Wheel.java and check what values state.getLocale() and getFormatPattern() are returning?

**Comment by henninghall** [comment]
Reopens when questions are answered 🙂
