### ISSUE TITLE
How to change the font family?

### ISSUE THREAD

**Issue by abdallaemadeldin** [henninghall/react-native-date-picker#181]
Hello there it's amazing package i love it so much but i wanna know how can i change the picker fontfamily?

**Comment by henninghall** [comment]
Hi, changing font is unfortunately not possible due to underlying limitations in UIDatePicker.

**Comment by rishiankush** [comment]
Anything fixed to make this possible?

**Comment by dmahajan980** [comment]
@henninghall would it be possible to change the font family for Android? If so, can you please share how this can be done? Or maybe any docs/PR/commits I can refer to?
