### ISSUE TITLE
Crashing Release Mode App in Android

### ISSUE THREAD

**Issue by Jere2357** [henninghall/react-native-date-picker#183]
**Describe the bug**
My App is in release mode and it is still not working on android even I already add  
_-keep public class net.time4j.android.ApplicationStarter_  and _-keep public class net.time4j.PrettyTime_ to my proguard-rules.pro file.

**Expected behavior**
Expected to run on my release mode app.

**To Reproduce**
 I add two lines of "-keep" in my proguard-rules.pro  file. 
```javascript
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
-keep public class net.time4j.android.ApplicationStarter
-keep public class net.time4j.PrettyTime

}
```
I enabled the proguard release builds to true.
```
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
```

**Smartphone**
 - OS: Android
 - React Native version 61.5
 - react-native-date-picker version 2.7.9

**Comment by tiendn** [comment]
Hi @Jere2357 , is the problem solved ?
How did you solve this? 
I have the same problem too?
But I don't use `proguard` in release
