### ISSUE TITLE
Styling date picker

### ISSUE THREAD

**Issue by Jere2357** [henninghall/react-native-date-picker#184]
I cant style my date picker like this:
<img width="304" alt="Screen Shot 2020-04-23 at 9 46 44 AM" src="https://user-images.githubusercontent.com/54886032/80050127-5eed3e80-8547-11ea-9c09-682111db1553.png">

Do you have any suggestion on how can I meet this?

**Comment by sriram-kailasam** [comment]
I want to remove the horizontal lines entirely. Is there any way that can be done?

**Comment by blusclips** [comment]
same as me i do want to style it like that.. any suggestions yet.

**Comment by henninghall** [comment]
Hi, thanks for the input! This is unfortunately not possible to do at the moment but I have been thinking about implementing a similar alternative using android's NumberPickerView. It would make it look similar to this:

<img src="https://miro.medium.com/max/1144/1*ZkCfNzu-pIrWgpBQeHYQIg.gif" width="400px"/>

Sounds like that could work for you? The only downside I see with that solution is that the scroll would have a bit too high friction (for my taste at least). It would make it a little bit more difficult to scroll through longer time spans. But I think I could definitely be worth adding as an option.

Please let me know if anyone is interested in helping out with this!

**Comment by blusclips** [comment]
I would more than like too.

**Comment by henninghall** [comment]
Released in 3.0.0
