### ISSUE TITLE
[Feature request] Optional value (empty/null value)

### ISSUE THREAD

**Issue by approached** [henninghall/react-native-date-picker#186]
Hi @ all

I like this plugin, but i missed one small feature. It is not possible to set the picker without value.

**To Reproduce**
```javascript
export default class App extends Component {

  state = { date: null }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

If i have a form with optional field like birthdate, so this field is everytime required.

**Comment by henninghall** [comment]
How are you imagining the picker to look like when the date is null? What date should be shown?

**Comment by approached** [comment]
Empty text or a placeholder would be nice like "Enter your birthday"

**Comment by henninghall** [comment]
Ah okay, sorry but I don't think it is very suitable to change the text the picker itself. Also, it is not possible on iOS. I would suggest you to add the text outside of the picker and control the date with 2 variables instead, perhaps something similar to this:

```javascript
export default class App extends Component {

  state = { 
    pickerDate: new Date(),
    selectedDate: null,
  }

  render = () =>
    <DatePicker
      date={this.state.pickerDate}
      onDateChange={date => {
        this.setState({ 
           pickerDate: date, 
           selectedDate: date,
       })
     }}
   />

}
```
