### ISSUE TITLE
onDateChange doesn't work lower than minimumDate

### ISSUE THREAD

**Issue by Yigityakut** [henninghall/react-native-date-picker#191]
**Describe the bug**
mode: datetime
minimumDate : 04/06/2020 15:00
current selected date : 04/06/2020 18:00

When you swipe the hour scroll to below minimumDate, it automatically goes to minimumDate. That's fine. The problem is in that moment, onDateChange is not triggered and our selected date value is not updated to the minimumDate.

**Expected behavior**
onDateChange must be triggered to minimumDate when user try to swipe lower than minimumDate.

OR

When minimumDate is set to 04/06/2020 15:00 , you should remove the hours before 15 when date is selected 04/06/2020.

**To Reproduce**
```javascript
export default class App extends Component {

 dateChanged = (val) => {
        console.log(val)
        console.log(this.state.selectedDate)
        this.setState({ selectedDate: val })
    }

  render = () =>
   <DatePicker
             mode={"datetime"}
             minuteInterval={30}
             minimumDate={minimumReservationDate}
             date={this.state.selectedDate}
             onDateChange={(val) => this.dateChanged(val)}
       /> 
}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.62.2
 - react-native-date-picker version 2.7.10

**Comment by henninghall** [comment]
Thanks, I will look into it!

**Comment by henninghall** [comment]
Fixed in https://github.com/henninghall/react-native-date-picker/pull/208 and released in version ```3.0.2```

**Comment by code-by** [comment]
When I set minimum date as `Date('10/10/2020')`, picker shows today instead of 10th of Oct.

**Comment by cakesoft-neha** [comment]
same problem with me also
