### ISSUE TITLE
Request: Make lines thinner on Android for Dark Colors

### ISSUE THREAD

**Issue by stephanoparaskeva** [henninghall/react-native-date-picker#193]
The size of the lines on android are pretty thick for dark colors and really stick out:

<img width="291" alt="Screenshot 2020-06-09 at 03 51 34" src="https://user-images.githubusercontent.com/40718272/84100810-89665e80-aa04-11ea-81c5-3ff3555dc5df.png">

Where as for IOS they're more sleek:

<img width="291" alt="Screenshot 2020-06-09 at 03 52 04" src="https://user-images.githubusercontent.com/40718272/84100854-9aaf6b00-aa04-11ea-9201-80a628f3f354.png">

Perhaps there could be an option to adjust thickness by number, by value eg:  `'none', 'thin', 'normal', 'thick'`. Or turn them on/off?

Great work by the way!

**Comment by henninghall** [comment]
I agree, that would be nice!
