### ISSUE TITLE
[IOS] Build failed: Declaration of 'RCTBubblingEventBlock' must be imported from module

### ISSUE THREAD

**Issue by srednicki95** [henninghall/react-native-date-picker#197]
**Describe the bug**
IOS App build fails after added react-native-data-picker.
Error in DataPicker.m file: 
`Declaration of 'RCTBubblingEventBlock' must be imported from module 'React.React.RCTView' before it is required`

All work correctly on Android.

**Expected behavior**
IOS app build successfully.

**To Reproduce**
react-native init
yarn add react-native-data-picker
cd ios
pod install

try to build app in xcode

**Smartphone (please complete the following information):**
 - OS: IOS
 - React Native version: 0.59.10
 - react-native-date-picker version : 2.7.11

## My solution
`#import "React/RCTViewManager.h"` on top DataPicker.m file.
#196

**Comment by henninghall** [comment]
Hi! Which version of Xcode are you using?
Does it happen on React Native v0.62?

**Comment by srednicki95** [comment]
@henninghall I use 11.4.1 xcode, but also tested it on 11.3.1.
About React Native version I tested only on 0.59.10

**Comment by henninghall** [comment]
Could you please test on react native 0.62 and check if the issue exist there? It would be very helpful! It sounds very strange if this error would be present without me nor anyone else noticing it 😅

**Comment by srednicki95** [comment]
I'll check it soon. It is possible that this may be caused by configuration in my Podfile. I have this fork, but this is only a temporary solution.

**Comment by henninghall** [comment]
Cannot reproduce it, probably something with your setup, try to compare it with a clean react native project
