### ISSUE TITLE
Logo offer for react native date picker

### ISSUE THREAD

**Issue by familqasimov** [henninghall/react-native-date-picker#2]
Hi sir. I'm graphics designer. I have studied your work. I think a simple logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify. Colors were selected as an example. You can write whatever you want.

![react-native-date-picker](https://user-images.githubusercontent.com/36432269/41635319-34e4b254-7459-11e8-8d24-b589b78445e1.png)

Good luck everyday..
BEST REGARD
.

**Comment by henninghall** [comment]
Hi! Wow, really appreciate your effort! Even though I am not very interested in adding these to this project I know someone who might be! Check out https://github.com/AntonNiklasson/react-dategrid/issues and make a request there, good luck!
