### ISSUE TITLE
NPE for "eu-ES" locale

### ISSUE THREAD

**Issue by mars-lan** [henninghall/react-native-date-picker#202]
**Describe the bug**
NPE is thrown when the default locale is set to "eu-ES" (Basque in Spain). This is due to the [getFormatPattern](https://github.com/henninghall/react-native-date-picker/blob/35770eacf96b00539c1edd79bece3a75d5ca27fc/android/src/main/java/com/henninghall/date_picker/wheels/YearWheel.java#L70) returning null.

Similar to https://github.com/henninghall/react-native-date-picker/issues/150, the locale pattern for this language is also a bit funky: `y('e')'ko' MMMM'ren' d('a'), EEEE`. This breaks many of the assumptions made in [LocaleUtils](https://github.com/henninghall/react-native-date-picker/blob/master/android/src/main/java/com/henninghall/date_picker/LocaleUtils.java) and leads to tge failure of extracting the "year" part from the pattern.

**Expected behavior**
No NPE thrown

**To Reproduce**
Set locale to "eu-ES" - Euskara (Espania)

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.62.2
 - react-native-date-picker version 2.7.13

**Comment by henninghall** [comment]
Thanks for reporting this! Fixed by https://github.com/henninghall/react-native-date-picker/pull/204 and released in `v3.0.1`
