### ISSUE TITLE
[Solved] Compilation error on Xcode 12 beta

### ISSUE THREAD

**Issue by killu3000** [henninghall/react-native-date-picker#209]
**Describe the bug**
Multiple semantic issues during compilation, saying that "Property has a previous declaration" for every property in "UIView+React.h"
Maybe the new compiler in Xcode 12 thought that the properties were declared twice, so it threw the error

**Expected behavior**
Build Success
(It used to work fine on Xcode 11)

**To Reproduce**
React-native version: 0.59.9
React-native-date-picker version: 2.7.0
Xcode version: XCode 12 beta 2
   Just build the app

**To Solve (only tested on Xcode 12 beta 2 and Xcode 11.5)**
In file "react-native-date-picker/ios/RNDatePicker/DatePicker.m"
and file "react-native-date-picker/ios/RNDatePicker/RNDatePickerManager.m",

Replace this line:
`#import "UIView+React.h"`

With these lines:
`#if __has_include(<React/UIView+React.h>)`
`#import <React/UIView+React.h>`
`#else`
`#import "UIView+React.h"`
`#endif`

**Comment by henninghall** [comment]
@killu3000 Hi, don't we need this for Xcode 12 anymore?

**Comment by henninghall** [comment]
Seems to be fixed in beta 3

**Comment by navasiloy** [comment]
still experiencing with xcode 12 beta 6
