### ISSUE TITLE
UI has an issue with th locale

### ISSUE THREAD

**Issue by dmitriy-saltovskiy** [henninghall/react-native-date-picker#210]
**Describe the bug**
AM / PM switches on ios are gone, on android their text is cut off
https://prnt.sc/ticma2

**Expected behavior**
Switchers are showing and text is not cut off

**To Reproduce**

```javascript
<DatePicker
     date={date}
     onDateChange={onDateChange}
     locale="th"
     mode="time"
     androidVariant="nativeAndroid"
/>
```

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version 0.62.2
 - react-native-date-picker version 3.0.2

**Comment by henninghall** [comment]
Thanks for reporting! Fixed in ```v3.0.3```

**Comment by henninghall** [comment]
@dmitriy-saltovskiy btw, I am considering adding a modal option to this lib, similar to your screenshot. Would you be interested in sharing some code or even creating a PR for this? 🙂

**Comment by dmitriy-saltovskiy** [comment]
@henninghall
unfortunately I have no code with that example.
for such a result i wrapped datepicker inside https://github.com/jeremybarbet/react-native-modalize.
