### ISSUE TITLE
DatePicker UI breaks when run in Debug on iOS 14 beta

### ISSUE THREAD

**Issue by pstakoun** [henninghall/react-native-date-picker#212]
**Describe the bug**
The DatePicker component looks different in a very unexpected way on the iOS 14 beta. After further investigation, this issue seems to go away in Release mode.

**Expected behavior**
I expect a user interface consistent with that of previous versions.

**Observed behavior**
Initial render, before pressing DatePicker:
![IMG_B79A9282A1EC-1](https://user-images.githubusercontent.com/7063516/88012278-7bb5f580-cae7-11ea-92db-02b367ea13de.jpeg)

After pressing DatePicker, a modal comes up with a calendar:
![IMG_5B1DCF0A98F1-1](https://user-images.githubusercontent.com/7063516/88012338-a56f1c80-cae7-11ea-9572-ece88ad45390.jpeg)

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker date={date} onDateChange={onDateChange} mode="date" />
```

**Smartphone (please complete the following information):**
 - OS: iPhone XS running iOS 14 Beta 2
 - React Native version 0.62.2
 - react-native-date-picker version 2.7.12

UPDATE: After archiving from a non-beta Xcode and deploying a production build, the issue seems to be resolved. I will look into it further and replicate. As of right now, my theory is that it only happens on Debug builds, but I believe this is an issue worth addressing regardless.

UPDATE 07/26: I just got this again on a Release build.

**Comment by henninghall** [comment]
Thanks for reporting! Fixed in ```v3.0.3```

**Comment by pstakoun** [comment]
Thanks for the quick fix!

**Comment by lumotroph** [comment]
Such a pity that this breaks compatibility with XCode <= 11.3.1
