### ISSUE TITLE
Predefined times (hours / minutes)

### ISSUE THREAD

**Issue by lucascroxatto** [henninghall/react-native-date-picker#213]
Hi Henning, is it possible to predefine the hours to be displayed in "time" mode?

For instance, I need to let available just 10:00 am and 3:00 pm. 

Regards and great work!

**Comment by henninghall** [comment]
Hi! It is unfortunately not possible at the moment, tracking this feature request here https://github.com/henninghall/react-native-date-picker/issues/123
