### ISSUE TITLE
Invariant violation: requireNativeComponent "DatePickerManager" was not found in the UIManager

### ISSUE THREAD

**Issue by charbelsako** [henninghall/react-native-date-picker#215]
Why is this error occurring?
I can provide with more info.

**Comment by henninghall** [comment]
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/44

**Comment by charbelsako** [comment]
do I have to run it from Xcode?

**Comment by henninghall** [comment]
No that should not be necessary
