### ISSUE TITLE
maximumDate on android is one day off

### ISSUE THREAD

**Issue by petr166** [henninghall/react-native-date-picker#22]
When setting the `maximumDate` prop to the current date, the maximum selectable date is set to the day before.

Example: 
maximumDate = 12 Sep,
the selector displays options with the last one being 11 Sep

Versions:
react 16.4.1
react-native 0.56.0
android 8.1 (also tested on 7.0)
react-native-date-picker 2.1.1

**Comment by henninghall** [comment]
Thanks for reporting this, I'll have a look at it!

**Comment by marotan3** [comment]
May be related: if I set both a `minimumDate` and a `maximumDate`, on android the app crashes. The dates I use are:

`minimumDate`: 1903-10-19T00:00:00.000Z
`maximumDate`: 2000-10-19T00:00:00.000Z

Versions:
react 16.3.1
react-native 0.55.4
android 8.1.0
react-native-date-picker 2.1.1

**Comment by henninghall** [comment]
Solved by https://github.com/henninghall/react-native-date-picker/commit/44961680e2afeb0e392c4bd7a71f9e6ed3cb8cd4 and released in `v2.2.0`
