### ISSUE TITLE
Scrolling fast makes the date jump around

### ISSUE THREAD

**Issue by andreialecu** [henninghall/react-native-date-picker#221]
**Describe the bug**

Attaching a recording:
![jUqAAavwTi](https://user-images.githubusercontent.com/697707/88696057-6a826f80-d10b-11ea-8f71-d705c73788c4.gif)

It appears that when quickly dragging the date around, the behavior is pretty erratic.

It's worse in practice when moving from date to time:

![Va8LS9Mxde](https://user-images.githubusercontent.com/697707/88696473-fe543b80-d10b-11ea-8475-64c9284721c9.gif)

I think this is a race condition with `onDateChange` firing while a new scroll is initiated and is still in progress. Thus the `date` prop gets updated to the date prior to the current scroll.

**Expected behavior**

Date shouldn't jump around.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
                <DatePicker
                  fadeToColor="none"
                  textColor="#ffffff"
                  date={matchInput.startTime}
                  minuteInterval={15}
                  onDateChange={onDateChange}
                />
```

**Smartphone (please complete the following information):**
 - OS: both
 - React Native version 0.63.1
 - react-native-date-picker version 3.0.3

**Comment by andreialecu** [comment]
If I remove the `date` prop from the `DatePicker` it stops jumping:

```ts
<DatePicker
  fadeToColor="none"
  textColor="#ffffff"
  // date={matchInput.startTime}
  minuteInterval={15}
  onDateChange={onDateChange}
/>
```

This should confirm it's some sort of race condition.

**Comment by andreialecu** [comment]
Further confirmation:

```ts
    const onDateChange = useCallback((date: Date): void => {
      console.log(date);
      setDate(date);
    }, []);

```

```
[Tue Jul 28 2020 20:13:19.497]  LOG      2020-08-18T10:30:00.000Z
[Tue Jul 28 2020 20:13:19.940]  LOG      2020-08-19T10:30:00.000Z
```

Seeing the two `console.log`s within 0.4s of each other. Noticed date jump from one date to another.

I will add a debounce temporarily.

**Comment by henninghall** [comment]
Great investigation! 🏆 I'll look into it

**Comment by henninghall** [comment]
Fixed in v3.1.0

**Comment by N1ghtly** [comment]
@henninghall it seems this is only a fix for Android? We are still running into this issue on iOS.

**Comment by felixchan** [comment]
iOS seems to have this issue.
