### ISSUE TITLE
Date picker fails to compile upon building 

### ISSUE THREAD

**Issue by charbelsako** [henninghall/react-native-date-picker#224]
**Describe the bug**
After installing the package and running `pod install` in the iOS folder, 
running  `react-native run-ios` fails on building the library Datepicker.m

**Expected behavior**
expected to compile

```
 /Users/charbel/Desktop/AwesomeProject/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:18: property 'preferredDatePickerStyle' not found on object of type 'DatePicker *'

            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
                 ^



❌  /Users/charbel/Desktop/AwesomeProject/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:45: use of undeclared identifier 'UIDatePickerStyleWheels'

            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
```

**Smartphone (please complete the following information):**
 - OS: iOS 13.3
 - React Native version 0.63.2
 - react-native-date-picker version 3.0.3

**Comment by henninghall** [comment]
Hi, what error do you get? What is your Xcode version?

**Comment by charbelsako** [comment]
Sorry forgot to post it

**Comment by henninghall** [comment]
Thanks, could you try upgrade to Xcode 11.6 if not already having it?

**Comment by charbelsako** [comment]
I can't upgrade to 11.6 I have an old Mac

**Comment by henninghall** [comment]
Ah okay then we need to find a solution for it, meanwhile you can downgrade to 3.0.2

**Comment by henninghall** [comment]
@charbelsako from what year is your mac? pro/air?

**Comment by charbelsako** [comment]
Pro, Mid 2012

**Comment by charbelsako** [comment]
I did not upgrade Xcode.
But I am gonna do it later on.

**Comment by henninghall** [comment]
Alright, Xcode 11.6 will probably resolve this issue, let me know if it doesn't and we'll reopen this issue.
