### ISSUE TITLE
[Android] DatePicker isn't showing on Android, only on iOS

### ISSUE THREAD

**Issue by enrickdl** [henninghall/react-native-date-picker#229]
**Describe the bug**
Both android variants "iosClone" and "nativeAndroid" isn't displaying on the app. Instead, what is being displayed is the normal android calendar date picker:

<div align="center" >
<img src="https://user-images.githubusercontent.com/65981081/89658728-45c58f00-d8a5-11ea-9c49-3a31b9dd5c3e.png" width="20%">
</div>

iOS version is working like a charm!

**Expected behavior**
Display either the "iosClone" or "nativeAndroid" variant when opening the DatePicker.

**To Reproduce**
```javascript
<DatePicker
            maximumDate={pastOnly ? new Date() : undefined}
            minimumDate={this.minimumDate}
            mode={isDateTime ? 'datetime' : 'date'}
            date={date ? moment(date).toDate() : new Date()}
            onDateChange={(date) => handleDateChange(date)}
            textColor={colors.black}
            style={{ alignSelf: 'center' }}
          />
```

or 

```javascript
<DatePicker
            maximumDate={new Date()}
            mode={eventToCreate.show_time ? 'datetime' : 'date'}
            date={eventToCreate.timestamp ? new Date(eventToCreate.timestamp) : new Date()}
            onDateChange={(date) => this.handleDateChange(date)}
            textColor={colors.black}
            style={{ alignSelf: 'center' }}
            androidVariant="nativeAndroid"
          />
```
**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [0.63.0]
 - react-native-date-picker version [3.1.0]

**Comment by henninghall** [comment]
How does your import line look like?

**Comment by enrickdl** [comment]
I'm importing as `import DatePicker from 'react-native-date-picker'`.

Also, I did run pod install, iOS is working, unfortunately, isn't working on Android :(

**Comment by henninghall** [comment]
Ok, have you previously installed another datepicker?

**Comment by enrickdl** [comment]
Yep, I had `@react-native-community/datetimepicker installed`, do you think some sort of conflict was happening? I do remember having that dependency uninstalled and it didn't work either

**Comment by henninghall** [comment]
I suspect that some kind of conflict might happen since there is no code for showing that picker in this lib. Have you tried removing the other lib from package.json and deleting node modules?

**Comment by enrickdl** [comment]
Just tried again and it didn't work :(  This time I uninstalled and removed node_modules before installing `react-native-date-picker` and it only works on iOS again.

My Steps: 
- remove `@react-native-community/datetimepicker` and `rm -rf node_modules` and run yarn again.
- `yarn add react-native-date-picker` and `cd ios && pod install`
- `import DateTimePicker from '@react-native-community/datetimepicker'` and added to my code.
- Tried on iOS 👍 
- Tried on Android 👎

**Comment by enrickdl** [comment]
I just test it out on a fresh 0.63 React Native project and it worked. So something must be happening on my work project that is not allowing this lib working on android. I'll check It out.

**Comment by enrickdl** [comment]
Case Closed! There was a method within the app that only showed a specific time picker for android. Since this project is 3 years old, I believe that this made sense back in time.

react-native-date-picker is working like a charm! Thanks for your time, @henninghall!
