### ISSUE TITLE
Width style not applied on Android (to stretch the date picker)

### ISSUE THREAD

**Issue by ttristan** [henninghall/react-native-date-picker#233]
Setting `<DatePicker style={{ width: Dimensions.get('screen').width }} />` works on iOS but not and Android since 3.1.0
Relates to #145 #222

**In Version 3.2.0:**
iOS
<img width="454" alt="1" src="https://user-images.githubusercontent.com/24268434/90978334-6d775100-e54d-11ea-82eb-7f8cf5dbb461.png">

Android
<img width="395" alt="2" src="https://user-images.githubusercontent.com/24268434/90978333-6cdeba80-e54d-11ea-8bce-cb093dc3ba06.png">

**In Version 3.0.3**
iOS (same as 3.2.0)

Android
<img width="394" alt="3" src="https://user-images.githubusercontent.com/24268434/90978332-6bad8d80-e54d-11ea-8d31-579da241fe06.png">

Using `maxWidth: 320`
<img width="396" alt="maxwidth" src="https://user-images.githubusercontent.com/24268434/90978330-694b3380-e54d-11ea-9dd1-4b275f2bdf39.png">

**Comment by henninghall** [comment]
Thanks for reporting this! fixed in v3.2.1
