### ISSUE TITLE
Android: wrong width with 3.2.1

### ISSUE THREAD

**Issue by tapz** [henninghall/react-native-date-picker#235]
**Describe the bug**

The component lines are too wide in 3.2.1 and the component is not properly centered.

3.2.1:
![IMG_7918](https://user-images.githubusercontent.com/11726387/91037963-9ca3c600-e612-11ea-9142-608737525c29.jpeg)

**Expected behavior**

3.2.0:
![IMG_7919](https://user-images.githubusercontent.com/11726387/91037978-a299a700-e612-11ea-9878-ba0f545b22fd.jpeg)

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
          date={props.time || new Date()}
          mode='time'
          onDateChange={props.onTimeChanged}
          textColor={colors.textColor}
          minuteInterval={5}
          androidVariant="iosClone"
        />
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.63.2
 - react-native-date-picker version 3.2.1

**Comment by henninghall** [comment]
Fixed in version 3.2.2. Centered it and made it a bit more narrow by default but not as much as you requested since the time picker on iOS is wider. You can achieve a more narrow look by setting your own preferred width by `style={{ width: 100px }}` etc
