### ISSUE TITLE
If locale is "da" ( Demark ), app crashes.

### ISSUE THREAD

**Issue by tarouboy** [henninghall/react-native-date-picker#236]
There are only year and month available, when you try to change the month or year, it crashes immediately. ( Android Only. iOS is fine )
I couldn't catch the error so not sure what happened.
I believe the date formatting issues.

Maybe can suggest a list of supported Locales?

**Comment by henninghall** [comment]
> There are only year and month available

What do you mean by this?

I don't manage to reproduce it, could you please supply a code sample where this problem occurs?

**Comment by henninghall** [comment]
I've tried da locale on date mode but I can't reproduce the error. Please provide a reproducible sample and I will try to fix your problem 🙂
