### ISSUE TITLE
onDateChange not called when date / time is selected/clicked. Gets called only when selection through scroll

### ISSUE THREAD

**Issue by ganeshdongre** [henninghall/react-native-date-picker#238]
**Describe the bug**
I liked the component as it bundles date & time together and selection is very simple.  
I find onDateChange() is not fired when I select the date by clicking on the date/time from the list (say as in screenshot Sept 6/Sept 8 OR Time 2/4  OR Values above or below the current selected). Scroll on the date/hour/min/am-pm does fire this callback. 
 
![image](https://user-images.githubusercontent.com/44608201/92382197-d522c400-f129-11ea-8b90-f9ffc3e3f4ba.png)

**Expected behavior**
the callback has to get called even for date/time click event

**To Reproduce**
<DatePicker
  date={this.state.est_dely_date? this.state.est_dely_date : new Date()}
  onDateChange={date => {
  console.log(date);
  this.setState({...this.state, est_dely_date: date});
  }}
  minuteInterval={30}
  androidVariant="nativeAndroid"
/>

**Smartphone (please complete the following information):**
 - OS: Tested on Android
 - React Native version - : "0.61.5",
 - react-native-date-picker version "3.2.2",

**Comment by henninghall** [comment]
Thans for reporting this, I'll look into it!

**Comment by soltysaleksandr** [comment]
same issue, doesn't work only for Android(iOS works as expected)

tested on:
React Native version - : "0.62.1",
react-native-date-picker version "2.7.9"
react-native-date-picker version "3.2.2"

**Comment by henninghall** [comment]
Released a fix for this in v3.2.3

**Comment by arun-xza** [comment]
This does FIX seems only to be working for inline mode but not working in "MODAL" mode.

**Comment by oguzydz** [comment]
any update?
same issue with @arun-xza

**Comment by henninghall** [comment]
onDatechange is not suppose to work with modal, use onConfirm instead. Does that help or same issue there?

**Comment by ericpoulinnz** [comment]
@henninghall can the documentation be updated to reflect that? It took me a while wondering why the library wasn't working until I found this thread.

For what it's worth, there are use-cases where `onDateChange` should fire in a modal, I don't see why limiting it to only work for inline is necessary.
