### ISSUE TITLE
Can anyone help me with responsiveness?

### ISSUE THREAD

**Issue by VisitPlan** [henninghall/react-native-date-picker#239]
Hello Team,

Thank you for this Greate Library.

I am facing the Responsiveness issue with small screens. Can someone help me how to make it responsive?

Thanks

**Comment by henninghall** [comment]
Hi, I don't really understand what you mean, could you send screenshots or video of your problem?

**Comment by VisitPlan** [comment]
Please find the screenshot and the Video link. I have given width and height as 25% of the screen width and 10% screen height.
![WhatsApp Image 2020-09-10 at 12 38 32 PM](https://user-images.githubusercontent.com/58108991/92787395-af661b00-f3c6-11ea-8b11-3848ef7bde65.jpeg)
[Screen Record](https://drive.google.com/file/d/11pg_cUtIP7d7y3OrckieQ7wY1c3Edj4F/view?usp=sharing)

**Comment by henninghall** [comment]
That picker size is unfortunately not supported. I would try to make the container bigger or put the picker in a modal or on another page.
