### ISSUE TITLE
Error while using in IOS 

### ISSUE THREAD

**Issue by stuart-ithands** [henninghall/react-native-date-picker#241]
Property 'preferredDatePickerStyle' not found on object of type 'DatePicker 

Use of undeclared identifier 'UIDatePickerStyleWheels'

 if(@available(iOS 14, *)) {
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;     // Error here
        }

**Comment by henninghall** [comment]
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/224
