### ISSUE TITLE
IOS 14 compatibility

### ISSUE THREAD

**Issue by Toxer10** [henninghall/react-native-date-picker#245]
Will there be an update of datepicker for IOS 14 devices? From IOS 14 the native datepicker looks completely different and app crashes when interacting with it.
![image](https://user-images.githubusercontent.com/25991946/94145978-fc90c500-fe7b-11ea-81ab-a9d73b6a7741.png)

**Comment by henninghall** [comment]
As far as I know this has been resolved and released, have you tried the latest version? See https://github.com/henninghall/react-native-date-picker/issues/212

**Comment by Toxer10** [comment]
@henninghall Oh, really, didn't see it. Thanks for your work and quick answer. This package is lit 🔥
