### ISSUE TITLE
Android, dates not visible on [mode={'date'}]

### ISSUE THREAD

**Issue by shivdotpy** [henninghall/react-native-date-picker#247]
**Describe the bug**
In IOS running perfectly, but in Android dates not visible

**Expected behavior**
Date Should be visible on 

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  render = () =>
    <DatePicker
          style={{
            flex: 1,
            justifyContent: 'flex-end',
          }}
          date={date}
          mode={'date'}
          androidVariant="iosClone"
          onDateChange={(date) => {
            setDate(date);
            setDateSelected(true);
          }}
          minimumDate={new Date()}
        />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version : 0.63.0
 - react-native-date-picker version : ^3.1.0

<img width="319" alt="Screenshot 2020-09-28 at 8 59 35 PM" src="https://user-images.githubusercontent.com/13102582/94452769-84a10280-01cd-11eb-80c6-aa956a021f67.png">

**Comment by henninghall** [comment]
Hi, which locale or language on your phone are you using?

**Comment by henninghall** [comment]
Please reply and I will investigate this problem

**Comment by himanshupadia** [comment]
@shivdotpy I am also facing same problem, did you find any solution for this.
```
<DatePicker
                style={{ width: width }}
                mode="datetime"
                androidVariant="iosClone"
                date={new Date()}
                locale="us"
                minimumDate={new Date()}
                onDateChange={(date) => {
                  this.onDateChange(date);
                }}
                textColor={color.BLACK}
              />
```
@henninghall if you have any solution, please let me know

**Comment by cymen** [comment]
Solution to this is to set the color in `styles.xml` using:

`<item name="android:textColorPrimary">@color/black</item>`

Found via https://stackoverflow.com/questions/31321039/material-date-picker-text-color however I had to use a lowercase `black` not `Black` as otherwise I had an error. You could of course just use `#000` or one of the other color variants too.
