### ISSUE TITLE
Different UI on IOS 14

### ISSUE THREAD

**Issue by bahtiyarerden** [henninghall/react-native-date-picker#248]
I am getting bug from https://github.com/react-native-community/datetimepicker/issues/285#issue-705637780

I am currently preparing my app for the iOS 14. I have noticed that the date picker is not what it used to be.

Here is what it looks like on iOS 13.7:

![](https://user-images.githubusercontent.com/10779996/93776147-f0162d80-fc2b-11ea-990d-295829d7de77.png)

Here is the iOS 14 version:

![](https://user-images.githubusercontent.com/10779996/93776428-2d7abb00-fc2c-11ea-8b59-830605576f7b.png)

![](https://user-images.githubusercontent.com/10779996/93776669-7894ce00-fc2c-11ea-942e-6243a7077d0e.png)

There is now an extra step, instead of spinning the wheel, I need to press it to trigger another calendar popup.

I use display: "spinner" prop.

Is there any way I can still use the wheel on iOS 14?
**Environment info**
``react-native info`` output:

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 391.89 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/pavelermakov/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
```

 - OS: iOS
 - React Native version 0.59.10
 - react-native-date-picker version 2.7.3

**Comment by bahtiyarerden** [comment]
It fixed on new version

**Comment by luojiong** [comment]
Which method did you use to solve the problem @bahtiyarerden

**Comment by bahtiyarerden** [comment]
I updated library to 3.2.3 version. I checked the library versions and it seems to fixed at v3.0.3

**Comment by luojiong** [comment]
Okay, thanks for your answer, I will try to update to the latest version

**Comment by phuquoc164** [comment]
@luojiong Did you fixed your problem ? I have the same problem
