### ISSUE TITLE
Android mode="date" There are 31 days in February

### ISSUE THREAD

**Issue by baronhsiao** [henninghall/react-native-date-picker#249]
**Describe the bug**
There are 31 days in February.

**Expected behavior**
There are only 29 days or only 28 days in February.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
        <DatePicker
          mode="date"
          androidVariant="iosClone"
          minimumDate={new Date('1900/01/01')}
          maximumDate={new Date()}
          date={new Date()}
          onDateChange={date => { console.log(date) }}
        />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [0.61.4]
 - react-native-date-picker version [3.2.2]

**Comment by henninghall** [comment]
Thanks for reporting this. This is intentional and similar to how the iOS picker works: the date will exist but you can't stop the wheel on that date. Making an android specific solution of how things work is usually out of scope of this package.

**Comment by baronhsiao** [comment]
@henninghall But I can stop the wheel on 31 days in February and I get the value is March 3.
