### ISSUE TITLE
Bug - Unable to resolve module 'moment' from 'node_modules/...'

### ISSUE THREAD

**Issue by stephanoparaskeva** [henninghall/react-native-date-picker#252]
<img width="408" alt="Screenshot 2020-10-13 at 18 12 34" src="https://user-images.githubusercontent.com/40718272/95893376-c9a56700-0d7f-11eb-98cf-dbd963a19eab.png">

 - OS: IOS/Android
- `"react-native": "^0.63.3",`
- `"react-native-date-picker": "^3.2.4",`

**Comment by henninghall** [comment]
Looks like something isn't cleared properly after your update, try the 4 steps suggested in the error message, did it help?

**Comment by stephanoparaskeva** [comment]
> Looks like something isn't cleared properly after your update, try the 4 steps suggested in the error message, did it help?

Yes this was all I needed to do, thanks!
