### ISSUE TITLE
Disable 12-hour system?

### ISSUE THREAD

**Issue by andry1001** [henninghall/react-native-date-picker#254]
Hey!

Any ways to disable 12-hour system (AM/PM), but keep locale?

**Comment by henninghall** [comment]
Nope, in what situation would you like to do this?

**Comment by andry1001** [comment]
For example in Estonia we do not use 12 hour AM/PM system. When I set Estonian locale it has the right translations, but the AM/PM time is there.

**Comment by henninghall** [comment]
Hmm in that case it should work by default. On android you need to set `is24hourSource='locale'` if you want to override the phone's 24h-setting. 

Are you having the problem on iOS or Android? I tried to set `locale='et'` and it uses 24h format for me.

**Comment by andry1001** [comment]
On Android, updated from 3.02 -> 3.2.5 and the same code works now.

```
<DatePicker
    date={new Date(props.date)}
    onDateChange={props.onChange}
    style={styles.datePicker}
    locale={I18n.locale}
    textColor={colors.primaryTextColor}
    mode={props.mode ? props.mode : "datetime"}
    is24hourSource='locale'
    fadeToColor='none'
 />

However the `fadeToColor='none'` throws "Invalid color: none" now and I couldn't find a way to get rid off the fade color. It was completely transparent before.
```
