### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Vickshine** [henninghall/react-native-date-picker#257]
Open often, select times, and close。 It will be crash.(version: v3.2.4  android)
log:
System.err: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class <unknown>\
System.err: Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class <unknown>\
System.err: Caused by: java.lang.reflect.InvocationTargetException\
System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)\
System.err:     at android.view.View.inflate(View.java:21052)\
System.err:     at com.henninghall.date_picker.PickerView.update(PickerView.java:36)\
System.err:     at com.henninghall.date_picker.DatePickerManager.onAfterUpdateTransaction(DatePickerManager.java:68)\
System.err:     at com.henninghall.date_picker.DatePickerManager.onAfterUpdateTransaction(DatePickerManager.java:28)\

**Comment by henninghall** [comment]
Hi @Vickshine , can you provide a code example of how you're using the picker?

**Comment by Vickshine** [comment]
like this:
<DatePicker
                            style={styles.pickerStyle}
                            date={this.state.date}
                            mode="time"
                            timeZoneOffsetInMinutes={8*60}
                            onDateChange={(date) => {
                                this.setState({date: date})
                            }}
                        />

**Comment by henninghall** [comment]
Fixed in https://github.com/henninghall/react-native-date-picker/pull/286 and release in v3.2.8
