### ISSUE TITLE
IOS 14 update maintenante needed

### ISSUE THREAD

**Issue by hugoh59** [henninghall/react-native-date-picker#259]
the look of the datepicker has considerably changed in ios14 and the datepicker does not look like anything anymore, this needs an update in order to work with ios14. thank you

**Comment by tsdmrfth** [comment]
I have same problem. I will try to implement bottom date picker for iOS 14 in this repository by opening a pull request

**Comment by henninghall** [comment]
@tsdmrfth Are you running the latest version of the package?

**Comment by tsdmrfth** [comment]
@henninghall No. I think you solved the problem in latest version.
