### ISSUE TITLE
Time picker gets funky due to daylight saving 

### ISSUE THREAD

**Issue by mars-lan** [henninghall/react-native-date-picker#262]
**Describe the bug**
11/1 is the day that daylight saving ends for US. There's a few things that went wrong on that day:
* The AM/PM selectors show only AM/AM
* Missing hour (7 in this case) in the hour selector

![Screenshot_20201101-021827_TrayMinder](https://user-images.githubusercontent.com/24240669/97804064-52d2ef80-1c02-11eb-988f-d613a77b33a1.jpg)
![Screenshot_20201031-203059_TrayMinder](https://user-images.githubusercontent.com/24240669/97804063-51092c00-1c02-11eb-9f51-942611841db3.jpg)

**Expected behavior**
No strange behavior on the daylight saving start/end dates

**Comment by ryanoconnor7** [comment]
We are also seeing this issue.

**Comment by jmkmay** [comment]
Any findings so far @ryanoconnor7 @mars-lan ? We got this too. Oddly only an issue on Android though.

**Comment by jmkmay** [comment]
Changing date to tomorrow (Nov 2) seems to resolve this... I think it's actually an Android related bug. Even the Twitter app is showing all Tweets, including ones from days or weeks ago, as "1 day ago". Hopefully this resolves itself by tomorrow.

**Comment by navasiloy** [comment]
same issue

**Comment by wmonecke** [comment]
Hi, I am also seeing this issue! Sometimes the same hour appears twice.

**Comment by mars-lan** [comment]
@henninghall any chance of fixing this soon before other countries start changing their time?

**Comment by wmonecke** [comment]
@mars-lan Ill try to debug the issue tomorrow and let you guys know what might be causing the issue

**Comment by jmkmay** [comment]
@wmonecke for the record, this issue completely went away a day after the date change. It waas just Nov. 1 that it was an issue. I think its an Android bug.

**Comment by mars-lan** [comment]
@henninghall pinging this again. If it' due to daylight saving this might happen again in a couple of month.

**Comment by henninghall** [comment]
I've tried but I didn't manage to reproduce it. Would be great if you could provide some more details. @mars-lan 

1. Was this only a problem on the actual date of the daylight saving switch? Or can you still reproduce it today by going back and selecting a date on the 11/1?

2. Can Which timezone did you see this in?

**Comment by mars-lan** [comment]
1. I can easily reproduce the issue by changing the system date to 11/1/20
2. Pacific time (GMT-08:00), but any US time zones will work as they all end daylight saving on the same date.

**Comment by henninghall** [comment]
Managed to fix these issues. Released in `v3.2.9`
