### ISSUE TITLE
How to hide/remove/ disable particular date between minimum date and maximum date

### ISSUE THREAD

**Issue by gdhelp03** [henninghall/react-native-date-picker#263]
Hi, my code is like

`  <DatePicker date={this.state.date}  onDateChange={""} mode={'datetime'}  is24hourSource="locale" locale='en-IN'  minimumDate={"2020-11-01"} maximumDate={"2020-11-10"} />`

1. In the above scenario, it will show date from 2020-11-01 to 2020-11-10 and I want to hide/remove/disable few dates like 2020-11-05, 2020-11-06 from the list.
 
2. If possible can we add minimum time and maximum time like date, above mentioned.

please add this feature if not available or if available please provide the example

**Comment by henninghall** [comment]
Unfortunately, this is not supported and will not be due to limitations of UIDatePicker on iOS
