### ISSUE TITLE
How to set the date picker full width

### ISSUE THREAD

**Issue by ajitdas123** [henninghall/react-native-date-picker#266]
**Describe the bug**
I am trying to set the calendar full width, but its width remains the same

**Expected behavior**
I was expecting to take it full width

<img width="548" alt="Screenshot 2020-11-29 at 7 40 45 PM" src="https://user-images.githubusercontent.com/20204881/100544315-cd7f4100-327a-11eb-85cf-1d5e552d6870.png">

**To Reproduce**
```
 <DatePicker
         mode={'date'}
         date={this.props.current}
         androidVariant="nativeAndroid"
         maximumDate={this.props.maximumDate}
         minimumDate={this.props.minimumDate}
         style={{width:windowWidth-32}}
         onDateChange={(date) => this.handleDateSelection(date)}
 />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.63.2]
 - react-native-date-picker version [3.2.5]

**Comment by henninghall** [comment]
Hi! That's a limitation of the native picker varaint, if you really need this feature, try the ios clone variant.
