### ISSUE TITLE
31 days in October

### ISSUE THREAD

**Issue by naveendevs** [henninghall/react-native-date-picker#267]
Dynamic number of days are not handled and onChange returns the next month than that of selected, in that case.

Can this be handled?

**Comment by henninghall** [comment]
Android or iOS? Which picker variant?

**Comment by naveendevs** [comment]
@henninghall Android, iOS clone and native vairant

**Comment by henninghall** [comment]
What date are you trying to select when getting the wrong date? October has 31 days as far as I know 😉

**Comment by henninghall** [comment]
Please provide a reproducible example and I will reopen the issue

**Comment by kamlesh1000** [comment]
I am exactly facing the same issue.
When I tried to select "31st Feb" which is invalid date, I was allowed to select it, but returned "3rd March" on select.
This is only issue on android device. It's perfect on ios as it doesn't allow the invalid date selection at all.
mode="date"
androidVariant="iosClone"

**Comment by henninghall** [comment]
Fixed in `v3.2.7`
