### ISSUE TITLE
{Question} Confirm and Cancel Buttons?

### ISSUE THREAD

**Issue by the-dut** [henninghall/react-native-date-picker#270]
I'm not seeing any way to actually submit the date they pick. Is there supposed to be a confirm/cancel or select/cancel buttons that show up?  I'm not seeing any.  Thanks!

**Comment by henninghall** [comment]
Good question! it is up to you to implement that yourself, if you want that in your application. Since it is a common pattern I consider adding a default implementation of that in the future.
