### ISSUE TITLE
Order of date is different on Pixel 2 devices

### ISSUE THREAD

**Issue by mitjnextt** [henninghall/react-native-date-picker#274]
Hey there,

On the most of devices we checked the order of the date format is Day - Month - Year

but on Pixel 2 Device, It shows Month - Day - year.

Is there any props I'm missing to reorder it??

![Item 14](https://user-images.githubusercontent.com/67790880/102584270-20d30980-412c-11eb-9777-19bd5090a97b.jpeg)

**Comment by henninghall** [comment]
The order is determined by the locale, if no locale is forced by the locale prop it will use the phone language. Are there different phone languages on the two devices?
