### ISSUE TITLE
App crashes when in production mode

### ISSUE THREAD

**Issue by ralphhovsepian** [henninghall/react-native-date-picker#276]
The package works perfectly on my emulator. But when its on production mode, the date mode works but the datetime mode doesnt work and crashes (Android). ive tried to disable proguard, or do the same as mentioned in the documentation but it is still not working.

`

                <DatePicker androidVariant={Platform.OS === 'android' ? 'nativeAndroid' : 'iosClone'}

                date={startDate}

                onDateChange={(e) => startDateChange(e)}

                mode={isEnabled ? 'date' : 'datetime'}

              />
`

**Comment by henninghall** [comment]
Hi, could you provide the stack trace? 🙂

**Comment by ganesh-papola** [comment]
@ralphhovsepian any solution?

**Comment by henninghall** [comment]
If this is an OutOfMemory crash, it is resolved in the lastest version 3.2.8. If not, please provide the stack trace and I'll look into it!

**Comment by bekirytm** [comment]
I am using version 3.3.0 and this error still persists.
It suddenly kicks out of the app.
