### ISSUE TITLE
Pick invalid dates too in android only

### ISSUE THREAD

**Issue by kamlesh1000** [henninghall/react-native-date-picker#277]
I am exactly facing the same issue.
When I tried to select "31st Feb" which is invalid date, I was allowed to select it, but returned "3rd March" on select.
This is only issue on android device. It's perfect on ios as it doesn't allow the invalid date selection at all. Please reopen this issue.
mode="date"
androidVariant="iosClone"

**Comment by henninghall** [comment]
Fixed in `v3.2.7`
