### ISSUE TITLE
onDateChange wont trigger after setting locale

### ISSUE THREAD

**Issue by teclagual** [henninghall/react-native-date-picker#28]
Adding the locale "es" does change the language of the DatePicker to spanish, but onDateChange stopped triggering.

If I remove the locale, onDateChange works again.

`import React from 'react';
import { View, Text } from 'react-native';
import DatePicker from 'react-native-date-picker';

export default class Citas extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            date: new Date(),
        };
    }

    render() {
        console.log(this.state.date);
        return (
            <View>
                <Text>New Cita Component</Text>
                <DatePicker
                    date={this.state.date}
                    mode="date"
                    onDateChange={date => this.setState({ date })}
                />
            </View>
        );
    }
}`

**Comment by henninghall** [comment]
Thanks for reporting this, I will have a look at it!

**Comment by Time-erhu** [comment]
format='YYYY-MM-DD HH:mm'   like "2018-11-12  13:04"

**Comment by phithu** [comment]
+1

**Comment by henninghall** [comment]
Fixed by https://github.com/henninghall/react-native-date-picker/commit/228ae9bf9171712b5cc97b270b63f696743d9070 and released in `v2.2.1`
