### ISSUE TITLE
onDateChange always return the current date.

### ISSUE THREAD

**Issue by SaadAli-rolustech** [henninghall/react-native-date-picker#283]
**Describe the bug**
onDateChange always return the current date. It does not return the selected date.

**Expected behavior**
It should return the newly selected date.

**To Reproduce**
const CustomeDatePicker = () => {
    const [date, setDate] = useState(new Date());

    const dateChanged = newDate => {
        console.log('____________________________');
        console.log(newDate);
        console.log('____________________________');
    };

    return (
        <DatePicker
            // maximumDate={new Date()}
            // mode="date"
            date={date}
            onDateChange={dateChanged}
        />
    );
};

export default CustomeDatePicker;
```

**Smartphone (please complete the following information):**
 - OS: [iOS] (haven't tested on Android yet)
 - React Native version [0.63.0]
 - react-native-date-picker version [3.2.7]

**Comment by henninghall** [comment]
I don't manage to reproduce it, what is your iOS version, iPhone model and what phone language do you use?

**Comment by SaadAli-rolustech** [comment]
iOS version : 14
ipad pro 4th gen
language enUS

**Comment by jaynguyen89** [comment]
Same issue on Android, tested from API 27 to 30.

**Comment by henninghall** [comment]
@jaynguyen89 Since timezone offset isn't used in the above example I believe it is a separate issue. If you could supply a different issue with a reproducible example, I am happy to investigate it.

**Comment by henninghall** [comment]
@SaadAli-rolustech I don't manage to reproduce the issue. I've tried your exact device, ios version, react native and datepicker version. 

Does the same problem occur when running this code? 

```jsx
import React, { useState } from 'react'
import DatePicker from 'react-native-date-picker'

export default () => {

  const [date, setDate] = useState(new Date())

  const onDateChange = (date) => {
    console.log(date)
    setDate(date)
  }

  return (
    <DatePicker
      date={date}
      onDateChange={onDateChange}
    />
  )
}
```

**Comment by henninghall** [comment]
If you are still having this problem, please try the snippet above and I will reopen this issue.

**Comment by ajitdas123** [comment]
@henninghall,  I am also facing the same issue, I have tried with your snippet above with little changes and the issue came back. Here is my snippet
```
handleSelectedMonthYear =(date) => {
 const timeStamp = moment(time).format('YYYY-MM-DD');
  this.setState({
            selectedMonthYear: timeStamp,
        }, () => {
            console.log('State', this.state);
        });
}

 <DatePicker
        mode={this.props.datePickerMode}
        date={currentDate}
        androidVariant="nativeAndroid"
         maximumDate={this.props.maximumDate}
         minimumDate={this.props.minimumDate}
         onDateChange={(date) => {
           console.log('Date',date);
           this.handleSelectedMonthYear(date)
         }}
         />
 ```
 My Props are as follows
 ```
MAX DATE:  Fri Feb 16 2007 09:38:45 GMT+0530 (India Standard Time)
MIN DATE:  Tue Feb 16 1971 09:38:40 GMT+0530 (India Standard Time)
Current date:  Wed Feb 10 2021 00:00:00 GMT+0530 (India Standard Time)

 ```
Platform: IOS
Package Version:    "react-native-date-picker": "^3.2.9",
React native: 0.63.3
 
![Screen Recording 2021-02-16 at 9 45 46 AM](https://user-images.githubusercontent.com/20204881/108017999-777d9680-703c-11eb-9c24-4e0ea6cd0aec.gif)

**Comment by henninghall** [comment]
Thanks for the video and explanation! 

You've set the max date to 2007, that's why you want get onchange callbacks after that date. (and it automatically scrolls back). Does it work for years before 2007?

**Comment by jmkitavi** [comment]
@henninghall I understand this is a closed issue.
But I am having a similar problem on my Android.

After several tests it seems to be happening when I set a maximumDate

**Comment by satyabrata45** [comment]
I am having a similar problem with my ios

https://user-images.githubusercontent.com/96112237/180928480-e4b6001f-564a-4f5c-8a9f-711a547c62b7.mp4

.

**Comment by ThushalIntervest** [comment]
I am also having this issue. Every time i change date, onDateChange function not calling.
