### ISSUE TITLE
mode not working  on android

### ISSUE THREAD

**Issue by Harpalsinh-Jadav** [henninghall/react-native-date-picker#284]
whether I use mode={'date'} or mode={'time'} or mode={'datetime'}  it is giving me DateTime out put of mode={'datetime'} in android.
Also, width is given 100% but it's also not applied.

```
const [date, setDate] = useState('');
 date == '' ? setDate(new Date()) : null;

return (
    <View >
            <DatePicker
              date={date}
              onDateChange={(value) => {
                setDate(value);
              }}
              mode={'time'}
              maximumDate={Date()}
              style={{width: '100%', height: ScreenHeight * 0.265}}
            />

            <DatePicker
              date={date}
              onDateChange={(value) => {
                setDate(value);
              }}
              mode={'datetime'}
              maximumDate={Date()}
              style={{width: '100%', height: ScreenHeight * 0.265}}
            />

            <DatePicker
              date={date}
              onDateChange={(value) => {
                setDate(value);
              }}
              style={{width: '100%', height: ScreenHeight * 0.265}}
              mode={'date'}
            />
    </View>
  );
```

My react-native version --> 0.63.4
 here is output image--> `https://ibb.co/7XC2wWw`

**Comment by henninghall** [comment]
There are several problems with your code.
1. The date object should never be a string. Don't use setDate in the render function. Use new Date() in the useState as in the example in the README. 
2. Style cannot be set to a percentage as described in the error message you should have received.
3. MaximumDate needs to be set to `new Date()` not `Date()` or you will get an error. 

These errors are causing the picker to not behave as expected.
