### ISSUE TITLE
Date not change in release iOS

### ISSUE THREAD

**Issue by nwpnkmngm** [henninghall/react-native-date-picker#285]
I got date cannot change when release on iOS

language : enUS

here my code

     <DatePicker mode="date"
                            style={{ width: vw(100), marginTop: 30 }}
                            locale='en-US'
                            date={new Date(personalData.birthdate)}
                            textColor={Platform.OS == 'android' ? colors.black : colors.pickerItem}
                            onDateChange={handleOnSelectDate}
                        />
                        
    const handleOnSelectDate = date => {
        let [m, d, y] = new Date(date).toLocaleDateString().split("/")
        if (Number(y) > 2020) y = 2020
        setPersonalData({ ...personalData, birthdate: `${y}-${m}-${d}` })
    }

**Comment by henninghall** [comment]
Hi, thanks for reporting this.

1. Does it only happen in a release build? 
2. Does it happen when you run the following code? https://github.com/henninghall/react-native-date-picker#minimal-example

**Comment by henninghall** [comment]
3. How does your import line look like?

**Comment by henninghall** [comment]
If you are still having this problem, please answer the questions above and I will reopen this issue.
