### ISSUE TITLE
onDateChange not fired in some Huawei Honor devices

### ISSUE THREAD

**Issue by tapz** [henninghall/react-native-date-picker#288]
**Describe the bug**
onDateChange is not fired in some Huawei Honor devices

**Expected behavior**
onDateChange is called

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
  style={styles.datePicker}
  date={props.time || new Date(2100, 0, 1, 0, 0, 0, 0)}
  mode='time'
  onDateChange={props.onTimeChanged}
  textColor={colors.textColor}
  minuteInterval={5}
/>
```

**Smartphone (please complete the following information):**
 - OS: Android 7
 - React Native version 0.63.4
 - react-native-date-picker version 3.2.10

**Comment by henninghall** [comment]
Hi @tapz! Do you get any errors in the android log?

**Comment by henninghall** [comment]
Btw, `androidMode` is not a valid prop. I don't think that's the cause of this problem though.

**Comment by henninghall** [comment]
@tapz since you're using `androidMode` i suspect you're using [react-native-datepicker](https://github.com/xgfe/react-native-datepicker) which is a different package, is that right?

**Comment by tapz** [comment]
@henninghall No, that's not what I'm using. Probably just read the wrong documentation :-D

**Comment by henninghall** [comment]
Ah alright! Could you check if you get any error logs (logcat) when this happens? Would be very helpful 🙏

**Comment by tapz** [comment]
I don't myself have the devices where this occurs, but I know the device codes:

Honor 6A (DLI-L22) Android 7
Honor 8 (FRD-L09) Android 7
Honor 9 (STF-L09) Android 9

I only have this device where this does NOT occur:

Honor P8 Lite (PRA-LX1) Android 8

**Comment by tapz** [comment]
Now I got my hands on FRD-L09. The only error I see in the logcat is this:

`ReactEventEmitter: Unable to find event emitter for reactTag: 2131231232 - uiManagerType: 2`

**Comment by tapz** [comment]
I changed the phone language to English and now `onChange` is called. I tested with countries US, UK and Finland. Only US had the AM/PM selector, so it does not seem to be related to that. But when I select Finnish/Finland or Swedish/Sweden it does not get fired.

**Comment by henninghall** [comment]
Thanks for helping investigating this! Do you see any "non-error stacktraces" being printed in the logs? There are some places where errors gets caught and stack traces printed on the default log level.

**Comment by tapz** [comment]
I don't see any non-error logging or stack traces.

**Comment by henninghall** [comment]
Alright, now if you could put in some breakpoints in the code when running it on the Honor device I think we can find the root cause of this. If you run the app in debug mode from Android Studio and put some breakpoints in the file `WheelChangeListenerImpl.java`. Does the function gets called? How far does the function run? Just let me know if you have any problems debugging it.
