### ISSUE TITLE
Mode Not Working in Android

### ISSUE THREAD

**Issue by Harpalsinh-Jadav** [henninghall/react-native-date-picker#290]
whether I use mode={'date'} or mode={'time'} or mode={'datetime'} it is giving me DateTime out put of mode={'datetime'} in android.

```
import React, { Component } from 'react';
import DatePicker from '@henninghall/react-native-date-picker';


export default class MoveIn extends Component {
    state = { date: new Date() }
    render() {
        return (
            <DatePicker
                date={this.state.date}
                onDateChange={date => this.setState({ date })}
                mode={'date'}
                style={{ height: 300, width: 300 }}
            />
        );
    }
}
```

I get this code from [https://github.com/henninghall/react-native-date-picker/blob/master/examples/detox/src/examples/DateMode.js](url)

My react-native version --> 0.63.4
API Version = 30,
Android Emulator = Pixel_3a_API_30_x86(AVD)
Output = 
![new issue](https://user-images.githubusercontent.com/40863598/105371844-06a8b180-5c2b-11eb-8ac8-08512acc2489.png)

**Comment by henninghall** [comment]
Hi @Harpalsinh-Jadav, thanks for reporting this. 

Do you get any errors in the android log?

**Comment by Harpalsinh-Jadav** [comment]
> Hi @Harpalsinh-Jadav, thanks for reporting this.
> 
> Do you get any errors in the android log?

Not specific but getting this at starting time ->

 Warning: DatePickerIOS has been merged with DatePickerAndroid and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'. See https://github.com/react-native-community/datetimepicker

**Comment by henninghall** [comment]
Allright, which emulator/phone model are you using?

**Comment by henninghall** [comment]
@Harpalsinh-Jadav now I realize what the problem is, you're using `'@henninghall/react-native-date-picker'` which is a very old outdated version of this package. Uninstall that package and install `react-native-date-picker` instead and you'll be fine!
