### ISSUE TITLE
Date format support : YYYY-MM-DD while opening picker.

### ISSUE THREAD

**Issue by pragyawebvillee** [henninghall/react-native-date-picker#293]
When the picker is opened, it opens date with DD MM YYYY format, I changed locale for this but the picker opens it in another language. 

**Expected behavior**
I want to open Picker in YYYY MM DD format

**To Reproduce**
<DatePicker
        locale=''
        format="YYYY-MM-DD"
        date={props.date}
        mode={'date'}
        maximumDate={props.date}
        onDateChange={changeDateValue}
      />

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version - 0.62.2
 - react-native-date-picker version - v2.7.12

**Comment by henninghall** [comment]
Specifying a different format in other ways than changing the locale is or will not be supported since thats how UIDatePicker works. Which country or countries are you trying to target?

**Comment by pragyawebvillee** [comment]
Targeting Countryies: India & Malaysia
