### ISSUE TITLE
Native component for RNDatePicker does not exist

### ISSUE THREAD

**Issue by issamabdelkrim** [henninghall/react-native-date-picker#30]
Hi, after installation steps, I get that error
![capture d ecran 2018-11-21 a 12 48 24 pm](https://user-images.githubusercontent.com/11806926/48839530-15198b00-ed8c-11e8-87ac-1001d91e1fed.png)

i didn't use expo

**Comment by henninghall** [comment]
Hi! Are you using Cocoapods?

**Comment by issamabdelkrim** [comment]
Yes

**Comment by henninghall** [comment]
I have managed to reproduce this, its definitely an issue when using CocoaPods. I will try to fix it, in the meantime you can manually link the project like this: [Manual Linking ](https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking) 

For everyone not using CocoaPods you can use `react-native link` as usual.

**Comment by JoschaP** [comment]
Same problem on ios with manual linking.

The DateManagerPicker could not be found

**Comment by henninghall** [comment]
I only manage to reproduce same error as @issamabdelkrim when the Podfile is setup incorrectly. For instance if react-native-date-picker is excluded. This could happen if you forget to use `react-native link` or `pod install`. With a [Podfile like this](https://github.com/henninghall/react-native-date-picker/blob/master/example-cocoapods/ios/Podfile) followed by a `pod install` it works perfectly fine for me. I added an [example project ](https://github.com/henninghall/react-native-date-picker/tree/master/example-cocoapods)using cocaopods with a[ step-by-step explanation](https://github.com/henninghall/react-native-date-picker/tree/master/example-cocoapods) of how I created it. 

@harshita-dhingra's error seems to be somthing completely different which I unfortunately don't manage to reproduce at all. Please provide an explaination of how to reproduce it if your problem persists. 

Also please provide your react-native version if the above doesn't help.

**Comment by RaiSaugat** [comment]
I am having the same problem as @harshita-dhingra in android. 

> "DatePickerManager" does not exist

Can you help me on this one?

**Comment by henninghall** [comment]
@RaiSaugat I will give it a try! What version of react-native and react-native-date-picker are you using?

**Comment by RaiSaugat** [comment]
"react-native": "0.51.0",
"react-native-date-picker": "^2.2.1"

**Comment by henninghall** [comment]
You can try upgrading react-native version if you have the possibility since it's 1 year old. https://facebook.github.io/react-native/docs/upgrading At some point I will investigate a bit around which versions that the package support.

**Comment by RaiSaugat** [comment]
The same version works on my colleague workspace. But not in mine.

**Comment by feetbo90** [comment]
I am having same problem, what should I do? 
"react-native": "^0.52.2",
"react-native-date-picker": "^2.2.1"

**Comment by henninghall** [comment]
@feetbo90 Is it the android or ios issue?

**Comment by henninghall** [comment]
I am pretty sure the original ios issue is related to the Podfile. See [my comment](https://github.com/henninghall/react-native-date-picker/issues/30#issuecomment-442602146) of how to solve it. 

The Android issue mentioned in this thread is unrelated to the ios one why I consider it is best to open a separate issue for that one. If anyone still having that issue, please open an issue with a description of how to reproduce it. I am unable to reproduce myself. Also please mention your React Native and react-native-date-picker version. Appriciate your help.

**Comment by ofito** [comment]
I Have the same problem without Cocoapods. My version :
react-native: 0.55.2,
react-native-date-picker: 2.2.1

Sometimes react native link doesn't work correctly, it would be good a manual installation info.

Anyway, great job!.

**Comment by henninghall** [comment]
@ofito Great idea, should definitely add that. Did you solve it by manual installation?

**Comment by azhararmar** [comment]
I had the same issue, In my case react-native link did not work. solved it by manual installation. Here is how I did it.

1. Open project.xcworkspace
2. In the "Project Navigator > Libraries" right click and "Add files to ..."
3. Select RNDatePicker.xcodeproj from "node_modules/react-native-date-picker/ios"
4. Go to "Targets > Project Name > Linked Framework & Libraries" and select "+"
5. Select "libRNDatePicker.a" from the list (search for it) and click "add"
6. Re run react native project.

**Comment by airman00** [comment]
On Android in your MainApplication.java, you may need to also add the DatePicker Package
```

    @NonNull
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        // Add the packages you require here.
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
              ... other packages
          new DatePickerPackage()
        );
    }
```
