### ISSUE TITLE
AM PM 🐛 

### ISSUE THREAD

**Issue by NexflareGI** [henninghall/react-native-date-picker#300]
**Bug**
Suppose the date prop of the library uses any time greater than 6pm and less than 11pm. As soon as I change the value of date prop to any other date with time 12 am the library first goes to am (as expected) and then automatically comes back to pm.

**Comment by daniel-zarachowicz** [comment]
it would be great to set pm am mode as stand alone property which is not depending on locale

**Comment by henninghall** [comment]
@NexflareGI I don't manage to reproduce this, could you give a code sample that I can run?
