### ISSUE TITLE
react-native 0.63.4 Cannot read property 'toISOString' of undefined android and ios

### ISSUE THREAD

**Issue by daniel-zarachowicz** [henninghall/react-native-date-picker#308]
**Describe the bug**
Property 'date' of the component is not mandatory at current state. 
When undefined passed as value into it this errors will come up:

iOS: The prop `date` is marked as required in `DatePickerIOS`, but its value is `undefined`
Android: Cannot read property 'toISOString' of undefined

**Expected behavior**
No errors when passing undefined value.
For example, when completing form for a first time, value could be not known. 

**To Reproduce**
Pass undefined value into date property.

```javascript

 <DatePicker
          date={undefined}
          mode={mode}
          onDateChange={handleConfirm}
        />

**Smartphone (Emulator Android 10,  Emulator iOS 12 ):**
 - OS: [Android and iOS]
 - React Native version [0.63.4]
 - react-native-date-picker version [3.2.10]

**Comment by daniel-zarachowicz** [comment]
Quick and dirty fix is to pass dummy Date value fe. new Date('2021-03-23T00:00:00') into useState:
 const [date, setDate] = useState<Date | undefined>(value ? value : new Date());

**Comment by henninghall** [comment]
Hi, you have to supply an initial value. The picker needs to know what to display as default. 

If you want to track if the user has selected a value or not I would suggest keeping that as an additional state. Either as a boolean or another Date.
