### ISSUE TITLE
Unable to pick a date earlier than 6 months ago on Android

### ISSUE THREAD

**Issue by oowletFalquinho** [henninghall/react-native-date-picker#316]
**Describe the bug**
Unable to pick a date earlier than 6 months ago on Android.
On iOS it works as expected.

**Expected behavior**
User should be able to scroll back to whatever year he/she wants.

**To Reproduce**
My code:

```javascript
{datePickerVisible && (
    <DatePicker
    maximumDate={new Date()}
    mode='date'
    date={eventToCreate.timestamp ? new Date(eventToCreate.timestamp) : new Date()}
    onDateChange={(date) => this.handleDateChange(date)}
    textColor={colors.black}
    style={{ alignSelf: 'center' }}
    />
)}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.63.0
 - react-native-date-picker version 3.2.10
 
![photo4906884017400424622](https://user-images.githubusercontent.com/80268936/115889511-63825680-a42a-11eb-9a83-98ceb3f9c647.jpg)
![photo4906884017400424623](https://user-images.githubusercontent.com/80268936/115889513-641aed00-a42a-11eb-879b-82b8ab544c5e.jpg)

**Comment by henninghall** [comment]
You can set the minimumDate and maximumDate props to support this. But you should be aware of that it bad ux to let the users scroll that long and you probably want to use the date mode for those situations.

**Comment by oowletFalquinho** [comment]
I've tried setting a explicit minimumDate and it didn't solve it.
The mode is 'date'.
Regarding the UX yeah, I would agree, but my need now is to support what is there, not rework.
So from your answer can I say that this is the expected behaviour?
