### ISSUE TITLE
Wheels not showing on iOS 14 (Xcode 12).

### ISSUE THREAD

**Issue by konstantin-k13** [henninghall/react-native-date-picker#317]
**Describe the bug**
I'm running into the issue where time picker looks different on iOS 14.4 with Xcode 12.4. It is quite urgent since we need to release an update but we can't do it with the new version of Xcode, and Apple rejects builds made with Xcode 11 now.

Do you know what may be causing this issue? I even tried switching packages to @react-native-community/datetimepicker, but it didn't help as well - same problem.

I tried downgrading to v3.0.3 (since it's the version this issue reportedly has been resolved in - see https://github.com/henninghall/react-native-date-picker/pull/217/files), but no luck.
I also tried deleting the DerivedData and all cache files, but, again, didn't help.
Please help.

![image](https://user-images.githubusercontent.com/47841503/116052801-ccbcd080-a69b-11eb-8b21-79eb9e53515f.png)
![image](https://user-images.githubusercontent.com/47841503/116052826-d47c7500-a69b-11eb-93fd-26b98aaf7039.png)

**Expected behavior**
I should be able to see the time picker as wheels. Like on the screenshot below
![image](https://user-images.githubusercontent.com/47841503/116054168-3be6f480-a69d-11eb-9492-e80ce8e5ef65.png)

**To Reproduce**
```javascript
export default class App extends Component {
  constructor(props) {
      super(props);

      this.state = {
          Time: this.props.selectedTime
      }
  }

  render = () => {
    const {
        selectedTime,
        onChangeTime = () => { }
    } = this.props;

    return (
        <DatePicker
            mode="time"
            date={selectedTime}
            minuteInterval={15}
            onDateChange={(time) => {
                this.setState({
                    Time: time
                }, () => onChangeTime(time))
            }}
        />
    );

}
```

**Smartphone (please complete the following information):**
 - OS: iOS 14.4 (Simulator)
 - React Native version 0.61.2
 - react-native-date-picker version 3.2.10

Update: DatePicker with mode="date" looks okay, the issue only reproduces with mode="time".

**Comment by konstantin-k13** [comment]
@henninghall Any thoughts? I really need to push the build to production ASAP

**Comment by ekim-novus** [comment]
I'm having the same issue :(
