### ISSUE TITLE
Get current time at time mode

### ISSUE THREAD

**Issue by vaiosyndicates** [henninghall/react-native-date-picker#322]
Is it possible to get current time and set the state or maybe fire onChangeDate props?
Because i just can set state only when i scroll the timepicker

**Comment by vaiosyndicates** [comment]
so basically, i want to get current value of the time picker
for now, in this library there is no option / props to get current value right?
if i want to implement my case, is it possible to get current value of the time picker, without changing / scrolling the time picker?

**Comment by henninghall** [comment]
Alright, no you would need to keep track of the current value in a state yourself. You can then read the state which will always contain the current value as long as you update it on every change. As seen in this example https://github.com/henninghall/react-native-date-picker#minimal-example
