### ISSUE TITLE
DatePicker inside Horizontal scrollview crash on Android

### ISSUE THREAD

**Issue by dungnguyentri3110** [henninghall/react-native-date-picker#329]
Hi guys.
I have problem with my component. I wrap my date Picker inside Scrollview Horizontal. Then i show it up and i scroll datepicker to choose my date, it work well on IOS but on android it crash immediately when id. i Dont know why. Help me. Thanks you

**Comment by henninghall** [comment]
Hi, could you provide the stack trace and/or a reproducible sample?

**Comment by henninghall** [comment]
Hard to say without a stack trace but if it is the same crash as [this](https://github.com/henninghall/react-native-date-picker/issues/301) it has been **resolved in react native 0.64.2**. Please try that and let me know if it doesn't solve the issue and we can reopen this.
