### ISSUE TITLE
Is there any way to change date order ?

### ISSUE THREAD

**Issue by dineshucreate** [henninghall/react-native-date-picker#33]
**I am looking to change Date order in Android** 

```
Right now it's something like Month - Day - Year
It should be like   Day - Month - Year
```

> As per documentation: The locale for the date picker. Changes language, date order and am/pm preferences. 
It seems I can change date order but not able to do

Thanks

**Comment by henninghall** [comment]
Hi! Yes the order is determined by the locale  so it could be changed by adding/changing the locale property. Does that work for you?

If you already set the locale property to the desired but received unexpected order, please provide your locale and I will have a look.
