### ISSUE TITLE
when I add textColor props it doesnt automatically changes with scrolling dates  in android with nativeAndroid variant

### ISSUE THREAD

**Issue by Rameesh-sanesquare** [henninghall/react-native-date-picker#333]

**Comment by azharkiz** [comment]
same issue i am also facing

**Comment by cihancil** [comment]
Same here. 

Also color doesn't applied to all characters.

**Comment by auliakbarh** [comment]
same issue

**Comment by henninghall** [comment]
Hi, what do you mean by "it doesn't automatically changes with scrolling dates"? Can you add screenshots/screencap of the problem? 

@cihancil I don't manage to reproduce the problem with missing colors on some characters. Could you give a code example? What language are you using?

**Comment by sutefan1** [comment]
hey @henninghall,

I think I'm running into the same issue:

`RN Code:`
```
<DatePicker
    androidVariant="nativeAndroid"
    mode={'date'}
    date={new Date(date.toISOString())}
    onDateChange={(newDate) => {
      setDate(moment(newDate));
    }}
    textColor={Platform.OS === 'ios' ? COLORS.WHITE : undefined}
    fadeToColor={'none'}
/>
 ```
 `styles.xml:`
 ```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorControlNormal">@color/white</item>
    </style>
</resources>
 
```
 # Expected output:
 Native android spinner with WHITE divider and WHITE selected text color which fade from WHITE to somewhere grey or whatever. 
 
 # Actual output:
 Native android spinner with WHITE divider and WHITE selected text color but BLACK non selected text color/fade color.
 
![photo_2021-06-15 18 20 50](https://user-images.githubusercontent.com/11005451/122088841-71d76800-ce06-11eb-9e02-f78c3ef2c1ad.jpeg)

**NOTE:**
 Once you start scrolling the black text gets selected but not even updated to the `selectedTextColor`.
 
 # RN Info
 ```
 System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 116.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 16, 21, 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    react-native: 0.61.5
 ```
 
 # Version 3.2.10

**Comment by tomLadder** [comment]
having issue described by @sutefan1 😢

**Comment by sutefan1** [comment]
@henninghall Is this module still maintained on a regular basis? I'm just asking as we plan on using it (`nativeAndroid`)  in the next release and therefore don't want to wait anymore with the publish but switch back to the `iOSClone`. (It's open-source, I absolutely understand if there might not be time atm for it or whatever)

Looking forward to any response.

**Comment by aangindra** [comment]
having same issue

**Comment by efstathiosntonas** [comment]
same here but on iOS, the current date is Black instead of the white i've given to `textColor`, eg today is 30 Jul, the July and 30 is black, all other months/days have the correct color.

**Comment by henninghall** [comment]
I've tried but I don't manage to reproduce this issue on either Android or iOS. If anyone could supply a fully runnable sample, a full component or repo where this happens, that would be very helpful in figuring this out.

**Comment by henninghall** [comment]
@sutefan1 yes it is actively maintained

**Comment by sutefan1** [comment]
@henninghall Have a look at https://github.com/sutefan1/react-native-datepicker-sample 

Clean RN project with dark background and therefore the intention of bright textColor. Let me know if you need further infos.

**Comment by henninghall** [comment]
Thanks @sutefan1! I could reproduce and fix the android issue. Released in `v3.4.1`

@efstathiosntonas or others, if you still have a similar issue on iOS, it would be great if you could open another issue and explain how to reproduce it there too.

**Comment by efstathiosntonas** [comment]
@henninghall thanks for the fix, what I’ve done in the end is to use white on dark theme of my app and black on light theme.

`textColor` with any other color value won’t work. The today’s day will always be different color than all the other days/months witch are correctly “colored” by `textColor`.

**Comment by henninghall** [comment]
Yes I am aware that we cannot color the "Today" string to something else than black or white. It is actually also mentioned in the Readme. As a workaround, the date picker is supposed to show the actual date instead of the "Today" string when chosen another color. But obviously this didn't work for on your device. You don't happen to remember which iOS version and device you were running?

**Comment by efstathiosntonas** [comment]
iPhone 11 emulator with 14.5 and iPhone XS real device with 14.7.1 

i ll create a repo tomorrow for reproduction and i ll post the link here. (Or create a new issue since this is closed and related to android)
