### ISSUE TITLE
When Android system language is RTL, the time picker is reversed incorrectly

### ISSUE THREAD

**Issue by guytepper** [henninghall/react-native-date-picker#339]
<img src="https://user-images.githubusercontent.com/13344923/121677901-2e57c380-cabf-11eb-96a1-4444997252d2.jpg" alt="IMAGE 2021-06-11 14:13:12" width="325" align="right">When the Android system language is RTL, the time picker is showing up incorrectly: the hours are on the right column and the minutes on the left. 
The time picker should be the same as the LTR mode, and not reversed.

Btw, providing a different `locale` won't affect this - as long as the system language is RTL, the time picker will still be reversed.

**System Info:**
 - OS: Android 9
 - React Native version [e.g. 0.63.4]
 - react-native-date-picker version: 3.3.1

**Comment by henninghall** [comment]
Released a fix for this in version `3.4.0`
