### ISSUE TITLE
How can i set height and width for picker ?

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [henninghall/react-native-date-picker#34]
I should set height and width to picker how can i do it?

I tried putting inside to View and giving propertie style and they didn't worked.

Its getting smaller when i set width, height smaller than
{
        width: 310,
        height: 180,
}
but its wont growth when set bigger then this parameters.

I'am trying this with android.
react-native: v 0.57.7
react-native-date-picker: v 2.2.1

Thanks in advance

**Comment by henninghall** [comment]
Hi, thanks for reporting this! Custom width and height is unfortunately not supported yet. Currently it uses the default size of DatePickerIOS which is 310/180. I will have a look at it, but I'm not sure when I'll be able to implement it. Meanwhile, try to make a fork and change your desired measures.

**Comment by Blutude** [comment]
Also an issue for me! I'm trying to fit it inside a modal. I was previously using DatePickerIOS and it fit perfectly but now the AM and PM part is getting cut.

**Comment by Blutude** [comment]
Actually, I had to wrap the datepicker in a view and set the style of the view to alignItems: 'center'. The size turned out to be fine, it just wasn't centered. (My datepicker is inside a modal and I didn't have to wrap the DatePickerIOS in a view). I guess DatePickerIOS is centered by default.

**Comment by azhararmar** [comment]
@Blutude datepicker inside the view with alignItems: 'center' indeed work.

**Comment by PhuongNguyenETIT** [comment]
Can change the width, height in Android?

**Comment by fedu44** [comment]
Henninghall, is there a way I can help you with the development of this datepicker?

**Comment by henninghall** [comment]
@fedu44 Yes PR's are always appreciated! If you would like to work on this feature you might get some help from [this branch](https://github.com/henninghall/react-native-date-picker/tree/custom-width-height ) where I have started the work of customizable width and height.

**Comment by henninghall** [comment]
Basic functionality is done but some finishing fixes are needed before release.

**Comment by henninghall** [comment]
Released in v2.5.0

**Comment by DarshanNDK** [comment]
yo, did you update the readme file as well, for custom height and width?
i.e, How do I use it? XD

**Comment by quanle1996** [comment]
@henninghall 
Hi, can you show me how to custom the height or width? thanks.

**Comment by samducker** [comment]
Hi @henninghall could you confirm if changing the width on android is not possible at the current time? 

Works fine on iOS cannot seem to get it to be any bigger than this on android.

![Screenshot_20240828-001908](https://github.com/user-attachments/assets/ce0be9dd-0488-459c-82d3-8fd0e3419de2)

My code

```
import { useWindowDimensions} from 'react-native';
  const { width: screenWidth } = useWindowDimensions();

 <DatePicker
                date={value}
                onDateChange={onChange}
                mode="date"
                maximumDate={new Date()}
                style={[
                  styles.datePicker,
                  Platform.OS === 'ios' ? { width: screenWidth - 32 } : { width: screenWidth },
                ]}
                dividerColor={theme.colors.surface['300']}
              />
```
