### ISSUE TITLE
Kicks it out of the application. (Android) 

### ISSUE THREAD

**Issue by bekirytm** [henninghall/react-native-date-picker#345]
<DatePicker
        style={{
          width: width * 0.9,
          height: height * 0.3,
        }}
        date={date}
        onDateChange={(val) => {
          setDate(val);
        }}
        textColor={'#39B1A7'}
        fadeToColor={'#fff'}
        maximumDate={new Date()}
        minimumDate={new Date('1950-01-01')}
        mode={'date'}
        locale={'tr'}
        is24hourSource="locale"
      />

I'm using version 3.3.0 and it throws it out of the app while scrolling.

**Comment by sutefan1** [comment]
@bekirytm Please use `` for code formatting. 
This seems more like a question for StackOverflow. Ask your question there WITH an error log in order to get help.

**Comment by bekirytm** [comment]
hi, i am not getting any error log. If I had an error, I would add it here, but it closes the application without giving an error log.

**Comment by sutefan1** [comment]
@bekirytm Have you also checked the `logcat` from Android Studio? You can filter the logs by processes and further by text search. There you should for sure find some reason why the app gets killed.

**Comment by bekirytm** [comment]
@sutefan1 I hadn't tried this. I'll try and post the error log I got here. thank you.

**Comment by henninghall** [comment]
It could be this issue: https://github.com/henninghall/react-native-date-picker/issues/301 
Which version of react native are you using? If 0.64 you need to be using 0.64.2 or above.

**Comment by bekirytm** [comment]
@henninghall  I am currently using version 0.64.2.

**Comment by Saad-Bashar** [comment]
same problem, JSI Module crash in 0.64.2 :(

**Comment by Saad-Bashar** [comment]
Okay seems like this occurs within a horizontal scroll view. I tried putting it in a normal view and it works okay. Any solution on that? @henninghall

**Comment by seamive** [comment]
@bekirytm: Make sure you're on `react 17.0.1 and react-native 0.64.2`.
Also, make sure you have implemented the `proguard rules` just in case since there are major changes to the UIManager.

**Comment by henninghall** [comment]
@bekirytm if this still is an issue, please provide stacktrace/error log and we can look into this
