### ISSUE TITLE
Year Day Month format

### ISSUE THREAD

**Issue by vinay-sayone** [henninghall/react-native-date-picker#346]
**Describe the bug**
How to display the date wheel in Year Day Month format under locale="en"?

**Expected behavior**
It should display the date wheel.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

   state = {
    defaultDateTime: new Date(moment().subtract(18, 'y')),
  };

  render = () =>
    <DatePicker
      date={this.state.defaultDateTime}
      onDateChange={this.dateChangeHandler}
      mode="date"
      style={styles.datePicker}
      textColor={AppStyles.colors.COLOR_PICTON_BLUE}
      fadeToColor={'none'}
      dividerHeight={5}
      maximumDate={new Date(moment().subtract(18, 'y'))}
      locale="en-US"
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [0.63.4]
 - react-native-date-picker version [3.3.1]

**Comment by henninghall** [comment]
I would recommend trying to remove one prop after another to track down where the problem is.

Also, could you please provide a fully runnable example and the stack trace? or I won't be able to reproduce this.

**Comment by henninghall** [comment]
I am not aware of any English-speaking country using Year Day Month so this is probably not possible. Just curious, what is your use case for this?
