### ISSUE TITLE
How to change the font size of the dates ?

### ISSUE THREAD

**Issue by Lilsax** [henninghall/react-native-date-picker#350]
im just trying to change the font size thanks

**Comment by mehdinasiripoor** [comment]
same here!!!!!

**Comment by LozytskyiA** [comment]
+

**Comment by henninghall** [comment]
See this discussion https://github.com/henninghall/react-native-date-picker/discussions/171

**Comment by henninghall** [comment]
I meant the scaling method mentioned there

**Comment by LozytskyiA** [comment]
> I meant the scaling method mentioned there

But I need to change the font size and font family.
Is it even possible ?)

**Comment by henninghall** [comment]
Not by a prop, you can probably use a transform and/or probably modify the native code to get it to look like you want. PR's are welcome!
