### ISSUE TITLE
Android Cannot read property 'toISOString' of undefined

### ISSUE THREAD

**Issue by thienphuit** [henninghall/react-native-date-picker#352]
TypeError: Cannot read property 'toISOString' of undefined

This error is located at:
    in DatePickerAndroid (at src/index.js:22)

export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android 
 - React Native version [e.g. 64.2]
 - react-native-date-picker version [e.g. 3.3.2]

**Comment by mengmengmeng01** [comment]
遇到同样的问题，请问有没有解决

**Comment by mohgawaad** [comment]
![Screen Shot 2021-08-04 at 6 33 06 PM](https://user-images.githubusercontent.com/39673388/128231898-115fa690-971a-40cb-84ad-295306c092a6.png)

This issue also appeared to me

**Comment by dkunin9** [comment]
any idea?

**Comment by henninghall** [comment]
Can you provide a minimal code sample where this happens?

**Comment by utae** [comment]
date props is required for Android (can't be undefined or null)
