### ISSUE TITLE
Library ui is broken on react-native version 0.64

### ISSUE THREAD

**Issue by Babazon** [henninghall/react-native-date-picker#353]
**Describe the bug**
The library does not display an inline picker, the wheel is always on, un-styled, without input accessories or backdrop.

<img width="430" alt="Screenshot 2021-07-06 at 08 09 46" src="https://user-images.githubusercontent.com/9430138/124559353-e9177f00-de3b-11eb-9d08-54f7dc5bf0bf.png">

<img width="427" alt="Screenshot 2021-07-06 at 07 19 42" src="https://user-images.githubusercontent.com/9430138/124543942-7c45ba00-de26-11eb-978d-6f462a6e997b.png">

**Expected behaviour**
Library should pop up picker on click of an  inline text element, display input accessories and backdrop.

**To Reproduce**
Add example code that reproduces the behaviour. 
```javascript
// use react-native 0.64.x
// ios 14.5

<DatePicker
          minuteInterval={10}
          mode="datetime"
          date={date}
          onDateChange={setDate}
        />
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS] IOS
 - React Native version [e.g. 0.59.4] 0.64.0
 - react-native-date-picker version [e.g. 2.5.1] 3.3.2

**Comment by henninghall** [comment]
This is the expected behavior
