### ISSUE TITLE
While JCenter is shutting down, builds will be failed if I remove jcenter() from build.gradle 去掉jcenter() build出错。

### ISSUE THREAD

**Issue by dubiao** [henninghall/react-native-date-picker#354]
**Describe the bug**
If I remove jcenter() from my build.gradle build failed
从build.gradle里删除了jcenter()时，build就出错

**Expected behavior**
As jcenter is no longer the best way (as it is shutting down) to host libs, most projects are removing jcenter() from build.gradle. Libs should be hosted by mavenCenter or jit.io. And builds success. Thanks
在JCenter已经要走向关闭的情况下（虽然现在是可读），很多项目都把jcenter()从build里移除，以便收到最新版本的库。麻烦使项目可以在 mavenCenter或jit.io上可以拉到。谢谢。

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.64.0
 - react-native-date-picker version [any]

**Comment by henninghall** [comment]
Jcenter has no plans to shut down at the moment, it will be kept as readonly so there is no problem with keeping jcenter right now. 

https://github.com/henninghall/react-native-date-picker/issues/310
