### ISSUE TITLE
TypeError: props.date.getTime is not a function. (In 'props.date.getTime()', 'props.date.getTime' is undefined)

### ISSUE THREAD

**Issue by thechaudharysab** [henninghall/react-native-date-picker#356]
**Describe the bug**
Getting this error:

> TypeError: props.date.getTime is not a function. (In 'props.date.getTime()', 'props.date.getTime' is undefined)

**Expected behavior**
It should show the date picker.

**To Reproduce**
This is the required code:

```
...
    const [userUserDOB, setUserDOB] = useState(new Date());
...
                        <DatePicker
                            style={styles.dobPicker}
                            date={userUserDOB}
                            onDateChange={setUserDOB}
                            mode={'date'}
                            textColor={colors.darkBlue}
                        />
...

    dobPicker: {
        alignSelf: 'center'
    },

```

**Smartphone:**
 - OS: iOS
 - React Native version: 0.63.4
 - react-native-cli: 2.0.1
 - react-native-date-picker version: ^3.2.10

**Comment by HammzaHM** [comment]
I have faced the same issue... the problem is you should a javascript Date Instance the best way to fix this by wrap your date prop value with `new Date()` like so: 
`<DatePicker
                            style={styles.dobPicker}
                            date={new Date(userUserDOB)}
                            onDateChange={setUserDOB}
                            mode={'date'}
                            textColor={colors.darkBlue}
                        />`

**Comment by henninghall** [comment]
`onDateChange` should always return a Date instance so this should never happen. Are you sure you're not modifying userUserDOB at some point? If not, please provide a fully runnable sample where this happens and I will look into this. I could not reproduce it with the sample above. 

Also, it would be useful if you can provide an example of what the value userUserDOB is when this error happens.
