### ISSUE TITLE
picker time day ahead..

### ISSUE THREAD

**Issue by DwsCode88** [henninghall/react-native-date-picker#358]
![Screenshot_1626920770](https://user-images.githubusercontent.com/42653240/126582357-2c698c1f-e740-418b-8654-2455578de52c.png)
I'm using the example shown and have it console. Warn and it shows the next day for todays date..

Like right now it shows for today as 7/22

`   <DatePicker date={date} onDateChange={setDate} />`

**Comment by henninghall** [comment]
Looks like you're logging the date in utc format while the datepicker are using the device's timezone. Could that be it?

**Comment by DwsCode88** [comment]
How do I fix that?

**Comment by henninghall** [comment]
It is nothing to fix, it works as intended. You can store the date in utc format and if you want to display it you can format it to local timezone. Google for "format Javascript date" if you need more info.
