### ISSUE TITLE
iOS is24hourSource is ignored if locale is set

### ISSUE THREAD

**Issue by systemride** [henninghall/react-native-date-picker#359]
I have my device set to use 24 hour time. The time picker still shows AM/PM in the picker.

Eg:
```
<DatePicker
    date={new Date(this.props.time)}
    is24hourSource={"device"}
->  locale={"en-US"}
    mode={"time"}
    onDateChange={this.props.onTimeChange}
    textColor={this.props.textColor}
  />
```

I would expect it to still render 24 hour time with `is24hourSource={"device"}` being set.

**Comment by henninghall** [comment]
It's an "android only" prop

**Comment by marlti7** [comment]
but i want it work on ios

**Comment by marlti7** [comment]
> but i want it work on ios

i found locale set with _GB is work
