### ISSUE TITLE
3.4.1 does not compile

### ISSUE THREAD

**Issue by tapz** [henninghall/react-native-date-picker#368]
**Describe the bug**

Does not compile:

```
> Task :react-native-date-picker:compileReleaseJavaWithJavac FAILED

node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/pickers/
AndroidNative.java:56: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {

symbol:   variable Q
location: class VERSION_CODES

node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/pickers/
AndroidNative.java:57: error: incompatible types: int cannot be converted to String
            setTextColor(color);

compileSdk = 30
buildTools = "30.0.2"
minSdk = 22
targetSdk = 30
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.65.1
 - react-native-date-picker version 3.4.1

**Comment by aje** [comment]
Same issue here

**Comment by henninghall** [comment]
Try 3.4.2, should fix it for you

**Comment by tapz** [comment]
@henninghall I tried clearing all and rebuilding. Did not help.

**Comment by henninghall** [comment]
What error message do you get?

**Comment by tapz** [comment]
I only get one error, which is:

```
/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java:57: error: incompatible types: int cannot be converted to String
            setTextColor(color);

```

**Comment by henninghall** [comment]
Thanks! Then I understand, I initially thought you meant it still was the `Build.VERSION_CODES.Q)` error. I'll look into it!

**Comment by henninghall** [comment]
Which value has your `textColor` prop?

**Comment by tapz** [comment]
'#333333'

**Comment by henninghall** [comment]
I've tried with #333333 with difference devices, sdk versions and different props but I can't reproduce it. Do you mind putting up a RN project on github where this can be reproduced? Or explain how I can reproduce it in a fresh react native project? Would be helpful, thanks.

**Comment by MujtabaFR** [comment]
I have the same issue using 3.4.3
```
error: incompatible types: int cannot be converted to String
            setTextColor(color);
```
I had to downgrade to 3.4.0 to fix it

**Comment by henninghall** [comment]
Haven't still been able to reproduce it but I might have found the solution, please try v4.0.0 and let me know if it solved it for you

**Comment by MujtabaFR** [comment]
Still same error with v4.0.0
Going back to v3.4.3 🚶🚶🚶

**Comment by tapz** [comment]
Works for me.

**Comment by henninghall** [comment]
@MujtabaFR you did remember to rebuild after install right?

**Comment by carlezzo** [comment]
react-native 0.61.5 
picker 4.2.0 
Android only builds when comment the line // super.setTextColor(color);

<img width="794" alt="Screen Shot 2022-03-31 at 18 49 51" src="https://user-images.githubusercontent.com/11723151/161109149-b9c5a664-b4f6-4335-8944-bd018b2da2ef.png">

**Comment by shaishandil** [comment]
I just inherited a codebase where this is an ongoing issue. Does anyone know of a solution?
