### ISSUE TITLE
App crashes in android release build when date is undefined

### ISSUE THREAD

**Issue by Palmaaa** [henninghall/react-native-date-picker#374]
**Describe the bug**
`date` prop is typed as `Date | undefined`, however when passing an undefined value, it makes the app crash (only in android release build).

**Expected behavior**
Accept an undefined value in date props without crashing or correct date prop type

**To Reproduce**
```javascript
<DatePicker
    date={currentDate} //undefined
    mode="date"
    onDateChange={handleOnChange}
/>
```
**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.63.4
 - react-native-date-picker version 3.4.3

**Comment by skuzyuk** [comment]
I also ran into an application crash problem: on some screens the date picker works flawlessly, and the same component crashes on some screens

**Comment by henninghall** [comment]
@Palmaaa thanks, the date prop is supposed to be required. A fix will be included in the next release.

@skuzyuk please create a new issue for that and include the stack trace, and I'll have a look
