### ISSUE TITLE
When I scroll the months to set it return back to first

### ISSUE THREAD

**Issue by adilijaz** [henninghall/react-native-date-picker#379]
**Describe the bug**
I'm using this library to select a date but when my month scroller is not working properly e.g Starting month is September when I scroll down and go to February it returns automatically to September again. But when I do the same stuff in this way (select year first, then date then month) works properly.

**Expected behavior**
month should be selected after scroll

```javascript
  <DatePicker
          date={date}
          onDateChange={setDate}
          mode={'date'}
          androidVariant={'nativeAndroid'}
          minimumDate={moment().subtract(50,'years')}
          maximumDate={moment().subtract(18,'years')}
        />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version : 0.64.2
 - react-native-date-picker version : ^3.3.2

**Comment by BaderSerhan** [comment]
@adilijaz It happens when we have a max date / min date set up.
I am facing this issue as well, how have you managed to fix it?
Is there a way to put years first for example?
