### ISSUE TITLE
crash the application when you swipe in the datePiker component on some screens

### ISSUE THREAD

**Issue by skuzyuk** [henninghall/react-native-date-picker#385]
**Describe the bug**
on some screens, the application crashes when drinking, change the date (wake up), while there is no error in the console
**Expected behavior**
expect performance on all screens

**To Reproduce**

```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version : [0.64.0]
 - react-native-date-picker version [3.4.3]

**Comment by henninghall** [comment]
Update your RN version to 0.64.2 or later
