### ISSUE TITLE
Setting of Minimum and Maximum time not available

### ISSUE THREAD

**Issue by Venkatesh-kumar** [henninghall/react-native-date-picker#387]
Hello,

Setting of min and max date is available. It would be really helpful for lot of developers to set min and max time also.

**Comment by dev-hsn** [comment]
> Hello,
> 
> Setting of min and max date is available. It would be really helpful for lot of developers to set min and max time also.

I have the same issue, did you found a solution?

**Comment by henninghall** [comment]
It is already possible, use the `minimumDate` or `maximumDate` prop with a Date object set to a specific time.
