### ISSUE TITLE
Is there any way to change the gap between year and month and day?

### ISSUE THREAD

**Issue by wangxueke** [henninghall/react-native-date-picker#39]
I think it is too narrow to me. Help
![gap](https://user-images.githubusercontent.com/26314706/54346634-6376d080-4680-11e9-8484-0fe4dea31230.png)

**Comment by henninghall** [comment]
Hi! I believe there is no way to do this at the moment. It might be possible to fix by creating a fork and manually setting a fixed width of the native component. 

To be able to customize the size of the component is next up on my to do list and might solve this issue. I will hopefully be able to fix it within 2-3 weeks. Feel free to make a PR if you solve this in a general way.

**Comment by wangxueke** [comment]
ok，thank you very much~. I am waiting for you! haha.

> Hi! I believe there is no way to do this at the moment. It might be possible to fix by creating a fork and manually setting a fixed width of the native component.
> 
> To be able to customize the size of the component is next up on my to do list and might solve this issue. I will hopefully be able to fix it within 2-3 weeks. Feel free to make a PR if you solve this in a general way.
