### ISSUE TITLE
When a used two picker in same screen, one change another

### ISSUE THREAD

**Issue by gustavohcastro** [henninghall/react-native-date-picker#394]
<View style={{flexDirection:'row', justifyContent:'space-between', marginTop:16}}>
                    <Button variant='outlined' style={{width:'48%'}} onPress={() => {
                      setOpenStart(true)
                    }}>
                        <Typography>{startDate.toLocaleDateString()}</Typography>
                    </Button>
                    <Button variant='outlined' style={{width:'48%'}} onPress={() => {
                         setOpenEnd(true)
                    }}>
                        <Typography>{endDate.toLocaleDateString()}</Typography>
                    </Button>
                </View>
                <DatePicker
                    modal
                    confirmText="Confirmar"
                    cancelText='Cancelar'
                    title="Selecione uma data"
                    mode='date'
                    open={openStart}
                    date={startDate}
                    onConfirm={(date) => {
                        setOpenStart(false)
                        setStartDate(date)
                    }}
                    onCancel={() => {
                        setOpenStart(false)
                    }}
                />
                <DatePicker
                    modal
                    confirmText="Confirmar"
                    cancelText='Cancelar'
                    title="Selecione uma data"
                    mode='date'
                    open={openEnd}
                    date={endDate}
                    onConfirm={(data) => {
                        setOpenEnd(false)
                        setEndDate(data)
                    }}
                    onCancel={() => {
                        setOpenEnd(false)
                    }}
                />

**Comment by NavidHosseini** [comment]
same issue

**Comment by dsipahioglu** [comment]
I also have this issue on Android. Though it works fine on ios

**Comment by bartoszboruta** [comment]
Same issue here

**Comment by dsipahioglu** [comment]
I found a workaround by updating the date states by checking which modal is active. I also had to close both modals on the onClose method, because opening a modal also opens the other one. I hope this helps someone
 In onDate changed: 
 if (this.state.beginDateModalOpen) {
        this.setState({ beginDate: date, maskedBeginDate: newDate, beginDateModalOpen: false });
}

I used the date picker inside another component but these are my props.

<NativeDatePicker
                        date={this.state.beginDate}
                        value={this.state.maskedBeginDate}
                        onDateChange={this.onDateChanged}
                        open={this.state.beginDateModalOpen}
                        onConfirm={this.onDateChanged}
                        onOpenModal={() => this.setState({ beginDateModalOpen: true })}
                        onCancel={() => this.setState({ beginDateModalOpen: false, endDateModalOpen: false })}
                      />

**Comment by zemuldo** [comment]
+1 on this issue

**Comment by henninghall** [comment]
Thanks for reporting this, it is fixed in v4.1.0
