### ISSUE TITLE
Could not find com.github.henninghall:numberpickerview:v1.1.5

### ISSUE THREAD

**Issue by Lekhrajk** [henninghall/react-native-date-picker#396]
**Describe the bug**
I just installed the latest version from npm but i am getting this error while running app
Could not find com.github.henninghall:numberpickerview:v1.1.5.

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.64]
 - react-native-date-picker version [e.g. 4.0.0]

**Comment by elsieej** [comment]
> https://githubmemory.com/repo/henninghall/react-native-date-picker/issues/310
> 
> Looks like you need to add `maven { url 'https://www.jitpack.io' } `

It's still not working for me. 
React Native version [e.g. 0.70.1]
"react-native-date-picker": "^4.2.5",

**Comment by Umesh079** [comment]
I am having the same issue.

**Comment by SmolinPavel** [comment]
Same issue..

**Comment by giekus** [comment]
Well it seems that https://www.jitpack.io is down, and that's why the library can't be fetched.

**Comment by Norbiros** [comment]
This is issue from **2021**, now we have another error #5239

**Comment by Umesh079** [comment]
Jitpack down. https://www.saashub.com/jitpack-status

**Comment by rnkdsh** [comment]
same issue here

**Comment by raviranjan31** [comment]
same issue here

**Comment by Birat77** [comment]
same issue here: Could not determine artifacts for com.github.henninghall:numberpickerview:v1.1.5: Skipped due to earlier error

**Comment by henninghall** [comment]
This error happens when jitpack is down. It is back up now after some downtime today.

**Comment by unstoo** [comment]
> maven { url 'https://www.jitpack.io' }

Should it be added somewhere in the docs? Couldn't build one of my RN project without this line of code.
