### ISSUE TITLE
Invariant Violation: requireNativeComponent: "DatePickerManager" was not found in the UIManager

### ISSUE THREAD

**Issue by Vic-L** [henninghall/react-native-date-picker#40]
Hihi,

I am facing this error on android.
With reference to #15, I am not using expo and i use `react-native init` when I started the app.
App can install normally on Android, but fails on open the date picker.
Works normally on iOS.

Am I missing something?

**Comment by Vic-L** [comment]
I matched the andorid config files in the example directory and found that the lines in `MainApplication.java` were missing.

    ...
    import com.henninghall.date_picker.DatePickerPackage;
    ...
    protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        return Arrays.<ReactPackage>asList(
                ...
                new DatePickerPackage(),
                ...
        );
    }

It worked after adding these files. I removed my `android/build` while debugging this, leaving it here in case it matters.

Good work with the library by the way. Many thanks! 🎊

**Comment by nerdygirl** [comment]
I just ran into the same issue and this fix worked for me. Thanks!

**Comment by Jaja0624** [comment]
anyone using expo having same issue?

**Comment by Di4ik3r** [comment]
I ran into the same issue, but rebuilding (`react-native run-android`) - solved the issue

**Comment by yesIamFaded** [comment]
This Issue Still exists.... Using expo so I cant do the fix

**Comment by kritarth2121** [comment]
Please give the fix

**Comment by gaweki** [comment]
this still happen in my redmi note 9 pro. in android simulator pixel 4 xl works well

**Comment by sckwokyboom** [comment]
+

**Comment by minshaf998** [comment]
similar problem

**Comment by luluanacarla** [comment]
I'm having the same problem

**Comment by mgarcial1995** [comment]
I'm having the same problem whit Expo.

**Comment by amiellion** [comment]
on expo and have same problems

**Comment by thezeenagari** [comment]
> on expo and have same problems

This library can't be used in the "Expo Go" app because it [requires custom native code](https://docs.expo.dev/workflow/customizing/).
