### ISSUE TITLE
Support For Web

### ISSUE THREAD

**Issue by hasn-ab** [henninghall/react-native-date-picker#402]
**Describe the bug** 
Could not use it with react-native-web.

**Expected behavior** 
Should provide support for web as well. One way would be using index.web.js and writing web-specific code. Or if it does, need to update documentation.

**To Reproduce** 
Run it on web.
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Web(Chrome Browser)
 - React Native version [0.64.0]
 - react-native-date-picker version [3.3.0]

**Comment by henninghall** [comment]
react-native-web isn't supported yet, PRs are welcome! Keeping the web discussion here: 
https://github.com/henninghall/react-native-date-picker/discussions/313
