### ISSUE TITLE
Multiple DatePickers on one screen not working properly

### ISSUE THREAD

**Issue by FelixBaum** [henninghall/react-native-date-picker#403]
**Describe the bug**
If I add 2 DatePickers as modal to a single screen, everytime a modal is opened, I have to click two times on the cancel or confirm button. It seems as at first the first DatePicker is opened, after closing the first, the second one will be opened.

**Expected behavior**
Only the DatePicker opened with the open prop should be opened.

**To Reproduce**
```javascript
.
.
.
<>
<DatePicker is24hourSource="device" locale="de_DE" modal mode="datetime" open={startPickerOpen} date={start} onDateChange={(date) => {  }} onCancel={() => setStartPickerOpen(false)} onConfirm={(date) => { setStartPickerOpen(false); setStart(date) }} cancelText="Abbrechen" confirmText="Übernehmen" title={null}/>

<DatePicker is24hourSource="device" locale="de_DE" modal mode="datetime" open={endPickerOpen} date={end} onDateChange={(date) => {  }} onCancel={() => setEndPickerOpen(false)} onConfirm={(date) => { setEndPickerOpen(false); setEnd(date) }} cancelText="Abbrechen" confirmText="Übernehmen" title={null}/>
</>
.
.
.
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version: 0.65.1
 - react-native-date-picker version: 4.0.0

**Comment by henninghall** [comment]
Hi! This is fixed in 4.1.0
