### ISSUE TITLE
null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')

### ISSUE THREAD

**Issue by JamieDJ** [henninghall/react-native-date-picker#404]
Hi

I'm new to react native and I have an expo app that I am trying to use this package in in order to get the date requested by the user to display information within that time frame. However I am getting this error that I cannot figure out "null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')" may someone please assist

**Comment by PokerJava** [comment]
me too

**Comment by henninghall** [comment]
Have you created a custom expo client as described in the readme?

**Comment by henninghall** [comment]
Ok, does it work with the inline picker?

**Comment by gwalshington** [comment]
Why was this closed? What is the solution? I'm getting this out of (seemingly) nowhere with an Android datepicker that's been working properly for over a year.

Any suggestions?

**Comment by akiid777** [comment]
what is the solution please

**Comment by kylesziv** [comment]
I'm getting this as well.

**Comment by pratius** [comment]
> I'm getting this as well.
It's working for me if downgrading to the previous version:- "react-native-date-picker": "^4.1.2"

**Comment by yesIamFaded** [comment]
I have the same Issue ... downgrading does not fix it for me. I feel like all the DateTimePickers are BUGGY as Hell. I have tried 4 and all of them have different problems. 😞

**Comment by henninghall** [comment]
@yesIamFaded please remember that people are building these open source libraries on their free time, for free. Please help out by sending PRs fixings the bugs you find, or provide clear instructions of how to reproduce your issues. 

Regarding this issue, I still am not able to reproduce it, if anyone could supply a repo where this issue is present, or write step by step instructions of how to reproduce it in a clean project, that would be really helpful. Thanks!

**Comment by sayran123** [comment]
I was having the same issue and am running my simulator on my phone. After doing a yarn install, pod install, and rebuilding the project in Xcode it worked for me.

**Comment by Guribeiro** [comment]
### same issue here :disappointed:
**TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')**

    "react-native": "0.64.3",
    "react-native-date-picker": "^4.2.0",
    "expo": "~44.0.0",

**Comment by jereztech** [comment]
same issue but in production, in dev it's working fine.

**Comment by Goowwy** [comment]
any solution?

**Comment by sivadinesh1** [comment]
Why is this closed, all similar issues are mentioned as duplicate of #404 and there is no solution in #404. 
What is the solution #maintainers. understand people contribute during their free time. but if cannot have docs up to date. please close this project or mention it as not Production ready. takes away lot of engineers time

**Comment by pushparajsamant** [comment]
I faced the same issue when I was trying to run it using expo go. It worked when I ran it using expo run:ios or expo run:android. Maybe something that will work for you guys.

**Comment by Loot1** [comment]
Same problem with expo go here.

react-native: 0.64.3
react-native-date-picker: 4.2.2
expo: 44.0.0
expo-dev-client: 0.8.6

**Comment by henninghall** [comment]
Still cannot reproduce it. If anyone can share a repo where this problem is present, then I will investigate this.

And make sure you have followed the specific installation instructions for Expo before doing that.

**Comment by pushparajsamant** [comment]
@henninghall I get that error when used with plain expo go. Followed the instructions to the T.

**Comment by ninizoo** [comment]
same issue with expo start.

https://docs.expo.dev/workflow/customizing/
The classic expo build command does not support custom native code. When you're ready to ship your app, you can build it with EAS Build or archive and sign it locally.

It works for me.

in dev)
expo run:android

in production)
eas build --platform android

**Comment by Barely-Dead** [comment]
I ran into the same error but I don't think it's an issue with the package itself, it's how you run your project. I haven't tried expo but in a bare react native project if you run **npm start** you will get the error, if you run **npx react-native run-ios** there is no error. Similar to what @ninizoo said about expo. Probably why after a year this hasn't been resolved because there isn't actually anything to fix. 

Also, if your using expo why not just use https://docs.expo.dev/versions/latest/sdk/date-time-picker/ ? It has more dedicated support.

**Comment by Namlifebuoy** [comment]
This error appeared when i installed react-native-date-picker library but forgot pod install. Please pod install and rebuild the app. Hope it helps you

**Comment by summerlove57** [comment]
I also encountered the same crash. 

I stopped the server and deleted the app in the emulator. Recompile with xcode and it's fine now.

**Comment by amithgolla** [comment]
I got the same error. It turns out that I forgot to rebuild the project. I ran "npx react-native run-android", and it worked fine.

**Comment by lordkyle0** [comment]
You should run expo run: android or ios in Expo bareworkflow to make all changes in your project

**Comment by akram-chopdawg** [comment]
i faced the by pod-install and re-running its work  its work for me

**Comment by Osmanity** [comment]
by using plain expo project with expo still gives this issue

**Comment by prabhatCH** [comment]
Same issue and unable to resolve it. 
Finally switched to [this module](https://github.com/mmazzarolo/react-native-modal-datetime-picker) which has much clearer instructions on installation in expo and works without any hiccup right out of the box.

**Comment by nabilcambiaso** [comment]
on expo, the solution i found is:
first run `expo run:ios` then it will install a bunch of stuff, then a ios directory will show up, only then enter to that directory and run the command `pod install` then if all has been installed successfully run your app again, using `expo run:ios`

**Comment by emre-sozen** [comment]
You have to delete project from your emulator, close metro and then run project. It worked for me.

**Comment by MatheusLima1** [comment]
In my case, I was using expo and eas build, I needed to build another version using the eas build to both platforms, and after this worked.

**Comment by Dawnthorn** [comment]
Adding "@react-native-community/datetimepicker": "6.5.2" to package.json fixed this issue for me.

**Comment by ashokdv** [comment]
Why is it closed?

**Comment by anniewey** [comment]
Getting same error after upgrading to `4.3.0` from `4.2.1`. 

Ran `pod install`, tried delete `DerivedData` and reset packager cache but not working either.
Downgrading back to `4.2.1`.

```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')
```

**Comment by henninghall** [comment]
@thachnqc2c So far, no one has been able to supply a repo where this is reproducible. If you can, please do. That is the only way this issue can be reopened. 

To my understanding, this error often happens because:
- You are trying to use Expo Go (it is not supported, see README)
- You haven't run `pod install` properly
- You haven't rebuilt the project with run-ios / run-android or equivalent. 

I'll try to make a better error message around this at some point.

**Comment by JoeMartin2001** [comment]
Any updates?

**Comment by zanotta** [comment]
@anniewey solution worked for me: downgrade to "react-native-date-picker": "4.2.1"

**Comment by gioanrobles24** [comment]
I started to have this problem after the iOS 17 update, maybe is related ?

**Comment by zanotta** [comment]
> I started to have this problem after the iOS 17 update, maybe is related ?

i don't think so, i had clients with the same bug using iOS 16.

**Comment by gioanrobles24** [comment]
> > I started to have this problem after the iOS 17 update, maybe is related ?
> 
> i don't think so, i had clients with the same bug using iOS 16.

i tried your solution and did not worked for me :( on iOS 17, i 'am downloading iOS 16 just to be sure.

**Comment by zanotta** [comment]
> > > I started to have this problem after the iOS 17 update, maybe is related ?
> > 
> > 
> > i don't think so, i had clients with the same bug using iOS 16.
> 
> i tried your solution and did not worked for me :( on iOS 17, i 'am downloading iOS 16 just to be sure.

good luck my friend.

for me, the downgrade, pod install and rebuild via xcode worked.

**Comment by ceres-quangd** [comment]
same issue, I have downgraded to 4.2.1 to solved this out

**Comment by ah584d** [comment]
the issue is after 4.3.x, when you run pod install it deletes the reference from Podfile.lock

![image](https://github.com/henninghall/react-native-date-picker/assets/30211873/0c237211-bc06-41d5-94c4-a0de0a528fbf)
and then crashes in runtime obviously
