### ISSUE TITLE
Displayed Time is Diffrent in Modal and Inline

### ISSUE THREAD

**Issue by Finneah** [henninghall/react-native-date-picker#407]
**Describe the bug**
When i choose modal, the DatePicker shows the hours one hour behind. When i choose inline, the displayed hour is correct.

**Expected behavior**
Displayed hour is the given hour.

**To Reproduce**
```javascript
export const DateTest = ({ route, navigation }) => {

const [date, setDate]= useState(new Date("2021-12-12T08:50:25Z")) // <= one hour behind new Date() <= two hours behind
  
 
  return (
    <DatePicker
	modal
	open={datePickerIsOpen}
	date={date} 
	
	onConfirm={(date) => {
		setDate(date);
           
		setDatePickerIsOpen(false);
	}}
	onCancel={() => {
		setDatePickerIsOpen(false);
	}}
	onDateChange={(date) => {
			setDate(date);
                     
	}}
    />
)
}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS] Tested only on iOS
 - React Native version [0.63.4]
 - react-native-date-picker version [4.1.0]
 
**Screenshots**
*inline*
![Bildschirmfoto 2021-10-13 um 13 29 21](https://user-images.githubusercontent.com/30401702/137124574-e5cdc16d-4022-40a3-90ef-47bd6d4f1d3e.png)
*modal*
![Bildschirmfoto 2021-10-13 um 13 29 29](https://user-images.githubusercontent.com/30401702/137124581-8d052680-8aba-4a72-a042-317d0e1434e4.png)

**Comment by christinehesher** [comment]
I have the same issue with dates for some years (changes between 12 and 13 every ten years apparently???)
![Screenshot 2021-10-13 at 17 14 11](https://user-images.githubusercontent.com/12895938/137150933-48e18ca2-db1e-4688-bd60-4e38c356f898.png)
