### ISSUE TITLE
timeZoneOffsetInMinutes is not getting the default in modal mode

### ISSUE THREAD

**Issue by francesco-clementi-92** [henninghall/react-native-date-picker#408]
**Describe the bug**
When the react-native-date-picker component is used with the in-line mode, the date is shown with the device timezone.

When the same component is shown in the modal mode, the date is shown without the device timezone.

**Smartphone :**
 - OS: iOS
 - React Native version 0.64.0
 - react-native-date-picker version 4.1.0

**Comment by francesco-clementi-92** [comment]
I don't have dayjs installed and I'd like to avoid it

**Comment by bogdan2510** [comment]
then use moment or date-fns

**Comment by adityatagline** [comment]
> you can fix this by getting the offset and then using 'timeZoneOffsetInMinutes' on datepicker. `const currentTimeZoneOffsetInHours = dayjs(Date).utcOffset() / 60;` the add `timeZoneOffsetInMinutes={currentTimeZoneOffsetInHours * 60}`

This piece of heaven saves the day, I have used moment instead of dayjs.
Thanks though.
