### ISSUE TITLE
i get bug when use 2 datepicker in 1 screen

### ISSUE THREAD

**Issue by dongchiteo264** [henninghall/react-native-date-picker#409]
when I use 2 different date pickers on the same screen and get 2 different values, the opening variable is also different. But when I change the value, both change. It seems that the system thinks 2 dateicker is 1.
Although these two are completely different

Anyone please help me

**Comment by Finneah** [comment]
francesco-clementi-92 Can you show your Code plz? It would help. And take a look at #408

**Comment by henninghall** [comment]
This problem is fixed in 6.1.0. If you are using that version, please resubmit the issue with the proper issue template
