### ISSUE TITLE
is24Hour format ?

### ISSUE THREAD

**Issue by Humbl-e** [henninghall/react-native-date-picker#41]
I wish to show the time according to the device setting : "Use 24-hour format" .
Currently if i change locale to 'eng-US' i get AM/PM which is default but i would like to give priority to device setting of 24-hour format for 'time mode' at least.
Is this possible if so how?

Thanks

**Comment by henninghall** [comment]
Hi @Humbl-e! This is not possible at the moment! As you say the only way to change the 24h format is changing the locale. But I agree that It would be a good feature!

**Comment by henninghall** [comment]
Hi @Humbl-e! This is unfortunately not possible at the moment. As you say the only way to change the 24h format is changing the locale. But I agree that It would be a good feature!

**Comment by henninghall** [comment]
This is fixed in https://github.com/henninghall/react-native-date-picker/commit/d6491b6c47adaa85d2a66f47269bdfbce6598662 and will be available in the next release!

**Comment by Humbl-e** [comment]
Thanks alot!! :)

**Comment by henninghall** [comment]
Released in v2.4.0
