### ISSUE TITLE
Android crash RangeError: Date value out of bounds. 

### ISSUE THREAD

**Issue by LucacelRazvan** [henninghall/react-native-date-picker#416]
**Describe the bug**
I added the DatePicker with date mode component and used date as state, when the component is rendered the app crashes with
RangeError: Date value out of bounds. 
Source Error:
DatePickerAndroid.js
    retrun addMinutes(...)

**Expected behavior**
I expect the app not to crash.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
              date={date}
              androidVariant="iosClone"
              onDateChange={responseDate => {
                setDate(new Date(responseDate));
              }}
              mode={'date'}
              textColor={Color.PINK}
            />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.65.1]
 - react-native-date-picker version [e.g. ^4.1.0]

**Comment by LucacelRazvan** [comment]
Update:
const [date, setDate] = React.useState(
    new Date('December 17, 1995 03:24:00'),
  );
  this chases on Android,
  but this works on Android:
  const [date, setDate] = React.useState(
    new Date(),
  );
  
  
  No problems on Ios with any option

**Comment by jtvargas** [comment]
Any updates, why is causing this issue?

**Comment by jtvargas** [comment]
Update: I found that disabling Hermes in RN 0.65 fixed the issue... but is not the preferred solution

**Comment by Joshandrews43** [comment]
Experiencing this issue as well, do we have any solution?

**Comment by shoaib2527** [comment]
I had the same issue. I think its something with Date Format. I got it working by replacing 

    const getTime = dayjs(time).format(TimeFormat);

    const getDate = dayjs(date).format(DateFormat);
    
    const newDate = dayjs(`${getDate} ${getTime}`).toDate();
    
    if (onChange) onChange(newDate);
    
with this
    
    const hour = dayjs(date).hour();

    const minute = dayjs(date).minute();

    const newDate = dayjs(selectedDate).startOf('day').add(hour, 'hour').add(minute, 'minute').toDate();

    if (onChange) onChange(newDate);`
    
"newDate" variable is being passed to date-picker as value of "date" prop.

**Comment by henninghall** [comment]
This Hermes bug is tracked here https://github.com/facebook/hermes/issues/647. It is not related to this library.

**Comment by erickcrus** [comment]
Disable hermes isn't a option. How to resolve that problem?

**Comment by nguyenvinhhn** [comment]
`
fix:  String(fromDate)

<DatePicker date={ new Date(String(fromDate)) }  onDateChange={setFromDate} />
`

**Comment by umairm1alik** [comment]
make sure the value you are passing to date is a date object like new Date()
<DatePicker
                  modal
                  mode="date"
                  open={open}
                  minimumDate={new Date()}
                  date={
                    !profileData?.chef_certificate_expiry_date
                      ? new Date()
                      : new Date(profileData?.chef_certificate_expiry_date)
                  }
                  onConfirm={dateString => {
                    setOpen(false);

                    handleProfileDataChange(
                      'chef_certificate_expiry_date',
                      dateString,
                    );
                  }}
                  onCancel={() => {
                    setOpen(false);
                  }}
                />
