### ISSUE TITLE
I can't get the right time when I select the time.

### ISSUE THREAD

**Issue by leonidlewis** [henninghall/react-native-date-picker#427]
I made some time picker with this module.
When I select the time in the time panel, I get the wrong time .
![image](https://user-images.githubusercontent.com/83287135/144671241-2c6cc41f-972d-4b4e-8c4d-e5e16b5c2df0.png)
![image](https://user-images.githubusercontent.com/83287135/144671281-43ab245e-f37d-4e62-bb68-49d30282a9c7.png)
Why do I get this time?

**Comment by henninghall** [comment]
The picker will be displayed in local time. How do you format the Date when 7.39 is displayed?
