### ISSUE TITLE
minDate & maxDate not working 

### ISSUE THREAD

**Issue by MostafaBillett** [henninghall/react-native-date-picker#43]
I was trying to limit the picker to display only two days, so i made something like this

```
<DatePicker
            date={moment().format('YYYY-MM-DD')}
            onDateChange={date => this.setState({ startDate: date })}
            minDate={moment(new Date()).add(1, 'days').format('YYYY-MM-DD')}
            maxDate={moment(new Date()).format('YYYY-MM-DD')}
 />
```

and i also tried to make it with JS Date to be something like this but it didn't work either

```
maxDate: new Date().setHours(new Date().getHours() + (24 * 2)),
minDate: new Date().setHours(0),
```

so what I'm doing wrong here?

**Comment by henninghall** [comment]
Hi! date, minDate and maxDate are supposed to be Date objects. Not strings. Maybe you could use the `.toDate()` from moment.

**Comment by henninghall** [comment]
To clearify: 

Your second attempt returns a unix timestamp and not a Date object. You should be able to do something like this to get a date object:  
```new Date((new Date().setHours(0,0,0,0)))```

If you use moment you could use moment's `toDate()`

**Comment by MostafaBillett** [comment]
Thank you, it's working fine in android only, in ios it doesn't work, is it because of the `getTime()` that is in the date picker ios
