### ISSUE TITLE
How to change fontSize of picker data? 

### ISSUE THREAD

**Issue by jocoders** [henninghall/react-native-date-picker#433]
Guys you have such an amazing picker library. It has fixed a few bags that I have on the previous picker library, but only one thing is bothering me: on IOS in the date mode the data does not fit in the case of ranges with a few pickers. The month is short and the year is not visible. And I have not found any props to change the fontSize. Please can you tell my how can I do it?

![Simulator Screen Shot - iPhone 5s - 2021-12-13 at 14 51 58](https://user-images.githubusercontent.com/41040813/145809710-e4b05d39-b062-4bbd-a616-daf56fee84df.png)

**Expected behavior**
It is possible to change fontSize of date.

**To Reproduce**
Add example code that reproduces the behavior. 
```
  private renderDates() {
    return this._dates.map((options, index) => {
      const key = `WheelDatePicker ${index}`;

      return (
        <React.Fragment key={key}>
          <DatePicker
            style={{ flex: this._dates.length === 2 ? 0.5 : 1, fontSize: 10 }}
            androidVariant={'iosClone'}
            maximumDate={options.max}
            date={options.date}
            locale={'ru-RU'}
            mode={'date'}
            confirmText={'PUSH ME'}
            onDateChange={options.onChangeDate} />
            <Text color={_textColor} absolute>{'\u2014'}</Text>
        </React.Fragment>
      );
    });
  }

```

**Smartphone (please complete the following information):**
 - OS: IOS 12.1
 - React Native version 0.64.2
 - react-native-date-picker version 4.1.3

**Comment by henninghall** [comment]
Font size discussions is held here https://github.com/henninghall/react-native-date-picker/discussions/171
