### ISSUE TITLE
Android: DatePicker androidVariant={'nativeAndroid'} does not work with API Level 23

### ISSUE THREAD

**Issue by Finneah** [henninghall/react-native-date-picker#434]
**Describe the bug**
The Picker isnt visible with androidVariant={'nativeAndroid'}. 
I tried it with modal and inline. 

Its only visible with androidVariant={'iosClone'}

**Expected behavior**
The Picker is visible in nativeAndroid Variant**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
        androidVariant={"nativeAndroid"}
        is24hourSource={'locale'}
        locale="de-DE"
        modal
        open={datePickerIsOpen}
        date={editTask.dueDate ? new Date(editTask.dueDate) : new Date()}
        onConfirm={(date: { toISOString: () => any }) => {
	        // do what you have to do
        }}
        onCancel={() => {
	        // setDatePickerIsOpen(false);
        }}
        onDateChange={(date) => {
        // this Function has to be set but it has no usability on modal
        }}
        confirmText={'CONFIRM'}
        cancelText={'CANCEL'}
/>
```

**Smartphone (please complete the following information):**
 - OS:Android Pixel 2 emulator and Samsung Galaxy A5 API Level 23 Real Device
 - React Native version 0.63.4
 - react-native-date-picker version 4.1.0
 
See Screenshot (sry, had to hide some stuff because of Data Privacy)
![Bildschirmfoto 2021-12-13 um 16 47 06](https://user-images.githubusercontent.com/30401702/145855406-0a689698-04a7-4a90-baa2-7626f037b9c4.png)

**Comment by henninghall** [comment]
Hi, did you get any error message in logcat when this happens?
