### ISSUE TITLE
iOS 15 keyboard numpad accepts off numbers and cannot disable it

### ISSUE THREAD

**Issue by gabrielmoncea** [henninghall/react-native-date-picker#435]
**Describe the bug**
Since iOS 15 you can tap on the wheel to call the keyboard and type the time. There is no way to disable it and also you can type out of range numbers.

https://user-images.githubusercontent.com/39256258/145984310-c24cb045-4050-4088-89dc-296146845376.MP4

**Expected behavior**
Need a way to disable numpad if possible, restrict typing to hour - minute range.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      maximumDate={getMaximumDate()}
      mode="datetime"
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: `iOS`
 - React Native version: 0.64.2
 - react-native-date-picker version: 4.1.3

**Comment by henninghall** [comment]
Did some investigation but unfortunately this doesn't seem to be possible due to limitations of [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker). It isn't much written about it but if anyone finds a way to solve this, please let me know.

**Comment by iGroza** [comment]
@henninghall hi, I fixed this issue, by handling UIControlEventEditingDidBegin event.

**DatePicker.m**
```objc
- (instancetype)initWithFrame:(CGRect)frame
{
    if ((self = [super initWithFrame:frame])) {
        [self addTarget:self action:@selector(handleDatePickerTap) forControlEvents:UIControlEventEditingDidBegin];
        // ^^^^ added this line to initWithFrame

...

- (void)handleDatePickerTap  {
    [self resignFirstResponder];
}
```

**Comment by henninghall** [comment]
Oh that's great! Do you mind creating a PR?

**Comment by henninghall** [comment]
Thanks for the PR @iGroza! Just for my understanding. Could it be reasons for keeping this feature for some use cases? (we could create a prop) or is this just broken for everyone you mean?

I though that it is probably a reason for the feature to be introduced? 🤔

**Comment by gabrielmoncea** [comment]
I agree to have it as a prop. Apple thinks it's a feature, while some designers / PMs think it's a bug :P

**Comment by aayush123** [comment]
This problem still exists. Can we re-open the issue?
