### ISSUE TITLE
Yellow console logs when using app on web

### ISSUE THREAD

**Issue by roivasxxx** [henninghall/react-native-date-picker#436]
**Describe the bug**
Everything **works fine for both android on ios**, however I'm using it for my app that will be used on web aswell. **I do know that the picker doesn't work for web.** I got it working on web by just using require when not on web, however bellow code is printed out in console. I have to note that this doesn't lead to any unexpected behavior going on. The only thing that's happening are the logs.

`./node_modules/react-native-date-picker/src/propTypes.js:35:10
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  33 |   textColor: PropTypes.string,
  34 |   timeZoneOffsetInMinutes: PropTypes.number,
> 35 |   testID: ViewPropTypes.testID,
     |          ^
  36 |   style: ViewPropTypes.style,
  37 |   ...modalPropTypes,
  38 | }
./node_modules/react-native-date-picker/src/propTypes.js:36:9
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  34 |   timeZoneOffsetInMinutes: PropTypes.number,
  35 |   testID: ViewPropTypes.testID,
> 36 |   style: ViewPropTypes.style,
     |         ^
  37 |   ...modalPropTypes,
  38 | }
  39 |
./node_modules/react-native-date-picker/src/DatePickerIOS.js:9:25
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
   7 | //let {requireNativeComponent} = Platform.OS==="web"?null:require('react-native')
   8 |
>  9 | const RCTDatePickerIOS = requireNativeComponent('RNDatePicker')
     |                         ^
  10 |
  11 | export default class DatePickerIOS extends React.Component {
  12 |   _picker = null
./node_modules/react-native-date-picker/src/DatePickerAndroid.js:9:25
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
   7 | }
   8 |
>  9 | const NativeDatePicker = requireNativeComponent(
     |                         ^
  10 |   `DatePickerManager`,
  11 |   DatePickerAndroid,
  12 |   { nativeOnly: { onChange: true } }`

**To Reproduce**
```javascript
function datePicker(prop) {
    if (Platform !== "web") {
      const DatePickerNative = require("react-native-date-picker").default
      return (
        <DatePickerNative
          date={attendanceState[prop]}
          onDateChange={(date) => handlePropChange(prop, date)}
          locale={locale}
        />
      )
    }
  }
```

 - OS: Web
 - React Native version: 0.63.4
 - react-native-date-picker version: 4.1.3
- Expo SDK 42.0.1

EDIT: 
```javascript
function datePicker(prop) {
    if (Platform.OS !== "web") {
      const DatePickerNative = require("react-native-date-picker").default
      return (
        <DatePickerNative
          date={attendanceState[prop]}
          onDateChange={(date) => handlePropChange(prop, date)}
          locale={locale}
        />
      )
    }
  }
```

**Comment by henninghall** [comment]
Shouldn't it be `Platform.OS`?

**Comment by roivasxxx** [comment]
> Shouldn't it be `Platform.OS`?

Ah yes my bad, fixed it in the code, however the errors persist.

**Comment by roivasxxx** [comment]
Found a way of fixing it creating files with platform-specific file extensions (foo.android.js, foo.web.js,...)and  importing the DatePicker in ..android.js and ..ios.js files.
