### ISSUE TITLE
requireNativeComponent: "RNDatePicker" was not found in the UIManger IOS!

### ISSUE THREAD

**Issue by Adarwall** [henninghall/react-native-date-picker#44]
Hi, I'm not using Expo as in previous issues and still have this problem on ios.
I followed the instructions and even tried to link it manually and it didn't work either.
thanks in advance.
<img width="343" alt="Screen Shot 2019-04-08 at 22 36 24" src="https://user-images.githubusercontent.com/42234958/55751730-11428880-5a4f-11e9-88bc-70aa02522cbf.png">

**Comment by henninghall** [comment]
Hi! Looks like a linking problem. I would try manual linking again with this [manual linking guide](https://facebook.github.io/react-native/docs/linking-libraries-ios) carefully. Remember to rebuild your project afterwards in Xcode or by running `react-native run-ios `again.

**Comment by Adarwall** [comment]
Oh, I forgot to rebuild... oops.
It works now! thanks! :)

**Comment by henninghall** [comment]
Great!

**Comment by tipos** [comment]
Hi everyone! According to docs, there is no need to link if the RN version is greater than 0.59: 

![image](https://user-images.githubusercontent.com/6452564/90317179-17f1e180-df5a-11ea-9490-0c1025db2440.png)

I am using expo v38.0.8 with RN >0.60 but it still throws `requireNativeComponent: "RNDatePicker" was not found in the UIManger IOS!` error on both iOS and Android. 

Is there a way to use this package without ejecting expo?

**Comment by dnlmzw** [comment]
I'm also getting this error with Expo. Restarting my server doesn't fix it :/

**Comment by henninghall** [comment]
@dnlmzw expo does not support this component. See Readme
