### ISSUE TITLE
Modal get closed on confirm date( modal={true}, if i have't change open state to false.

### ISSUE THREAD

**Issue by rkkb** [henninghall/react-native-date-picker#442]
**Describe the bug**
Modal get closed on confirm date button press( modal={true}, even if i have't change open state to false.

**Expected behavior**
The controlled way should be, Modal should't close until I changed the open state from true to false.

**To Reproduce**
Add example code that reproduces the behavior. 
<DatePicker
          date={new Date(currentDate)}
          mode="datetime"
          androidVariant="nativeAndroid"
          minimumDate={new Date(currentDate)}
          maximumDate={new Date(moment(currentDate).add(23, 'd').format('YYYY-MM-DD'))}
          fadeToColor={Color.WHITE_COLOR}

          modal
          open={showDateModal}
          onConfirm={(date) => {
            if (moment(date).format("d") !== '1'){
              ToastError({ message: "Only monday are available to start diet plan" })
            }
            else {
              Toast({ message: "Success! Monday choosed" })
              this.setState({
                showDateModal: false,
                selectedDate: moment(date).format('YYYY-MM-DD')
              })
            }

          }}
          onCancel={() => {
            this.setState({ showDateModal: false })
          }}

**Smartphone (redmi 10):**
 - OS: Android  11
 - React Native version  "0.64.1",
 - react-native-date-picker version ^4.1.3

**Comment by henninghall** [comment]
Please include the platforms, versions etc as described in the issue template

**Comment by rkkb** [comment]
@henninghall These are the spec(also edited in issue) - **Smartphone (Redmi note 10):**
 - OS: Android  11
 - React Native version  "0.64.1",
 - react-native-date-picker version ^4.1.3
