### ISSUE TITLE
Setting minimumDate disables the month picker

### ISSUE THREAD

**Issue by henrik-funmed** [henninghall/react-native-date-picker#443]
**Describe the bug**
Setting minimumDate disables the month picker.

**Expected behavior**
When setting minimumDate I should still be able to select a coming month.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
          mode="date"
          minimumDate={new Date()}
          date={...}
          onDateChange={date => ...}
 />
```

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version 0.64.1
 - react-native-date-picker version 4.1.3

**Comment by henninghall** [comment]
Isn't that because it is December now? What happens if you change the year to 2022?

**Comment by henrik-funmed** [comment]
As @henninghall pointed out. It is because it is December, so the user needs to change year first! 👍
