### ISSUE TITLE
"RNDatePicker" was not found in the UIManager

### ISSUE THREAD

**Issue by FranciscoMendes10866** [henninghall/react-native-date-picker#449]
**Describe the bug**

In the application I'm developing I used the dependency and I don't have any problems during the development environment. However, as soon as we are going to test the application in TestFlight, as soon as the component comes into focus the application just crashes immediately.

**To Reproduce**

The component is only reused twice in the application and exactly in these two screens is when the problem occurs. Below I leave the reusable component that was created:

```javascript
import React, { VFC } from 'react';
import DatePicker from 'react-native-date-picker';
import { getColor } from 'utils/tailwind';

import styles from './styles';

type IProps = {
  width: number;
  date: Date;
  onDateChange: (newDate: Date) => void;
  minuteInterval?: 1 | 2 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30;
  minimumDate?: Date;
};

export const DateTimePicker: VFC<IProps> = ({
  width,
  date,
  onDateChange,
  minuteInterval = 1,
  minimumDate,
}) => {
  return (
    <DatePicker
      mode="time"
      androidVariant="iosClone"
      textColor={getColor('black-100')}
      onDateChange={(value: Date) => onDateChange(value)}
      date={date}
      style={[styles.picker, { width }]}
      minuteInterval={minuteInterval}
      minimumDate={minimumDate ? minimumDate : undefined}
      timeZoneOffsetInMinutes={0}
    />
  );
};

```

**Smartphone**
 - OS: iOS
 - React Native version: 0.64.1
 - react-native-date-picker version ^4.1.3

**Extra Notes**

Before opening this issue to report the bug and look for a solution to the problem, other similar issues have already been seen but unfortunately we have not had any success. In addition, the following commands were executed, but without success.

```sh
rm -rf ios/build
rm -rf ~/Library/Developer/Xcode/DerivedData
watchman watch-del-all
rm -rf node_modules
yarn
npx pod-install ios
```

**Error we got**

```sh
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: requireNativeComponent: "RNDatePicker" was not found in the UIManager.
```

**Comment by alephpt** [comment]
why was this closed? solution?
