### ISSUE TITLE
[Question] Date format support

### ISSUE THREAD

**Issue by filipef101** [henninghall/react-native-date-picker#45]
Does this allow to pick day-month-year instead of month-day-year ?
Else where should I look into to add dateFormat param?
Thanks dude

**Comment by henninghall** [comment]
Yes it does! The locale prop affects the order according to the locale's preference.

**Comment by afizboltz** [comment]
what locale's preference for DD-MM-YYYY format ya ?

**Comment by afizboltz** [comment]
got it its `locale="en-GB" `

hope it will helps others

cheerss

**Comment by henninghall** [comment]
If you don’t have a very good reason to, you should let the user use their own preference and not force one. 

That can be done be leaving out the locale prop and go with the defaults.
