### ISSUE TITLE
crash on debug in chrome mode

### ISSUE THREAD

**Issue by fkazemi5236** [henninghall/react-native-date-picker#451]
hello
I'm using this package and everything is worked correctly, when I open the debug in chrome, App is crashed !

also I add this codes in "proguard-rules.pro"
-keep public class net.time4j.android.ApplicationStarter
-keep public class net.time4j.PrettyTime

reset the cache and run the app
but debug not work and still crash the app :(

**Comment by henninghall** [comment]
Hi, please follow the issue template or I wont be able to investigate this. Create a new issue filling out the template provided.
