### ISSUE TITLE
onDateChange not updating fast enough, reverts to previous state upon not being able to register the scroll-select (iOS)

### ISSUE THREAD

**Issue by Guide4Ever** [henninghall/react-native-date-picker#453]
### Issue
onDateChange function is not updating fast enough. Sometimes when I quickly scroll and select let say 4 numbers (sequentially), the last (in our case 4th value) is not registered thus reverting back to the 3rd. That occurs with each scroll wheel separately. It's not an issue of combined scrolling of i.e. days and months. Individual scroll picker inherits this issue. 

The last value upon fast scroll-select does not get updated/ registered by onDateChange function, it locks to the previous state. (short explanation).

### Expected Behavior

Should register the last value even if it's being fast scrolled.

### Code

```javascript
      <DatePicker
        scrollRef={scrollRef}
        mode="time"
        date={date}
        locale="en"
        open={pickerOpen}
        onDateChange={changeFunction}
        minuteInterval={15}
      />
```

### Environment

1. `react-native -v`: 0.66.1
2. `node -v`: v16.13.0
3. `npm -v`: 8.1.0
4. `target platform`: iOS (could be Android too, haven't tested there yet)
5. `operating system`: macOS (emulator Xcode)

**Comment by DanielZyger** [comment]
same problem here

**Comment by kollinmurphy** [comment]
A very similar thing is happening to me. I'm using the modal date & time pickers. When the confirm button is clicked too soon, it calls `onConfirm` with the original date. This is happening on both iOS and Android. I've attached a screen recording of it happening on the iOS simulator.

https://user-images.githubusercontent.com/65209071/212437881-341ab122-cfdb-4020-b62d-13988891bb58.mov

**Comment by RWSDev** [comment]
This should be expected behavior.

on iOS:
- (void)pickerView:(UIPickerView *)thePickerView 
      didSelectRow:(NSInteger)row 
       inComponent:(NSInteger)component {
}

does not happen until the picker stops moving... I'm assuming it's the same in Android (but unsure)

**Comment by dcdavidheisnam** [comment]
It's happening on Android as well. Quite confusing when it happens during regular use.

**Comment by dcdavidheisnam** [comment]
onDateChange is firing late even when the animation has stopped. For example, when I switch AM to PM, it takes a whole second becore the onDateChange is fired. This really breaks the user experience because we're going to have to expect the user to wait before clicking on Save or Confirm.

**Comment by henninghall** [comment]
Let's keep the discussions around this problem in [this issue](https://github.com/henninghall/react-native-date-picker/issues/340),
