### ISSUE TITLE
prevent 24-format

### ISSUE THREAD

**Issue by hasan642** [henninghall/react-native-date-picker#457]
**Describe the bug**
I want to use 12 hours format time regardless 

**Expected behavior**
A prop that changes format (24/12) regardless device settings

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version: 0.64.3
 - react-native-date-picker version: 4.1.3

**Comment by henninghall** [comment]
Hi, what is your use case for this? When do we want to force a user who prefers 24h format to use 12h format? 

Reason for not supporting this is discussed here https://github.com/henninghall/react-native-date-picker/issues/130
and in [readme](https://github.com/henninghall/react-native-date-picker#how-do-i-change-the-1224h-or-ampm-format) etc
