### ISSUE TITLE
Hour of 1 is displayed as 12 on modal time wheel

### ISSUE THREAD

**Issue by BrettThePark** [henninghall/react-native-date-picker#459]
**Describe the bug**
When using a modal time picker with an initial time of 1am, the hour wheel starts on index 1, but the textual value is 12.

**Expected behavior**
Expect the textual hour to be 1

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
            <DatePicker
                modal
                mode={'time'}
                androidVariant={'nativeAndroid'}
                open={true}
                date={Some date with time of 1am}
                textColor={'black'}
            />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.64.1
 - react-native-date-picker version 4.1.3
![Screen Shot 2022-02-15 at 11 01 38 AM](https://user-images.githubusercontent.com/1700608/154112803-99f88ac9-b81f-4361-a731-9e49f15fc47e.png)

**Comment by henninghall** [comment]
Hi, this is fixed in version `4.1.5`
