### ISSUE TITLE
Wheels order not support in rtl direction (Hebrew/Arabic)

### ISSUE THREAD

**Issue by Oded-Zilkha-Blayberg** [henninghall/react-native-date-picker#462]
### **Describe the bug**
Wheels order not support Hebrew/Arabic. For this languages the order should be different.

### **Expected behavior**
**When the locale language is hebrew/arabic**

**- In datetime mode the day wheel should be in the right of the time wheels:**
current:
<img src="https://user-images.githubusercontent.com/65946240/154723065-2c93f4b5-255a-4685-9f89-9d1943d86e51.jpeg" height="250"></img>
wanted:
<img src="https://user-images.githubusercontent.com/65946240/154723103-d8c14067-f4e4-4863-b29c-13bc3a3ff261.jpeg" height="250"></img>

**- In date mode the wheels should be reversed:**
current:
<img src="https://user-images.githubusercontent.com/65946240/154723089-0297d9ef-c39b-45ee-a8d8-3612dfeacc5d.jpeg" height="250"></img>
wanted:
<img src="https://user-images.githubusercontent.com/65946240/154723121-016ff68f-6b46-42ad-ba1d-b5b8854892c7.jpeg" height="250"></img>

**Comment by henninghall** [comment]
Hi, thanks for reporting this. Does it look as expected on ios?

**Comment by Oded-Zilkha-Blayberg** [comment]
I can't check if its work well on ios because I have only android device. I guess it works because from what I have seen you use the ios built-in component.

**Comment by Oded-Zilkha-Blayberg** [comment]
@henninghall I fixed the issue but I have no permission to push my branch. Can you give me permission?
Thanks

**Comment by henninghall** [comment]
@Oded-Zilkha-Blayberg  Great! You would have to fork this repo, push to a branch on the fork, and then create a [Pull Request](https://github.com/henninghall/react-native-date-picker/pulls) from your fork to this repo. Thanks for your help!

**Comment by henninghall** [comment]
Both `datetime` and `date` mode looks like expected (same as iOS) to me for the `he` / hebrew locale. 

<img width="614" alt="Screenshot 2022-04-17 at 10 15 14" src="https://user-images.githubusercontent.com/1652607/163706424-81e6c609-93bd-40a4-b581-1728242e3468.png">

<img width="667" alt="Screenshot 2022-04-17 at 10 10 13" src="https://user-images.githubusercontent.com/1652607/163706428-a3cc0284-538a-4d3b-8ef1-4010002d3d6a.png">

Is it the "he" locale that is the right one? Can you give example of popular app that handles this date format as you suggest? In that case I can reopen this issue and look into it again.

**Comment by LinhLM23496** [comment]
and for locale="vi"
