### ISSUE TITLE
how to set 24 hour time format? Is this possible?

### ISSUE THREAD

**Issue by TarunDas284** [henninghall/react-native-date-picker#47]

**Comment by henninghall** [comment]
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/41

**Comment by club9822** [comment]
just do this in `con.henninghall.date_picker.wheels.Setting.java`

public class Settings {
    public static boolean usesAmPm (){
        return false;
        // return !DateFormat.is24HourFormat(DatePickerManager.context);
    }
}

**Comment by henninghall** [comment]
@club9822 That would only work on Android though.
