### ISSUE TITLE
Unable to build debug with react native 0.67.3

### ISSUE THREAD

**Issue by lvlrSajjad** [henninghall/react-native-date-picker#474]
**Describe the bug**
After upgrading to RN 0.67.3,  I can't build my app because of this error

`Declaration of 'RCTBubblingEventBlock' must be imported from module 'React.RCTComponent' before it is required
`

The error when I'm trying to run is using bash:
`	CompileC /Users/[user]/Library/Developer/Xcode/DerivedData/[app]-acyywdzqrwcxjmcgsnxsusgggtux/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-date-picker.build/Objects-normal/x86_64/DatePicker.o /Users/bravebinary/git_repo/ecotrak/[app]/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-date-picker' from project 'Pods')
`
When I test the same project with react native 0.66.4, I see no build error

**Comment by ivanmomchilov9** [comment]
Here the same error, but with different RN version (0.64.3) and expo ejected project.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/48363607/158806423-25fe6f0b-43b6-45d2-a4b2-cc9751979b49.png">

**Comment by technyx-ali-rehman** [comment]
Add 
#import <React/RCTView.h>
to the top of DatePicker.m

This will solve the missing import issue

**Comment by fatlinesofcode** [comment]
same here

**Comment by SergiOnGit** [comment]
Same here

**Comment by Xelaan** [comment]
Same for me

**Comment by henninghall** [comment]
Fixed in v4.2.2
