### ISSUE TITLE
Disable dates that have already passed

### ISSUE THREAD

**Issue by KrisLau** [henninghall/react-native-date-picker#475]
Is there any way  to disable dates that have already passed? If it does not currently exist, I think that it would be a wonderful addition to the library where we could pass in a minimum and maximum date

**Comment by proverbface** [comment]
It seems according to documentation `minimumDate` and `maximumDate` should do the job. But those properties are not doing the job according to the documentation. I would appreciate if that can be fixed.

**Comment by proverbface** [comment]
+1

**Comment by henninghall** [comment]
You can achieve that with`minimumDate={new Date()}`
