### ISSUE TITLE
Android dark theme causes contrast issues

### ISSUE THREAD

**Issue by joediv** [henninghall/react-native-date-picker#476]
**Describe the bug**
The dark mode on the Android modal uses black text and doesn't have contrast. Text color works fine but the button colors ideally are configurable.

![modal](https://user-images.githubusercontent.com/11826814/157101523-9660cf2d-274e-4b0f-8211-026a1749e2d9.png)

**Expected behavior**
Ideally we could force the light theme on Android too or add buttonTextColor as a prop.

I would open up a PR if it was iOS but I'm not familiar enough with android

**Comment by Leeingnyo** [comment]
I disabled a dark theme by changing the `DayNight` app theme to `Light` theme in the `styles.xml`
And button text color are changed by setting `colorAccent` in `styles.xml`

In `android/app/src/main/res/styles.xml`,
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Change DayNight to Light for disable a dark theme -->
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primaryDark</item>
        <item name="colorAccent">@color/primary</item>
        <!-- Change colorAccent for button text color -->
        <item name="colorControlHighlight">@color/secondary</item>
    </style>
</resources>
```

for using `@color/~` reference, you should make a new file `colors.xml` in the same folder.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">[your primary color]</color>
    <color name="primaryDark">[same value]</color>
</resources>
```

btw, It would be good that props are supported, too.

**Comment by henninghall** [comment]
@joediv How does your `styles.xml` look like? 

When I tested this with an empty RN 0.69 project, the styles.xml looks like this:
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    </style>
</resources>
```

And it automatically switched the header/button color when the theme changed.

**Comment by henninghall** [comment]
I've tested this out and the solution is to change the AppTheme to `DayNight` in `styles.xml`. This comes automatically with newer versions of react native. 
```
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
```
