### ISSUE TITLE
cannot find symbol import com.facebook.react.bridge.Dynamic;

### ISSUE THREAD

**Issue by michelquik** [henninghall/react-native-date-picker#479]
after upgrade to "react-native": "0.67.3",
I'm gettign this errors 

Task :react-native-date-picker:compileDebugJavaWithJavac FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

my environment

distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip 

 ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
        supportLibVersion = "27.1.1"
        googlePlayServicesVisionVersion ="+"
        androidXCore= "1.7.0"
    }

**Comment by henninghall** [comment]
Still having this problem?
