### ISSUE TITLE
don't show the true selected date - adding +1 to the selected date automatically

### ISSUE THREAD

**Issue by ahmed-khlifi** [henninghall/react-native-date-picker#489]
**Describe the bug**
When i select a date, the picker add an extra day to the selected value, E.G : 2000-01-20T01:37:00.000Z instead of 2000-01-19T01:37:00.000Z

**Expected behavior**
Give the same date selected in the picker with the exact values

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
```
      <Button title="Open" onPress={() => setOpen(true)}  />
      <DatePicker
        modal
        mode='date'
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
          console.log(date);
        }}
        onCancel={() => {
          setOpen(false)
        }}
      />
    </>
```
```

**Smartphone (please complete the following information):**
 - OS: Android 
 - React Native version "0.67.3"
 - react-native-date-picker version "^4.2.0"

**Comment by henninghall** [comment]
Hi, thanks for reporting this. What time zone are you in? What locale/language are you using?

**Comment by joxelstudios** [comment]
Happening to me too. 

## Typescript
```
<DatePicker
  modal
  open={showDatePicker}
  mode="date"
  locale="en_US"
  date={date ? new Date(date) : new Date()}
  maximumDate={new Date()}
  onConfirm={(date) => {
    console.log(date)
    handleChange('date_of_birth', date.toISOString().split('T')[0])
    setShowDatePicker(false)
  }}
  onCancel={() => {
    setShowDatePicker(false)
  }}
/>
```

## Environment
- OS: iOS
- React Native: 0.67.0
- react-native-date-picker: 4.1.3

**Something I noticed:**
If I removed any variables from the `date` property on the `<DatePicker />` and used `new Date()` instead, the problem goes away. As soon as I add any other logic with variables, it adds an additional day to the selected date. 

![Kapture 2022-04-21 at 15 50 46](https://user-images.githubusercontent.com/36315326/164541600-4786ffd0-74a3-44b9-94f9-fe0320c17796.gif)
