### ISSUE TITLE
OnComfirm automatically turns off modal even if you don't set the open property  

### ISSUE THREAD

**Issue by xjdqq** [henninghall/react-native-date-picker#491]
import React, {useState} from 'react';
import {Button} from 'react-native';
import DatePicker from 'react-native-date-picker';

export default () => {
  const [date, setDate] = useState(new Date());
  const [open, setOpen] = useState(false);

  return (
    <>
      <Button title="Open" onPress={() => setOpen(true)} />
      <DatePicker
        modal
        open={open}
        date={date}
        onConfirm={date => {
          // setOpen(false);
          // setDate(date);
        }}
        onCancel={() => {
          setOpen(false);
        }}
      />
    </>
  );
};
I didn't set the open property, so I still turn off Modal and I can't open Modal the next time

**Comment by henninghall** [comment]
What platform, version of react native and react-native-date-picker are you using?

**Comment by xjdqq** [comment]
> 
i using
"react-native": "0.64.2",
"react-native-date-picker": "^4.1.1",

**Comment by henninghall** [comment]
Thanks, Android or iOS?
