### ISSUE TITLE
android compile problem

### ISSUE THREAD

**Issue by SnowChasm** [henninghall/react-native-date-picker#5]
when i add this to my project,it shows 
Error:(4, 0) Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist
<a href="openFile:/Users/wangchao/developer/react_native/ingsoccer/node_modules/react-native-date-picker-x/android/build.gradle">Open File</a>

i have to edit this file like this:
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"

Now, it work fine.
To be honest, this datepicker is very handsome.

**Comment by henninghall** [comment]
Thanks for reporting! The issue is solved and will be included in the next release, I will try to get it out very soon!
