### ISSUE TITLE
Date picker does not filter dates according to min and max dates

### ISSUE THREAD

**Issue by proverbface** [henninghall/react-native-date-picker#509]
**Describe the bug**
`maximumDate` and `minimumDate` do not filter out default dates. The date picker always shows all dates to be picked from.

**Expected behavior**
I would expect the date picker view to only show dates within the minimum and maximum date.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript

const minimumDate = moment().add(-270, 'days');

const PickerTest = () => {

  const [date, setDate] = useState();

  render = () =>
    <DatePicker
          open={true}
          mode="date"
          date={date}
          minimumDate={minimumDate.toDate()}
          maximumDate={new Date()}
          onDateChange={d => setDate(d)}
        />

}
```

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version 0.65.1
 - react-native-date-picker version ^4.2.1

**Comment by LazyAfternoons** [comment]
Same issue here: 
OS: Android and iOS
React Native version 0.68.1
react-native-date-picker version ^4.2.1

**Comment by henninghall** [comment]
Hi, this is a feature request discussed here: https://github.com/henninghall/react-native-date-picker/discussions/123
