### ISSUE TITLE
Can I disable for a specific time?

### ISSUE THREAD

**Issue by Poovit-B** [henninghall/react-native-date-picker#513]
For example I have 3 arrays of time.
if array[0] select 08:00
array[1],array[2] should not be able to select 08:00

if array[0] select 08:00 and array[1] select 09:00
array[2]should not be able to select 08:00 and 09:00

**Comment by henninghall** [comment]
No unfortunately not, this wont be possible to add due to limitations in UiDatePicker which is used under the hood on iOS
