### ISSUE TITLE
Not working with Managed Expo

### ISSUE THREAD

**Issue by jereztech** [henninghall/react-native-date-picker#514]
**Describe the bug**
Not working with Managed Expo, an error is thrown and no component is displayed.
`TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerManager.openPicker')`

**Smartphone (please complete the following information):**
 - OS: Android/iOS
 - React Native version 0.64.3
 - react-native-date-picker version 4.2.1

**Comment by henninghall** [comment]
See README on how to make it work with expo and custom expo builds.
