### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by shanetierney** [henninghall/react-native-date-picker#516]
**Describe the bug**
Building for Android and getting:
`Could not HEAD 'https://www.jitpack.io/com/henninghall/android/NumberPickerView/1.1.5/NumberPickerView-1.1.5.pom'. Received status code 401 from server: Unauthorized`

**Expected behavior**
Access to the jitpack repository

**To Reproduce**
N/A

**Smartphone (please complete the following information):**
 N/A

**Comment by henninghall** [comment]
I think this was a temporary issue with jitpack.io. If someone is still having this, please let me know and I'll reopen this issue.
