### ISSUE TITLE
Modal not opening in ios.

### ISSUE THREAD

**Issue by RajeevKhati** [henninghall/react-native-date-picker#521]
Even when open prop is true, Modal along with date picker is not opening. After removing "modal" prop from DatePicker, date picker gets showed up. Happening only in iOS.

**Comment by EJJSharpe** [comment]
Do you have any code to show? Your description isn't helpful.
I can tell you now that I've just put the most recent version in my app and this definitely works. I suggest having another look through your code.

**Comment by henninghall** [comment]
Yes we need a reproducible code sample to be able to investigate this.
