### ISSUE TITLE
wrapper backgroundColor not working 

### ISSUE THREAD

**Issue by sahakoushik** [henninghall/react-native-date-picker#522]
I have used a View to wrap up the Datepicker like the code below. But the **backgroundColor** is not applying within the wrapper.
```

 `<View style={{flex:1, backgroundColor:"#fff", marginHorizontal:16}}>
    <DatePicker
 	  mode={"date"}
	  dividerHeight={6} 	  
          fadeToColor={"#fff"}
 	  locale={"en_GB"}
	  androidVariant={"iosClone"}
 	  date={this.state.endDate}
 	  onDateChange={(date)=> this.setState({endDate:date})} />
 </View>`

```

**Comment by henninghall** [comment]
No been able to reproduce this. Can you supply a full working component that has this issue? Android or iOS?

**Comment by Shahzaib114** [comment]
Found solution!!!!

https://github.com/henninghall/react-native-date-picker/issues/583#issuecomment-1360886400
