### ISSUE TITLE
Error: Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by taatiq882** [henninghall/react-native-date-picker#524]
const [date, setDate] = useState(new Date());

**Comment by johnsan96** [comment]
I have this problem too. did you solve it?

**Comment by taatiq882** [comment]
Nop I couldn't solve that. its realy strange because I used the same it in the same maner.

**Comment by henninghall** [comment]
Sounds like you are rendering the date directly without formatting it, something like `<Text>{date}</Text>`. You should format the date before rendering.
