### ISSUE TITLE
Dark mode is bugged on iOS & Android

### ISSUE THREAD

**Issue by AlbinCederblad** [henninghall/react-native-date-picker#527]
**Describe the bug**
Dark mode is bugged. It's black on black text. And there seems to be no way to change the background color nor the title/confirm/cancel text colors.

**Expected behavior**
I expected darkmode to look OK

**To Reproduce**
Simply turn on dark mode on iOS/Android and see for yourself

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version: 0.64.0
 - react-native-date-picker version: 4.2.2

**Comment by AlbinCederblad** [comment]
Workaround (force disable darkmode):

iOS:
Set prop: theme={'light'}

Android:
set: 
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
and:
<item name="android:forceDarkAllowed">false</item>
in styles.xml

**Comment by Sneidon** [comment]
The other workaround is changing textColor manually according to the current theme.

`<DatePicker 
      date={date}
      textColor={dark? "white": "black"}
 />`

**Comment by n-devr** [comment]
I had a similar solution to @Sneidon , just adding some detail around how I was able to determine the currently active theme:

```javascript
// import Appearance from react-native
import { Appearance } from 'react-native';
// determine the color scheme on each render, as the user may change their preferences at any time
<DatePicker textColor={Appearance.getColorScheme() === 'dark' ? '#FFFFFF' : '#000000'}
```

**Comment by KiDeokKim** [comment]
just change color of the text is not perfectly solution..  because modal screen color also black.
so can i change modal style for android?

**Comment by henninghall** [comment]
Fixed in v4.2.4

**Comment by marvelous-ikechi** [comment]
Change the colour of the text depending on the colour of the Modal. For my white modal I use:
<DatePicker textColor={'#000000'} />

**Comment by manishnaruka** [comment]
> Dark mode does not work on Android - the background is white and the text is white. I understand I can set the text to `black` on Android but I want to set the background to dark color in this case since it's dark mode. I'm on version 4.2.6

I am facing the same issue. anyone got solution ?

**Comment by suzhaev** [comment]
> Dark mode does not work on Android - the background is white and the text is white. I understand I can set the text to `black` on Android but I want to set the background to dark color in this case since it's dark mode. I'm on version 4.2.6

same here
