### ISSUE TITLE
bundling failed

### ISSUE THREAD

**Issue by saadsaleem187** [henninghall/react-native-date-picker#53]
I got this below error
"error: bundling failed: Error: While trying to resolve module `react-native-date-picker` from file `/Users/mba/Desktop/office_data/react-native-apps/ExpenseManagementSystem/src/components/screens/AddIncome.js`, the package `/Users/mba/Desktop/office_data/react-native-apps/ExpenseManagementSystem/node_modules/react-native-date-picker/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/mba/Desktop/office_data/react-native-apps/ExpenseManagementSystem/node_modules/react-native-date-picker/index.js`. Indeed, none of these files exist:"
I don't know what's the problem. I can't resolve it. Kindly help me out.

**Comment by henninghall** [comment]
If you browse node_modules/react-native-date-picker manually, do you find the index.js?

**Comment by henninghall** [comment]
Don't manage to reproduce it. Assuming solved due to inactivity. Please let me know if that's not the case.
