### ISSUE TITLE
Plugin crashes an EAS Preview Build but works on development build

### ISSUE THREAD

**Issue by pushparajsamant** [henninghall/react-native-date-picker#531]
**Describe the bug**
When built with eas development profile, the plugin runs well but when built with eas preview it fails to find the DatePicker element and crashes the app. Gives the following error

**Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Expected behavior**
It should be able to access the DatePicker in the eas preview build

**To Reproduce**
eas build --platform android --local --profile preview

Install the app on device and try to access the page with the datepicker

My date picker code
<DatePicker
    modal
    date={dob}
    open={showDatePicker}
    mode="date"
    onConfirm={handleConfirm}
    onCancel={hideDatePicker}
/>
```

**Smartphone (please complete the following information):**
 - OS: Both Android and iOS
 - React Native version 0.68.2
 - react-native-date-picker version 4.2.2

**Comment by pushparajsamant** [comment]
Possible Solution
https://github.com/henninghall/react-native-date-picker/pull/532

**Comment by IngyuTae** [comment]
same issue + 1
