### ISSUE TITLE
please tell me how to change divider color 🔢 

### ISSUE THREAD

**Issue by vuhongson-01** [henninghall/react-native-date-picker#537]
I want to custom DatePicker, everything is ok but the divider is not, although I find solution in StackOverflow it does not work. I want to custom divider color :>>>>

**Comment by henninghall** [comment]
Tried this? https://github.com/henninghall/react-native-date-picker#how-do-i-change-the-divider-color

**Comment by LastStranger** [comment]
> Tried this? https://github.com/henninghall/react-native-date-picker#how-do-i-change-the-divider-color

there is no such section in this link
