### ISSUE TITLE
Datepicker props don't update.

### ISSUE THREAD

**Issue by MagicAce1988** [henninghall/react-native-date-picker#538]
**Describe the bug**
1. If Datepicker is open and you refresh the app the datepicker stays open even if you ask it to close.
2. If you try programatically to close the picker when coming from app background state it does not work, none of the props are getting updated on it.
3. Adding a key that changes to the picker just makes a new picker appear everytime the key changes.

**Comment by henninghall** [comment]
Hi, I cannot reproduce this. Please create a new issue with the proper issue template for me to be able to debug this further.
