### ISSUE TITLE
2 errors: Can not create subdir and invoke virtual method on null object

### ISSUE THREAD

**Issue by emclab** [henninghall/react-native-date-picker#54]
Installed 2.4.0 on react native 0.59.5/react 16.8.3/react navigation 3.9.1 and link successfully. The following error comes up when `react-native run-android`. The same errors happened for subdir `mergeDebugShaders` and `debug-mergeJniLibs`

  > Configure project :react-native-date-picker
  WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
  It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools  /update-dependency-configurations.html

  > Task :react-native-date-picker:mergeDebugJniLibFolders FAILED

  FAILURE: Build failed with an exception.

   * What went wrong:
   Failed to create directory 'C:\D\code\js\emps_app\node_modules\react-native-date-picker  \android\build\intermediates\incremental\mergeDebugJniLibFolders'

   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

   * Get more help at https://help.gradle.org

What I did was to manually create the 3 subdir. and now the render has an error on emulator:

![Capture](https://user-images.githubusercontent.com/946013/57273509-e8f97a00-704c-11e9-8fc6-85f0437a8f09.JPG)

I have no clue about the problem. Thanks for the help.

**Comment by emclab** [comment]
Solved the render error by assigning a value to date in state.

**Comment by henninghall** [comment]
Glad you solved it!
