### ISSUE TITLE
default date not displaying correctly

### ISSUE THREAD

**Issue by dodicandra** [henninghall/react-native-date-picker#540]
**Describe the bug**
default date not displaying correctly (today)

**Expected behavior**
The date displayed must be today

**To Reproduce**

```javascript

const CustomDetePicker = () => {
const [date,setDate] = React.useState(new Date())

return (
    <DatePicker
      androidVariant="iosClone" // same if "nativeAndroid"
      mode="date"
      date={date}
     />
   )
}
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [0.67.4]
 - react-native-date-picker version [4.2.1]

**Screen Capture**
![IMAGE 2022-07-12 6:20:12 PM](https://user-images.githubusercontent.com/48325708/178478440-e8440f38-deeb-4a2d-9f30-49839153194e.jpg)

**let me know if there is a duplicate issue**

**Comment by henninghall** [comment]
This is expected. Only "datetime" mode has the "today" string visible 🙂

**Comment by pushparajsamant** [comment]
@henninghall How difficult is it to make the today string visible for the Date mode. @dodicandra did you find a solution
