### ISSUE TITLE
Can't change the font style and modal's radius

### ISSUE THREAD

**Issue by naimur978** [henninghall/react-native-date-picker#541]
In my app, I'm using a particular font style. But using this package I can't do this. Can you help me out with this?

Again, I want to change the radius of the modal and give shadows around that. How to do that?

**Comment by henninghall** [comment]
Custom font style is not supported due to limitations in UIDatepicker, the underlying component. See this discussion for some workarounds https://github.com/henninghall/react-native-date-picker/discussions/171

If you want a custom modal you will have to do it yourself and use the inline picker.
