### ISSUE TITLE
Unable to change format of date picker day

### ISSUE THREAD

**Issue by Bsingh2697** [henninghall/react-native-date-picker#542]
**Describe the bug**
I'm trying to show dates in DD format but i couldn't find any parameter to set the format.

**Expected behavior**
Want Date in YYYY DD MM format

**To Reproduce**
Example 
           ` <DatePicker
              date={date}
              mode="date"
              onConfirm={setDate}
              onDateChange={date => setDate(date)}
              minimumDate={new Date('1970-01-01')}
              maximumDate={new Date()}
            />`
<img width="293" alt="Screenshot 2022-07-13 at 12 21 10" src="https://user-images.githubusercontent.com/36998578/178722240-486fd93c-c210-4781-9f03-ed48b345d87c.png">
Here I want days as  01, 02, 03... so on
 - OS: iOS
 - React Native version [e.g. 0.68.2]
 - react-native-date-picker version [e.g. 4.2.2]

**Comment by henninghall** [comment]
This is not supported due to limitation of the underlying UIDatePicker.

**Comment by kkkasio** [comment]
> This is not supported due to limitation of the underlying UIDatePicker.

Thank you for your answer, you must believe that on android it is not possible for example to format the date?

for example leave the months in other languages.
