### ISSUE TITLE
Wrong value returned from timepicker

### ISSUE THREAD

**Issue by faridyusman** [henninghall/react-native-date-picker#546]
**Describe the bug**
in mode timepicker, return a different value with the one I picked

**To Reproduce**
```javascript
const FormEditAkun = (_props: any) => {
  const [dateshow, setDateshow] = useState<boolean>(false)
const [data, setData] = useState('')
return (
<DatePicker
        modal
        mode='time'
        theme='light'
        locale='id'
        open={dateshow}
        is24hourSource='locale'
        minuteInterval={10}
        date={new Date()}
        onConfirm={_date => {
            let times = _date.toISOString().substr(11, 5)
          setData(times)
          setDateshow(false)
        }}
        onCancel={() => {
          setDateshow(false)
        }}
      />
)
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [0.66.4]
 - react-native-date-picker version [4.2.2]

**Comment by henninghall** [comment]
The time visible in the picker will be the time in your local timezone. When you use `toISOString()` you will grab the time in the UTC timezone.

**Comment by kigh143** [comment]
Hi,  I was facing the same issue, I dot know yet what is causing it s but this is the quick fix. format the date using moment js.
From the date returned, 

`const trueDateAndTime = moment(date).format();`
