### ISSUE TITLE
Android:sometime onConfirm could not change time from AM to PM or PM to AM.Its take multiple tryings to select AM or PM. 

### ISSUE THREAD

**Issue by ShafqatButt** [henninghall/react-native-date-picker#551]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by ShafqatButt** [comment]
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}

**Comment by ShafqatButt** [comment]
when Using android we select time from datePicker.when select to PM to AM or AM to PM it did not change once it take multiple trying more then once to change from AM to PM or PM to AM.

**Comment by ShafqatButt** [comment]
https://screenrec.com/share/UjRmuAFcpz...This is video link

**Comment by ShafqatButt** [comment]
https://screenrec.com/share/UjRmuAFcpz

**Comment by ShafqatButt** [comment]
import {directionDownIcon} from '@assets/icons';
import CustomInput from '@components/customInput';
import CustomLoading from '@components/customLoading';
import CustomText from '@components/customText';
import Header from '@components/header';
import PrimaryBtn from '@components/primaryBtn';
import Wrapper from '@components/wrapper';
import {RouteProp} from '@react-navigation/native';
import {addCoupon, editCoupon} from '@services/CouponsService';
import {
  getShortTime,
  getTimezoneOffset,
  serverFormattedTime,
  showToast,
} from '@services/HelperService';
import {NewCouponSchema} from '@utils/validations';
import {Formik} from 'formik';
import React, {useState} from 'react';
import DatePicker from 'react-native-date-picker';
import {KeyboardAwareScrollView} from 'react-native-keyboard-aware-scrollview';
import {useSelector} from 'react-redux';
import styles from './styles';
import moment from 'moment';

interface Props {
  navigation: any;
  route: RouteProp<{
    params: {
      update: boolean;
      data: any;
      callback: () => void;
    };
  }>;
}

const defaultDatePicker = {status: false, type: 'startDate'};
const defaultTimePicker = {status: false, type: 'startTime'};

const AddNewCoupon = ({navigation, route}: Props) => {
  const update = route.params?.update;
  const data = route.params?.data;
  const defaultExpiryDateTime = update
    ? new Date(data?.expiration_date_time)
    : new Date();
  const defaultStartDateTime = update
    ? new Date(data?.start_date_time)
    : new Date();
  const [showDatePicker, setShowDatePicker] = useState(defaultDatePicker);
  const [showTimePicker, setShowTimePicker] = useState(defaultTimePicker);

  const initialValues = {
    title: data?.title || '',
    startDate: defaultStartDateTime,
    startTime: defaultStartDateTime,
    expiryDate: defaultExpiryDateTime,
    expiryTime: defaultExpiryDateTime,
    deals: data?.total_no_coupons ? String(data?.total_no_coupons) : '',
    description: data?.description || '',
  };

  const closeDatePicker = () => {
    setShowDatePicker(defaultDatePicker);
  };
  const closeTimePicker = () => {
    setShowTimePicker(defaultTimePicker);
  };

  const submitHandler = (
    {
      title,
      startDate,
      expiryDate,
      startTime,
      expiryTime,
      deals,
      description,
    }: any,
    {setSubmitting}: any,
  ) => {
    let data: any = {
      title,
      start_date: moment(startDate).format('DD-MM-YYYY'),
      expiration_date: moment(expiryDate).format('DD-MM-YYYY'),
      start_time: serverFormattedTime(startTime),
      expiration_time: serverFormattedTime(expiryTime),
      total_no_coupons: deals,
      description,
      type: '1',
    };

    let apiService = addCoupon;
    let message = 'Coupon has been successfully added.';
    if (update) {
      apiService = editCoupon;
      data['coupon_id'] = route.params.data.id;
      message = 'Coupon has been successfully updated.';
    }

    apiService(data)
      .then(({data}: any) => {
        if (data?.status === 200) {
          navigation.goBack();
          route.params.callback();
          showToast('Success', message, true);
        } else {
          showToast('Failed', data?.message, false);
        }
      })
      .catch(err =>
        showToast('Request Failed', err?.response.data?.message, false),
      )
      .finally(() => setSubmitting(false));
  };

  return (
    <Wrapper>
      <>
        <Header title={update ? 'Edit Coupon' : 'Add New Coupon'} />
        <Formik
          initialValues={initialValues}
          onSubmit={submitHandler}
          validationSchema={NewCouponSchema}>
          {({
            values,
            errors,
            touched,
            handleChange,
            handleSubmit,
            isSubmitting,
            setFieldValue,
          }: any) => (
            <>
              <KeyboardAwareScrollView
                showsVerticalScrollIndicator={false}
                keyboardShouldPersistTaps={'always'}>
                <CustomText size={14} style={styles.headingTextContainer}>
                  Enter the coupon details below and it’ll be added to your
                  list.
                </CustomText>
                <CustomInput
                  label={' Deal Title'}
                  placeHolder={'20% off on John’s Meal'}
                  autoCapitalize="none"
                  value={values.title}
                  onChangeText={handleChange('title')}
                  error={touched.title && errors.title ? errors.title : ''}
                />
                <CustomInput
                  label={'Start Date'}
                  placeHolder={'Select Date'}
                  rightIcon={directionDownIcon}
                  onPress={() =>
                    setShowDatePicker({status: true, type: 'startDate'})
                  }
                  editable={false}
                  value={moment(values.startDate).format('DD-MM-YYYY')}
                  error={
                    touched.startDate && errors.startDate
                      ? errors.startDate
                      : ''
                  }
                />
                <CustomInput
                  label={'Expriy Date'}
                  editable={false}
                  placeHolder={'Select Date'}
                  onPress={() =>
                    setShowDatePicker({
                      status: true,
                      type: 'expiryDate',
                    })
                  }
                  rightIcon={directionDownIcon}
                  value={moment(values.expiryDate).format('DD-MM-YYYY')}
                  error={
                    touched.expiryDate && errors.expiryDate
                      ? errors.expiryDate
                      : ''
                  }
                />
                <CustomInput
                  label={'Start Time'}
                  editable={false}
                  onPress={() =>
                    setShowTimePicker({
                      status: true,
                      type: 'startTime',
                    })
                  }
                  placeHolder={'Select Time'}
                  rightIcon={directionDownIcon}
                  value={getShortTime(values.startTime)}
                  error={
                    touched.startTime && errors.startTime
                      ? errors.startTime
                      : ''
                  }
                />

                <CustomInput
                  label={'Expriy Time'}
                  editable={false}
                  placeHolder={'Select Time'}
                  rightIcon={directionDownIcon}
                  onPress={() =>
                    setShowTimePicker({
                      status: true,
                      type: 'expiryTime',
                    })
                  }
                  value={getShortTime(values.expiryTime)}
                  error={
                    touched.expiryTime && errors.expiryTime
                      ? errors.expiryTime
                      : ''
                  }
                />
                <CustomInput
                  label={'Total Deals'}
                  placeHolder={'No of Deals'}
                  onChangeText={handleChange('deals')}
                  value={values.deals}
                  error={touched.deals && errors.deals ? errors.deals : ''}
                />
                <CustomInput
                  label={'Description'}
                  placeHolder={'Write coupon details...'}
                  multiline={true}
                  autoCapitalize="none"
                  value={values.description}
                  onSubmitEditing={handleSubmit}
                  onChangeText={handleChange('description')}
                  error={
                    touched.description && errors.description
                      ? errors.description
                      : ''
                  }
                />
              </KeyboardAwareScrollView>
              <PrimaryBtn
                title={update ? 'Update Details' : 'Add Coupon'}
                onPress={handleSubmit}
              />
              <DatePicker
                modal
                mode="date"
                open={showDatePicker.status}
                date={values[showDatePicker.type]}
                onConfirm={date => {
                  setFieldValue(showDatePicker.type, date);
                  closeDatePicker();
                }}
                onCancel={() => {
                  closeDatePicker();
                }}
              />
              <DatePicker
                modal
                mode={'time'}
                open={showTimePicker.status}
                date={values[showTimePicker.type]}
                is24hourSource={'locale'}
                onConfirm={date => {
                  setFieldValue(showTimePicker.type, date);
                  closeTimePicker();
                }}
                onCancel={closeTimePicker}
              />

              <CustomLoading visible={isSubmitting} />
            </>
          )}
        </Formik>
      </>
    </Wrapper>
  );
};

export default AddNewCoupon;

**Comment by henninghall** [comment]
Thanks, how does your `setFieldValue` function looks like?
