### ISSUE TITLE
Light mode change from dark mode is broken

### ISSUE THREAD

**Issue by BrandonMA** [henninghall/react-native-date-picker#552]
**Describe the bug**
If you enable dark mode, open/close the modal, then go back to light mode and open the modal again, the text is black but the background is still dark gray so there's not enough contrast.

In a recent update I saw that dark mode support was added and the text is working as expected, so I assume the callback handling the theme change should also handle the background color.

Edit:
If you close the app and open it again, it works as expected

**Expected behavior**

**To Reproduce**

```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
        modal
        open={true}
        date={new Date()}
      />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [0.66.0]
 - react-native-date-picker version [4.2.5]

**Comment by henninghall** [comment]
I've tried but I don't manage to reproduce this issue. What android version are you using when seeing this issue?
