### ISSUE TITLE
Feature request: disable / enable hook

### ISSUE THREAD

**Issue by rishabmahesh** [henninghall/react-native-date-picker#553]
It would be great if there would be a parameter which can disable / enable the date picker. 

My specific requirement: Once user enters Date of Birth, they should not be able to change it. This requires above requested disabled / enabled feature

**Comment by henninghall** [comment]
I think I would be a bit weird ux if the user sees a picker they can't interact with. I suggest that you show a date string instead of a date picker if it is supposed to be disabled.
