### ISSUE TITLE
Light theme prop not working with iOS

### ISSUE THREAD

**Issue by vxm5091** [henninghall/react-native-date-picker#554]
**Describe the bug**
When setting the `theme` prop to `light`, I'm still seeing a dark background with black text (see screenshot). My only solution is to set text to white but that's not a good approach because I'm risking certain instances opening the modal with the light background and white text. 

FYI I'm testing this in Metro, not sure if that has an impact. 

**Expected behavior**
For the modal background to be light 

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
        theme="light"
        modal={true}
        open={openPickerModal}
        date={date}
        mode="date"
        onConfirm={(newDate) => onDateConfirm(newDate, field)}
        onCancel={onDatePickerCancel}
        locale="en-US"
/>
```

**Smartphone:**
 - OS: iOS
 - React Native version 0.66.1
 - react-native-date-picker version 4.2.5

![IMG_C1C10163210E-1](https://user-images.githubusercontent.com/57078583/183535330-7cdcfd9e-5f11-48e9-b5c2-6556c358dc36.jpeg)

**Comment by henninghall** [comment]
@vxm5091  I've tried but I don't manage to reproduce this issue.

What iOS version are you using? 

Also, would help a lot if you can provide a runnable repo where this bug is reproduced. Thanks!
