### ISSUE TITLE
Minute and second picker

### ISSUE THREAD

**Issue by arunabhverma** [henninghall/react-native-date-picker#557]
Hi React Native Date Picker Dev

I need one more feature in this beautiful date picker, 
A minute and second picker same as ios have.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/59590144/184804364-c75fff6f-545c-47a4-bb35-c10fe57c3dd4.png">

If I can achieve this with the same react native date picker version then please tell me how to implement it in my code.

Now I am using react native date picker with mode "time" and get this type modal with only time with formate of Hours and Minutes.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/59590144/184804630-2e8e50c2-9044-44f9-8a30-c646dab00183.png">

**Comment by henninghall** [comment]
Hi, thats looks like the countdown mode and we are tracking that feature request here: https://github.com/henninghall/react-native-date-picker/discussions/199 

Please upvote if you want it! 👍
