### ISSUE TITLE
Is it possible to translate the text that comes by default? "Select Date" and the "Confirm" and "Cancel" buttons

### ISSUE THREAD

**Issue by georgeMorales** [henninghall/react-native-date-picker#563]
**Describe the bug**
Is it possible to translate the text that comes by default?
"Select Date" and the "Confirm" and "Cancel" buttons

**Comment by georgeMorales** [comment]
title, confirmText, and cancelText props

**Comment by georgeMorales** [comment]
title, confirmText, and cancelText props

**Comment by vinamrahalgar** [comment]
cancelText does it work for iOS as well?
