### ISSUE TITLE
Text not visible on dark mode on Android with enforced Light theme

### ISSUE THREAD

**Issue by vkourtis** [henninghall/react-native-date-picker#568]
**Describe the bug**
In our app we avoided dealing with dark theme (for the time being). On android this is achieved by using `Theme.AppCompat.Light.NoActionBar` in our styles.xml. This forces the background of all alerts to be white.

`DatePicker` seems to use an alert to show the date/time picker but somehow the enforced light theme is not respected, so when dark mode is enabled on the device, the text color turns to white, which makes it "invisible" on top of the white alert background.

This happens when DatePicker's theme is undefined (I think defaults to `auto`). 
Changing the theme to `light` fixes the issue.

<img src="https://user-images.githubusercontent.com/783627/194020452-1c18e70c-0e62-4ed1-bb9a-2b39c9034d6a.jpg" height=200/>

**Expected behavior**
Since we're using a light theme, the text color should stay dark.

**To Reproduce**
- Use a modal `DatePicker` that pops up through an alert. Here's what we use:
```
<DatePicker
      modal
      androidVariant={"iosClone"}
      mode="datetime"
      open={open}
      date={date}
      onConfirm={(date) => {
        setOpen(false)
        setDate(date)
        setValue(date.getTime())
      }}
      onCancel={() => {
        setOpen(false)
      }}
    />
```
- Build for Android with a Light theme enforced. In our case we use:
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:spinnerDropDownItemStyle">@style/SpinnerDropDownItem</item>
        <item name="android:textColor">#808080</item>
        <item name="android:textSize">20sp</item>
        <item name="android:fontFamily">sans-serif</item>
        <item name="android:paddingLeft">0dp</item>
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>
    <style name="SpinnerDropDownItem" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:padding">8dp</item>
    </style>
</resources>
```

**Smartphone:**
 - OS: Android
 - React Native version: 0.70.1
 - react-native-date-picker version: 4.2.5

**Comment by vkourtis** [comment]
@diegomichell thank you! That's exactly what I did and confirming that it works. 

Though, I believe it's possible that there's a better handling for this. e.g. using `Theme.AppCompat.Light.NoActionBar` doesn't break the standard alerts when phone is in dark mode.

I understand this might be a complicated issue to solve and don't have a good suggestion for the time being.

**Comment by linuxuser07** [comment]
If you are still having the issue I had to this fix for mine 
` <DatePicker
        modal
        textColor={Platform.OS === 'android' ? 'black' : ''}
/>
`

**Comment by iway1** [comment]
would be cool if the `themeColor` prop wasn't marked as `iOS only` (seems to work on android?)
