### ISSUE TITLE
South Korea's preference in date display

### ISSUE THREAD

**Issue by BKJang** [henninghall/react-native-date-picker#57]
Hello, I'm BKJang of South Korea.

Thanks to your library, I was able to get more productivity on my project.
but, the South Korea preference has not been applied in the date display.
So I needed to make some personal modifications in the process during the project.

I would like to make corrections and contributions in this part of your library. Is it possible?

If you let me, I want to make PR in this library.

Thanks!

**Comment by henninghall** [comment]
Hi, that sounds great! PR's are very welcome! Please let me know if there is anything I can help you with, if you get stuck or having troubles understanding the codebase.

**Comment by BKJang** [comment]
Thank you. I will make PR soon. If I need about your codebase I will comment in this issue or on the PR. Please join in the review :)

**Comment by henninghall** [comment]
Of course! It sounds like it could be related to this PR https://github.com/henninghall/react-native-date-picker/pull/55

**Comment by BKJang** [comment]
I made PR about this issue. Please check! :) https://github.com/henninghall/react-native-date-picker/pull/58

**Comment by henninghall** [comment]
Great, PR merged!
