### ISSUE TITLE
MinuteInterval wrong rounding

### ISSUE THREAD

**Issue by SergueyPutilin** [henninghall/react-native-date-picker#570]
**Describe the bug**
When using a minuteInterval of for example `10` and the current time is 15:57, the picker displays 15:00

**Expected behavior**
The rounding should be floored instead of ceiled e.g. the time in the picker should be 15:50 instead of 15:00. Now, if you'd want to select the "current time", it basically goes back an hour.

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version 0.63.4
 - react-native-date-picker version 4.2.5

**Comment by henninghall** [comment]
Thanks for reporting this! a fix has been released in `4.2.12`.
