### ISSUE TITLE
Change Font Size in react-native-date-picker

### ISSUE THREAD

**Issue by emre-sozen** [henninghall/react-native-date-picker#572]
I want to change font-size in opened modal of react-native-date-picker.

<DatePicker 
 modal 
 open={open} 
 date={date} 
 mode={'date'}
 title="Choose Date"
 cancelText="Back"
 confirmText="Confirm"
 onConfirm={(date) => {
 setOpen(false)
 setBirthdate(date)
 setDate(date)
}}
 onCancel={() => {
  setOpen(false)
}}
/>

**Comment by henninghall** [comment]
https://github.com/henninghall/react-native-date-picker#font-size
