### ISSUE TITLE
When I open the modal, it crashes and I get a "TypeError: null is not an object" RenderError

### ISSUE THREAD

**Issue by eatanga-git** [henninghall/react-native-date-picker#575]
**Describe the bug**
I installed the package and used the starter modal example as shown in the main page.
https://github.com/henninghall/react-native-date-picker#example-1-modal

When I press "Open" to open the modal, I get a Render error that says 
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')
![image](https://user-images.githubusercontent.com/55466881/197270694-f0a6d15a-531c-4e82-aef3-19e099a9e020.png)

I was expecting it to load normally, similar to what is on the example page.

  
<img width="234" alt="datetime-mode-android" src="https://user-images.githubusercontent.com/55466881/197271715-c629375c-1e55-4037-a2ac-a8717fb3f262.png">

Here's my code. It's basically what was in the example.
```javascript
function DatePickerTest(){
  const [date, setDate] = useState(new Date())
  const [open, setOpen] = useState(false)

  return (
    <>
      <Button title="Open" onPress={() => setOpen(true)} />
      <DatePicker
        modal={true}
        mode="date"
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
        }}
        onCancel={() => {
          setOpen(false)
        }}
      />
    </>
  )

}
```
 
 - OS: [Android or iOS]
 - Expo
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by rafavalerio** [comment]
As per README file:

❌ This library can't be used in the "Expo Go" app because it [requires custom native code](https://docs.expo.dev/workflow/customizing/).

So you will need to pack it and generate a test version first

**Comment by eatanga-git** [comment]
> As per README file:
> 
> ❌ This library can't be used in the "Expo Go" app because it [requires custom native code](https://docs.expo.dev/workflow/customizing/).
> 
> So you will need to pack it and generate a test version first

Thank you. If I generate a test version, does that require me to eject from Expo? Or will it still build as it normally would?

**Comment by RicholeYu** [comment]
expo is not support nativecode, but you can eject and use react-native to run

expo eject
npx react-native start
npx react-native run-ios

**Comment by josiahconrad** [comment]
I don't believe you have to eject projects anymore if you don't want to, so long as you create development builds. You just can't use Expo Go for everything.

Get your project setup to run npx expo run:android or npx expo run:ios and you should be good to go.

**Comment by mwaqarshahid** [comment]
I am using react-native-cli but still it is giving me the same error of "TypeError: null is not an object".

```
"react": "17.0.2",
"react-native": "0.67.3",
"react-native-date-picker": "^4.2.6"
```

**Comment by rafaelgtraverso** [comment]
Hi, what would be the custom native code required to make this package work on expo go?

**Comment by eatanga-git** [comment]
> I don't believe you have to eject projects anymore if you don't want to, so long as you create development builds. You just can't use Expo Go for everything.
> 
> Get your project setup to run `npx expo run:android` or `npx expo run:ios` and you should be good to go. If you want to run it on a device, run either of the commands above with --device: `npx expo run:android --device` and it should give you a prompt in the terminal to select what to run it on. You need to have your device connected to your pc by USB though.

Thank you, yes, this applies. Running an Expo dev build helped solve this.
