### ISSUE TITLE
datetime picker no display

### ISSUE THREAD

**Issue by VeoScript** [henninghall/react-native-date-picker#578]
**Describe the bug**
I am facing this kind of issue which is there is no display in DateTime Picker Modal. I am using Samsung S10+ Android device.

I tested it on other android devices and it's okay.

**Expected behavior**
![image](https://user-images.githubusercontent.com/26340308/199700284-73c25d2e-a8a4-4343-98c5-e5fbcb8e1423.png)

**To Reproduce**
I put a custom font on it but it's still the same 
> I put a custom font on it but it's still the same

![image](https://user-images.githubusercontent.com/26340308/199699273-ec56a031-1130-4c18-b120-66c9360cfe92.png)

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version - [^0.64.2]
 - react-native-date-picker version - [^4.2.5]

**Comment by ThanhNam20** [comment]
Hi, I'm facing with this issue two, any update ?

**Comment by VeoScript** [comment]
@ThanhNam20 try to add **textColor** and add `theme='light'` to **DatePicker**
