### ISSUE TITLE
Can only see dates in the past

### ISSUE THREAD

**Issue by marcato15** [henninghall/react-native-date-picker#579]
**Describe the bug**
I have a very plain implementation of date picker. However, on iOS I can only see dates/times in the past. 

**Expected behavior**
When I set a minimum date I should see all future dates as options and all previous dates either removed or at least disabled. Instead I only see previous days as disabled but future days (including today) are all blank.

![IMG_6625](https://user-images.githubusercontent.com/413567/200591331-bac7e865-8bfe-45fb-96d5-d43335fe2194.jpg)

**To Reproduce**

```javascript
  import DatePicker from "react-native-date-picker";

   const [date, setDate] = useState(new Date());
   
    return (
           <DatePicker date={date} onDateChange={setDate} minimumDate={new Date()} />
   );
```

**Smartphone (please complete the following information):**
 - OS: iOS 16.1
 - React Native version 0.69.5
 - react-native-date-picker version 4.2.6

**Comment by daveadapptor** [comment]
Seems to be that this is ony an issue on devices that have Dark Mode enabled.  Also setting the textColour to black seems to fix it. @marcato15

**Comment by marcato15** [comment]
Thanks. That did the trick.
