### ISSUE TITLE
There is no way to disable future dates(year, month & date)

### ISSUE THREAD

**Issue by leulseged3** [henninghall/react-native-date-picker#580]
**Describe the bug**
Even though there is a prop called "maximumDate", it's only capable of prevent rendering next years after the maximum date.

**Expected behavior**
When a date prop is passed to the "maximumDate" prop, it should not render years, months and days after specified date in the prop.

**To Reproduce**
```javascript
  import DatePicker from "react-native-date-picker";

  const [date, setDate] = useState(new Date());

  return (
         <DatePicker 
           date={date} 
           onConfirm={(date) => setDate(date)}
           maximumDate={new Date()}
           mode="date"
         />
     );
```
![issue_date_picker](https://user-images.githubusercontent.com/34774344/201739794-c54a7aad-b472-4166-bcd7-bc32fd7c2d62.png)

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.68.2
 - react-native-date-picker version 4.2.6

**Comment by christopher-18** [comment]
facing same issue

**Comment by ghyath5** [comment]
Same here !!!!

**Comment by Jamal-ReachFirst** [comment]
Same here

**Comment by guilhermerera** [comment]
Same here. It happens with the `minumumDate` prop as well.

**Comment by henninghall** [comment]
This feature request is discussed here https://github.com/henninghall/react-native-date-picker/discussions/123
