### ISSUE TITLE
Incorrect Date returned in onConfirm((date) => {}) every time user opens the modal

### ISSUE THREAD

**Issue by vthunetcompany** [henninghall/react-native-date-picker#581]
**Describe the bug**
I get different `Date` every time I open the modal and confirm, by exactly `timezone` hours from the previous modal launch.
**Expected behavior**
I get that exact `Date` every time I open and confirm the date I selected in the picker modal. 

**To Reproduce**
1. Open the picker
2. Pick any date
3. Confirm the picker => still correct
4. Open the picker again
5. Not changing anything, confirm the picker => deviates by my `timezone` hours
6. Repeating this til it reaches the next (or previous) day and the date changes entirely. 

Your most basic boilerplate code:
```javascript
const [date, setDate] = useState(new Date());
const [openDatePicker, setOpenDatePicker] = useState(false);

<DatePicker
          modal
          open={openDatePicker}
          date={date}
          onConfirm={(date) => {
            setOpenDatePicker(false);

            console.log(date);  // this has already returned incorrect result here
            setDate(date);  // just saving the date we selected so it remembers the next time we launch the modal
          }}
          onCancel={() => {
            setOpenDatePicker(false);
          }}
          mode={'date'}
          theme={'light'}
        />
      </View>
```

**Smartphone (please complete the following information):**
 - OS: both Android and iOS, on real devices and simulators/emulators.
 - React Native version: **0.63.5**.
 - react-native-date-picker version: 4.3.1.

**Comment by henninghall** [comment]
I am not able to reproduce this. It sounds like a local issue since this would have been widely reported if this was a general one.

Does it still happen if you turn off debugging? (debugging the date with for instance an alert instead). I suspect it might be caused by some timezone difference between your debugging machine and the simulator. 

Also, what version of the library are you using? 4.3.1 doesn't exist

**Comment by henninghall** [comment]
If someone are still having this, please try with latest version and let me know if the issue still exists.

**Comment by jemilehin** [comment]
recently faced this same problem when testing on ios. it works fine on android but on ios, the mode=time each  time a user changes the time picker it changes the date that was already picked.
