### ISSUE TITLE
using ltr language on device that his system language is rtl

### ISSUE THREAD

**Issue by HodayaGruz** [henninghall/react-native-date-picker#582]
**Describe the bug**
in my app we are support rtl & ltr translations, when i put in the "locale" prop the language the text is change,
but on android since im using modal, the position of the buttons and titles is not change, 
and for example on my device (system language rtl) i choose in my app english so the translations are good but the text is stuck to the right.
![image](https://user-images.githubusercontent.com/44493583/204238743-f15a956d-96df-4f6b-ab31-ce02a23e88e8.png)

**Comment by henninghall** [comment]
This is intended, the system setting will control RTL config  in the picker.
