### ISSUE TITLE
Changes on styles.xml does not have any effect

### ISSUE THREAD

**Issue by somnathPrasad** [henninghall/react-native-date-picker#583]
I put this code in the styles.xml file

<style name="DatePickerTheme" parent="DatePickerBaseTheme">
    <item name="android:colorControlNormal">#dd00ff</item>
  </style>

but this does not change the border color or any color

PS: i am using expo

<DatePickerPackage textColor="#000" className="text-black" date={date} onDateChange={onDateChange} mode="date" />

styles.xml file
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:editTextStyle">@style/ResetEditText</item>
    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
  </style>
  <style name="ResetEditText" parent="@android:style/Widget.EditText">
    <item name="android:padding">0dp</item>
    <item name="android:textColorHint">#c8c8c8</item>
    <item name="android:textColor">@android:color/black</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
  </style>
  <style name="DatePickerTheme" parent="DatePickerBaseTheme">
    <item name="android:colorControlNormal">#dd00ff</item>
  </style>
</resources>

**Comment by RafaelMassula** [comment]
Hello @somnathPrasad 
try access ...\android\app\src\main\res\values\styles.xml
 `<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>
    <style name="DatePickerTheme" parent="DatePickerBaseTheme">
        <item name="android:colorControlNormal">#14af64</item>
         <item name="colorAccent">#14af64</item>
    </style>

</resources>`

uninstall the app in device and build again.

**Comment by Shahzaib114** [comment]
Hi Everyone, just remove modal property from given example, and put this code in <Modal> tag. everything will work
 <DatePicker
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
        }}
        onCancel={() => {
          setOpen(false)
        }}
      />

**Comment by henninghall** [comment]
Use v5 to avoid needing xml changes for this
