### ISSUE TITLE
Week day picker

### ISSUE THREAD

**Issue by Hostname47** [henninghall/react-native-date-picker#586]
First of all, I want to thank anyone contributed to this amazing package and It really helps me with many applications. Today I came across a situation where I have an event scheduled at a specific day of the week, and I have an option to change only the day of the event.

I think it will be much helpful if that package offer a mode='day' to display a picker where I can change only the day of the week.

**Comment by henninghall** [comment]
This will unfortunately not be supported due to limitations in UIDatePicker.
