### ISSUE TITLE
The future date from today is not displayed.

### ISSUE THREAD

**Issue by littlehongkong** [henninghall/react-native-date-picker#589]
**Describe the bug**
android notes
It's also an iPhone X simulator.
LG phone too

However, iPhone 7, iPhone 8, and some Galaxy devices do not look like the attached image,,
**Expected behavior**
I also uploaded the module version and it is the same
The original module version was slightly lower

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

    const getDefaultDate = () => {
        const today = new Date()
        const hour = defaultHour()
        const min = defaultMin()
    
        return new Date(today.getFullYear(), today.getMonth(), today.getDate(), hour, min)
      }
    
      const onDateChange = (selectDate: Date) => {
        const today = new Date()
    
        if (today > selectDate) {
          getDefaultDate()
          return
        }
    
        setDate(selectDate)
        setReservationDate(moment(selectDate).format('yyyy-MM-DD HH:mm'))
      }

  render = () =>
    <DatePicker
            date={new Date()}
            onDateChange={onDateChange}
            minuteInterval={10}
            style={{
              width: width,
            }}
            minimumDate={getDefaultDate()}
            maximumDate={moment(getDefaultDate()).add(1, 'years').toDate()}
            androidVariant={'iosClone'}
            locale={'ko_KR'}
          />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS] iOS
 - React Native version [e.g. 0.59.4] 0.67.3
 - react-native-date-picker version [e.g. 2.5.1] 4.2.6

![image](https://user-images.githubusercontent.com/11766241/209062169-7abd1e5a-438c-424f-8667-0ef906ab0b7e.png)

**Comment by henninghall** [comment]
This is probably due to dark mode. Try setting `textColor='black'`

**Comment by majirosstefan** [comment]
Could you add it into Readme, please ? or maybe even change default value of _textColor_ prop to "black" ?
