### ISSUE TITLE
invariant violation: require native component

### ISSUE THREAD

**Issue by craigcosmo** [henninghall/react-native-date-picker#59]
Just doing the basic sample code on the doc page, I got this error

<img width="150" alt="Screen Shot 2019-05-24 at 9 18 52 AM" src="https://user-images.githubusercontent.com/538657/58298289-2740b880-7e05-11e9-8337-bf779b8c28e3.png">

I'm using react native expo. could it be the reason ?

**Comment by craigcosmo** [comment]
some people got the s

**Comment by henninghall** [comment]
There is now a [feature request you can upvote 👍](https://expo.canny.io/feature-requests/p/support-react-native-date-picker) if you still are interested in using react-native-date-picker with expo!
