### ISSUE TITLE
Cannot set the input date value with appium and webdriver.io

### ISSUE THREAD

**Issue by kopax-polyconseil** [henninghall/react-native-date-picker#593]
**Describe the bug**

There is no input, thus this package cannot be tested with uiautomator2 xcuitest, through appium and webdriver.io

**Expected behavior**

We expect to be able to set the input date value in e2e testing

**To Reproduce**

State is stored not as an input value, but in a state, causing the impossibility to set it without gesture

```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android  and iOS
 - React Native version : 0.68.5
 - react-native-date-picker version : 4.2.2

**Comment by henninghall** [comment]
Hi, what do you mean by "input value"?

If a real user must set the date by a gesture, shouldn't that be the case for e2e runner as well?
