### ISSUE TITLE
Date type

### ISSUE THREAD

**Issue by ENGR-MANSOOR** [henninghall/react-native-date-picker#595]
**Describe the bug**

**Expected behavior**

**To Reproduce**
 <Button title="Datum" onPress={() => setOpen(true)} />
        <DatePicker
          modal
          mode={'date'}
          theme={'light'}
          open={open}
          date={date}
          onConfirm={(date) => {
            setOpen(false)
            setDate(date)
          }}
          onCancel={() => {
            setOpen(false)
          }}
        />
```

mode date is not producing only date without Time, i have set mode  date but not worked

**Comment by henninghall** [comment]
This is expected.
