### ISSUE TITLE
when I pass prop mode='time 'then how we get time from date and set into date picker react-native

### ISSUE THREAD

**Issue by MuhammadKashifAslam** [henninghall/react-native-date-picker#596]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
This question is related to js Date. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
