### ISSUE TITLE
Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.     com.facebook.react.bridge.ReactContext.getJSModule

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [henninghall/react-native-date-picker#600]
**Describe the bug**

java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
    com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:158)
    com.henninghall.date_picker.Emitter.eventEmitter(Emitter.java:15)
    com.henninghall.date_picker.Emitter.onDateChange(Emitter.java:27)
    com.henninghall.date_picker.ui.WheelChangeListenerImpl.onChange(WheelChangeListenerImpl.java:65)
    com.henninghall.date_picker.wheelFunctions.AddOnChangeListener$1.onValueChange(AddOnChangeListener.java:22)
    com.henninghall.date_picker.pickers.IosClone$2.onValueChange(IosClone.java:77)
    cn.carbswang.android.numberpickerview.library.NumberPickerView.respondPickedValueChanged(NumberPickerView.java:671)
    cn.carbswang.android.numberpickerview.library.NumberPickerView$2.handleMessage(NumberPickerView.java:408)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loop(Looper.java:257)
    android.app.ActivityThread.main(ActivityThread.java:8355)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Expected behavior**
This crash should not be there

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version ["0.68.5"]
 - react-native-date-picker version [ "4.2.6"]

**Comment by henninghall** [comment]
Please explain how to reproduce this and I'll reopen this.
