### ISSUE TITLE
DatePicker onDateChange returning wrong time

### ISSUE THREAD

**Issue by rajeshmarotu** [henninghall/react-native-date-picker#607]
**Describe the bug**
While trying to select a date, onDateChange method is returning UTC time which is different date from the selected one.

TimeZone my device is in: Asia/Calcutta (GMT+05:30) India Standard Time
Date Time when I've tried: 14 Feb 2023 02:08 AM
Date I've selected from DatePicker: 16 Feb 2023
Date Time that is getting returned: 2023-02-15T20:36:00.000Z

**Expected behavior**
Selected date and returned should be same.
Returned date should be 16 Feb 2023 instead of 15 Feb 2023

**To Reproduce**
Add example code that reproduces the behavior.

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.70.5]
 - react-native-date-picker version [e.g. 4.2.6]

https://user-images.githubusercontent.com/31095629/218570322-d355c703-2b7d-4a36-b19c-f1e380b536a1.mp4

**Comment by henninghall** [comment]
This is expected, the returned value is a js date object. Format it as you prefer before displaying it.

**Comment by jrsarath** [comment]
> Returned date should be 16 Feb 2023 instead of 15 Feb 2023

Sorry but how this is expected ? its returning date that's being offset by 1 day. formatting it how we want is fine, but returning 1 day offset is correct ?

**Comment by huytdps13400** [comment]
So what format do I need to use? Can you help me with that? @henninghall
