### ISSUE TITLE
Can't change buttons color on Android dark mode

### ISSUE THREAD

**Issue by Fouppy** [henninghall/react-native-date-picker#608]
**Describe the bug**
Hi, I applied changes in styles.xml to set the buttons white when using the lib in dark mode. Changes are not applied (tested with divider color too, this one works). Setting `textColor` prop doesn't help either.

Here's my `android/app/src/main/res/values/styles.xml`:
```xml
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:editTextStyle">@style/ResetEditText</item>
    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="android:windowBackground">@color/activityBackground</item>
    <item name="colorAccent">#ffffff</item>
  </style>
  <style name="ResetEditText" parent="@android:style/Widget.EditText">
    <item name="android:padding">0dp</item>
    <item name="android:textColorHint">#c8c8c8</item>
    <item name="android:textColor">@android:color/black</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
  </style>
</resources>
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version: 0.70.5
 - react-native-date-picker version: 4.2.8

**Comment by Fouppy** [comment]
Yes, to no avail unfortunately.

**Comment by manoharglm** [comment]
Changing `Theme.MaterialComponents.Light.NoActionBar` to `Theme.MaterialComponents.NoActionBar` fixed the issue for me

**Comment by henninghall** [comment]
@Fouppy if you still have this issue, please provide an minimal repo where this is reproduced and I can have a look at it!

**Comment by keshavsharma0712** [comment]
Hi @henninghall still facing this issue tried 
 <item name="colorAccent">#ffffff</item> but no success

**Comment by esalaza** [comment]
Hi, this is how it looks for me on `4.2.14` (sim and device) with a "default example" and dark mode.

```
    <DatePicker
      modal
      open={isOpen}
      date={date}
      onConfirm={onConfirm}
      onCancel={onCancel}
      maximumDate={maximumDate}
      mode="date"
      title={null}
    />
```

<img width="477" alt="image" src="https://github.com/henninghall/react-native-date-picker/assets/2491379/c3ca75c2-00c4-4841-a072-2b7d1f71b9ae">

Thank you.

**Comment by mieradi** [comment]
@esalaza Facing the same issue

**Comment by brandon-austin-lark** [comment]
+1 same issue for me

**Comment by sangayt1997** [comment]
+1
