### ISSUE TITLE
Android: maximumDate and minimumDate problem

### ISSUE THREAD

**Issue by maksim-tolo** [henninghall/react-native-date-picker#61]
Hi!

After adding the maximumDate prop, I'm getting the following error on Android:
`mMaxValue - mMinValue + 1 should not be greater than mDisplayedValues.length, now ((mMaxValue - mMinValue + 1) is 1 newDisplayedValues.length is 0, you need to set MaxValue and MinValue before setDisplayedValues(String[])`.
Looks like a problem with native code because adding maximumDate prop on IOS works fine.

Thanks.

**Comment by henninghall** [comment]
Hi! I have tried to reproduce this issue but I don't manage to. Would be great if you can supply a full example of how to reproduce the issue. I would like to confirm the bug before merging the PR. Many thanks looking into this!

**Comment by maksim-tolo** [comment]
Try setting `maximumDate` to a date earlier than the current date.
For example `maximumDate={new Date(Date.now() - 1000000)}`

**Comment by henninghall** [comment]
Thanks, now I understand the issue and managed to reproduce it!

**Comment by henninghall** [comment]
Released in version `2.4.2`

**Comment by filipef101** [comment]
@henninghall When passing a maximumDate and minimumDate on Android it takes a lot of time to open the picker

**Comment by henninghall** [comment]
@filipef101 Which dates are you using? You definitely shouldnt need to use a span of more than a couple of months or so. If that's the case you are probably using the wrong mode or approach to pick a date and will lead to bad user experience. (the user should not need to scroll that much in the picker)
