### ISSUE TITLE
Hour on the Datetimepicker does not roll over to the next date when a user scrolls past 11:59 PM on the hours and minutes scrollers

### ISSUE THREAD

**Issue by Austin-Guo** [henninghall/react-native-date-picker#615]
Hi,

I am a UT Austin student building an app with some of my friends. Our app is used locally and have around 1000 users. We are using specifically the Datetimepicker in our app. 
Many of our users seem to expect the date to change to the next day when they scroll past 12:00 AM (ex. scrolling the hour from 11 to 12 when the time is 11:45 PM), as that is intuitive to them. They had reported that as a bug for around 40 times by now. 
Would it be possible for you to add this feature to the package? I believe it would make the package even better : )

Also, another feature I would recommend is making it so that when a user scrolls from 59 to 00 on the minutes category, the hours would increase by 1. With those two features added, the package should consistently support use cases in which a user wishes to scroll all the way on hours and minutes to the next day, which is decently likely when a user is posting late in the evening. 

Thanks,
Austin Guo

**Comment by henninghall** [comment]
Hi, is this feature missing on both Android and iOS?

**Comment by Austin-Guo** [comment]
I'm not sure to be honest. Our app is pretty new and only supports iOS at this moment, so we never had a chance to test the feature with android. 
It is missing on iOS though.
