### ISSUE TITLE
Year missing using mode="datetime"

### ISSUE THREAD

**Issue by Jamal-ReachFirst** [henninghall/react-native-date-picker#616]
**Describe the bug**
How can i change year using `datetime`

**Expected behavior**
I want to change the year which is missing in `datetime` mode

**To Reproduce**

```
<DatePicker
      modal
      open={true}
      date={date}
      mode="datetime"
  />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [latest]
 - react-native-date-picker [4.2.9]

**Comment by henninghall** [comment]
It is not possible, you would need to use different pickers for that.

**Comment by mlhtnc** [comment]
This is sad :(
