### ISSUE TITLE
No implementation for the new Fabric Renderer?

### ISSUE THREAD

**Issue by FelixBaum** [henninghall/react-native-date-picker#618]
I created a new `react-native` app with the new architecture and the Fabric renderer enabled.
After installing this module and adding it to a screen, I get a red space with the prompt: `Unimplemented component: <RNDatePicker>`. 

Is a implementation for the new architecture planned? If not, can someone explain, what it would take to convert it for the new arch?

Thank you for the great date picker! Would love to use this one in my new app 🙏

**Comment by henninghall** [comment]
You are right, the new architecture is unfortunately not supported yet. I’ve looked at it briefly but haven’t been able to get the time in. I estimate it will take 10-40 hours to complete. If you want to help out with converting either the android or iOS part, or sponsoring the work it would be very appreciated, just let me know 🙏

**Comment by zhenguet** [comment]
@henninghall I hope you will complete it as soon as possible

**Comment by efstathiosntonas** [comment]
@henninghall Hi, are there any updates on this one? Thanks!

**Comment by annguyen-iosdev** [comment]
Hi guys, following this update. Thanks.

**Comment by henninghall** [comment]
Hi guys, here is an update!

The work on this has been started. You can follow the progress here: https://github.com/henninghall/react-native-date-picker/pull/678

Currently the iOS inline picker is migrated. If you're are using the inline picker in your project, I would appreciate help with testing it out. Install it by `yarn add react-native-date-picker@alpha` etc. it will only compile with the new architecture enabled at the moment. Please let me know how it worked for you by adding a comment in this thread, thanks!

**Comment by henninghall** [comment]
The iOS modal is now migrated as well

**Comment by henninghall** [comment]
The work on supporting the new architecture is completed! It is released in v4.3.0. Thanks for Nordic Brain Tech for partly sponsoring the migration.
