### ISSUE TITLE
The app references non-public selectors setHighlightsToday

### ISSUE THREAD

**Issue by tapz** [henninghall/react-native-date-picker#620]
**Describe the bug**

I get this error when uploading to App Store Connect in Xcode:

`The app references non-public selectors in Payload/MyApp.app/MyApp: getAuthorizationStatus:, setHighlightsToday:`

**Expected behavior**

No errors.

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [0.71.3]
 - react-native-date-picker version [4.2.9]
 - Xcode: [14.2 (14C18)]

**Comment by henninghall** [comment]
This is more of a warning than a error right? `getAuthorizationStatus` comes from another lib. When it comes to setHighlightsToday you will not be affected by this warning if you use default black or white text colors of the date picker.
