### ISSUE TITLE
DatePicker Not Center in the Screen

### ISSUE THREAD

**Issue by ThushalIntervest** [henninghall/react-native-date-picker#621]
In my Samsung Galaxy A12 DatePicker is not centred on the screen. But in the Google Pixel 6, it is the centre.
This happen after I upgrade Libary 4.2.5 to 4.2.9 ( It works fine in 4.2.5)

`
 <DatePicker
                        testID="dateTimePicker"
                        androidVariant='nativeAndroid'
                        modal
                        mode={'date'}
                        open={show}
                        date={date}
                        // minimumDate={minDate}
                        maximumDate={maxDate}
                        onConfirm={(date) => {
                            onChange("",date)
                            setDate(date);
                            setShow(false)
                        }}
                        onCancel={() => {
                            setShow(false)
                        }}
                        textColor={"#000000"}
                        theme={"light"}
                        locale={"en_GB"}
                    />
`

<img width="320" alt="Screenshot 2023-03-07 at 18 59 28" src="https://user-images.githubusercontent.com/100312355/223437855-dfbd7f15-a09e-4b81-8965-cdfbe183da1d.png">

**Smartphone**
 - OS: Samsung Galaxy Devices Android version 12 and 13
 - React Native version 0.68.2
 - react-native-date-picker version 4.2.9

**Comment by henninghall** [comment]
Looks more user-friendly to me to have the modal at the bottom. It will be closer for the fingers to tap the buttons and this is also how it works on iOS. 

If this really is introduced by an update in this library and not by a Samsung update, I'll see it as a feature and not a bug 😄
