### ISSUE TITLE
[Android] App crashes if unknown locale is passed

### ISSUE THREAD

**Issue by Apporix** [henninghall/react-native-date-picker#623]
**Describe the bug**
The application crashes on Android whilst opening the date picker if an unknown locale (so a locale that is not listed in Formats.java, like `lb` for Luxembourg) is passed. The crash is caused by line 31 of LocaleUtils.java, because the code assumes that if the `Formats.get` method on line 28 fails, then the `languageTag` must have an underscore, which is not the case for the given example. Hence the application crashes due to an out of bounce error.

**Expected behavior**
If the locale is not among the listed locales in Formats.java, the `defaultFormat` should be returned. This can be done by checking in line 31 of LocaleUtils.java if the `indexOf` method returns -1 and if so, then the `FormatNotFoundException` should be manually thrown. Ideally, the `defaultFormat` can be set by a property, to which the date picker then falls back.

**To Reproduce**
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      locale={'lb' /* Luxembourg */}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.68.5
 - react-native-date-picker version 4.2.5

**Comment by henninghall** [comment]
Thanks for reporting this! 
It is fixed in https://github.com/henninghall/react-native-date-picker/pull/650 and released in `4.2.13`.
