### ISSUE TITLE
Picker closing on any taps or scrolling on the picker

### ISSUE THREAD

**Issue by KrisLau** [henninghall/react-native-date-picker#624]
**Describe the bug**
Touching anywhere on the picker causes it to close without changing the date. Code hasn't changed and has worked for the past year or so. Package version hasn't changed either. 

https://user-images.githubusercontent.com/46275463/225142011-ca0d558a-a915-41bc-8944-243f6a0b19c9.mp4

**Expected behavior**
Picker should only close when I click on confirm or cancel

**To Reproduce**
I think it has something to do with my environment tho no clue what.
```javascript
export default class App extends Component {  
  const [showDateTimePicker, setShowDateTimePicker] = React.useState(false);

  render = () => {
     return (
      <Icon
        name={'clock-time-three-outline'}
        type="material-community"
        color={Colors.SECONDARY}
        onPress={() => {
          setShowDateTimePicker(true);
          props.onPressRightIcon();
        }}
        size={20}
      />
      <DatePicker
        modal
        theme={'light'}
        androidVariant={'nativeAndroid'}
        open={showDateTimePicker}
        mode={props.mode}
        date={props.date}
        onConfirm={event => {
          setShowDateTimePicker(false);
          props.onChangeDate(event);
        }}
        onCancel={() => {
          setShowDateTimePicker(false);
        }}
      />
    );
}
```

**Smartphone (please complete the following information):**
 - OS: iOS
 - React Native version 0.70.7
 - react-native-date-picker version 4.2.9

**Comment by KrisLau** [comment]
Added some logging and it seems to be calling the `onCancel` for some reason

**Comment by KrisLau** [comment]
@henninghall Added some logging and it seems to be calling the `onCancel` for some reason

**Comment by KrisLau** [comment]
"Erase All Content and Settings" fixes it as well

**Comment by HuitingLiu** [comment]
I  hit the same issue and "Erase All Content and Settings" doesn't work. 

"react-native": "0.72.4",
"react-native-date-picker": "^4.3.3",

**Comment by KrisLau** [comment]
@HuitingLiu Whenever you have weird issues I would try `react-native clean-project-auto` using https://github.com/pmadruga/react-native-clean-project
