### ISSUE TITLE
In android the selected day comes as the minimum day

### ISSUE THREAD

**Issue by xayilmaz** [henninghall/react-native-date-picker#625]
**Describe the bug**
On Android, the selected day comes as the minimum day, but on iOS I do not have such a problem. On iOS, the maximum day is selected.

Android
![Ekran Resmi](https://user-images.githubusercontent.com/62907229/225301423-25fd2940-de20-4d1f-ac2a-08a11bf87782.png)

IOS
![Ekran Resmi](https://user-images.githubusercontent.com/62907229/225301426-a903f9a5-3e65-4731-94f0-8ae0c1e99bb7.png)

**Expected behavior**
I am waiting for the selected day to come as the maximum day in Android as in IOS.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript

export default ageLimit = () => {
    var date = new Date();
    date.setFullYear(date.getFullYear() - 13);
    return date
}

<DatePicker
    modal
    locale={i18n?.language ?? 'en'}
    title={null}
    theme={"dark"}
    mode={"date"}
    open={datePickerOpen}
    date={date}
    confirmText={i18n.t("Continue")}
    cancelText={i18n.t("Cancel")}
    onConfirm={(date) => {
        setDatePickerOpen(false)
        setDate(date)
        setDateOfBirth(date)
    }}
    onCancel={() => {
        setDatePickerOpen(false)
    }}
    maximumDate={ageLimit()}
/>
```

**Smartphone (please complete the following information):**
 - OS: [Android and iOS]
 - React Native version [0.70.4]
 - react-native-date-picker version [^4.2.9]

**Comment by Rauzon** [comment]
@xayilmaz How did you solved this issue?

**Comment by xayilmaz** [comment]
> @xayilmaz How did you solved this issue?

When I gave a "new Date()" to the date picker it was not working so I solved the problem by providing a date.

you can give a static or dynamic custom date eg.

` date={new Date("2000-01-01")}`
