### ISSUE TITLE
Floating keyboard shows up in mode="time" when clicking the time.

### ISSUE THREAD

**Issue by anieshka** [henninghall/react-native-date-picker#631]
### Discussed in https://github.com/henninghall/react-native-date-picker/discussions/630

<div type='discussions-op-text'>

<sup>Originally posted by **anieshka** March 29, 2023</sup>
Is there a way to disable this feature? I've recently discovered this feature and didn't notice it before. Can someone help me, please?</div>
![02C1D7F2-83EC-4704-BEEA-74E7FC37CF4B](https://user-images.githubusercontent.com/80374400/228449097-9fb41cef-c9ff-4a3d-989f-1e18a9ef6238.jpeg)

**Comment by henninghall** [comment]
Duplicate https://github.com/henninghall/react-native-date-picker/issues/573
