### ISSUE TITLE
Date picker not showing on infinix and on google pixel mobile.

### ISSUE THREAD

**Issue by umairalirehan** [henninghall/react-native-date-picker#638]
I use date picker in react natice cli. but its not showing date picker on few mobile just like on infinix and on google pixel. But on some devices its working fine.

import React, {useEffect, useState} from 'react';
import {
SafeAreaView,
StatusBar,
View,
Text,
StyleSheet,
TouchableOpacity,
Modal,
ScrollView,
Button,
} from 'react-native';
import {
widthPercentageToDP as wp,
heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

import DatePicker from 'react-native-date-picker';
import colors from '../../Styles/colors';

import moment from 'moment';
import fontFamily from '../../Styles/fontFamily';

const DatePickerModal = ({modalVisible, onPressModal}) => {
const [date, setDate] = useState(new Date());

useEffect(() => {
// console.log("hook", moment(date).format("YYYY-DD-MM"))
}, [date]);

console.log('date', date);

return (

<View style={{flex: 1}}>
<TouchableOpacity
onPress={() => onPressModal(date)}
style={{
flex: 0.7,
backgroundColor: colors.transparentBlack,
}}>
<View
style={{
flex: 0.3,
backgroundColor: colors.white,
justifyContent: 'center',
alignItems: 'center',
width: wp('100'),
}}>

<DatePicker
mode="date"
minimumDate={new Date()}
date={date}
onDateChange={date => {
// console.log("insideDate", date)
setDate(date);
}}
/>

);
};

const styles = StyleSheet.create({});
export default DatePickerModal;

**Comment by henninghall** [comment]
1. Can you send a screenshot of the problem.
2. Does it show if you’re setting locale=“en” ?
