### ISSUE TITLE
if I use this on android only do we need to link?

### ISSUE THREAD

**Issue by craigcosmo** [henninghall/react-native-date-picker#64]
Hi,

if I use this on android only do we need to react-native link react-native-date-picker?

**Comment by henninghall** [comment]
Yes!

**Comment by craigcosmo** [comment]
As all of my code is inside the expo framework, it doesn't do linking

is it possible to extract the adnroid date picker from this project and use it as independent component, without react native linking?

**Comment by henninghall** [comment]
You will always need linking when the component uses native code, which it does, or what do you mean?

**Comment by henninghall** [comment]
There is now a [feature request you can upvote 👍](https://expo.canny.io/feature-requests/p/support-react-native-date-picker) if you still are interested in using react-native-date-picker with expo!

**Comment by henninghall** [comment]
Expo is now supported https://github.com/henninghall/react-native-date-picker#using-expo
