### ISSUE TITLE
 Could not find com.github.henninghall:numberpickerview:v1.1.5.

### ISSUE THREAD

**Issue by Kartik18g** [henninghall/react-native-date-picker#640]
**Describe the bug**
Build fails with ` Could not find com.github.henninghall:numberpickerview:v1.1.5.` 

 - OS: MacOS Android build
 - React Native version 0.67.2
 - react-native-date-picker version [e.g. 4.2.10]

**Comment by henninghall** [comment]
Jitpack is down at the moment https://www.saashub.com/jitpack-status

**Comment by henninghall** [comment]
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/396

**Comment by Kartik18g** [comment]
@henninghall 
Adding this to build.gradle is necessary for android builds to succeed. Can't we add this into the setup guide ?
```maven { url 'https://www.jitpack.io' }```

**Comment by lucaszdev** [comment]
@Kartik18g  Still with problem
