### ISSUE TITLE
setting maximumDate does not remove next months and days 

### ISSUE THREAD

**Issue by Mouhib-Rabbeg** [henninghall/react-native-date-picker#651]
<DatePicker
        date={new Date()}
        maximumDate={new Date()}
        onDateChange={dateChangeHandler}
        mode="date"
        androidVariant={'nativeAndroid'}
        
       
      />
it only removes years but months and days still shown
![image](https://user-images.githubusercontent.com/64324337/234816463-6134dedd-a583-4a32-8981-14deba7b6619.png)
same for minimumDate

**Comment by henninghall** [comment]
This is intentional and a limitation on iOS. 
The feature request discussion around fixing it on android is here: https://github.com/henninghall/react-native-date-picker/discussions/123

**Comment by caolong24** [comment]
> This is intentional and a limitation on iOS. The feature request discussion around fixing it on android is here: #123

why u set limit like that on ios?
