### ISSUE TITLE
Why testID is gone?

### ISSUE THREAD

**Issue by ksetrin** [henninghall/react-native-date-picker#652]
You added testID here https://github.com/henninghall/react-native-date-picker/pull/133

But it's gone now.

**Comment by henninghall** [comment]
I believe testID can still be passed in since it there is a prop spread in the component

**Comment by bemaverick** [comment]
@ksetrin Any progress with this?

**Comment by ksetrin** [comment]
> @ksetrin Any progress with this?

No, sadly I've not found a way to change the date via Detox

**Comment by andreyukD** [comment]
You can use `setDatePickerDate` method 
https://wix.github.io/Detox/docs/next/api/actions/#setdatepickerdatedatestring-dateformat
