### ISSUE TITLE
Library not working in Android, app not compile

### ISSUE THREAD

**Issue by lucaszdev** [henninghall/react-native-date-picker#653]
**Describe the bug**
When I install the library, works PERFECT in IOS, but in android, I can't use the library

**Expected behavior**
I expected to compile the android

**To Reproduce**
Just install the library, my RN version is 0.64.0

THE ERROR:

BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.henninghall:numberpickerview:v1.1.5.
     Searched in the following locations:
       - file:/Users/lucaszdev/.m2/repository/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
       - file:/Users/lucaszdev/Documents/mycapital-app/MyCapital/node_modules/react-native/android/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
       - file:/Users/lucaszdev/Documents/mycapital-app/MyCapital/node_modules/jsc-android/dist/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
       - https://dl.google.com/dl/android/maven2/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
       - https://jcenter.bintray.com/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
       - https://repo.maven.apache.org/maven2/com/github/henninghall/numberpickerview/v1.1.5/numberpickerview-v1.1.5.pom
     Required by:
         project :app > project :react-native-date-picker

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version 0.64.0
 - react-native-date-picker version 4.2.13

**Comment by F100P** [comment]
I don't know if I'm just rubbing it in but it is stated in the requirements that 
" * If using React Native 0.64, 0.64.2 or later must be used."

**Comment by henninghall** [comment]
That is right, 0.64.0 is not supported. Try a newer version @lucaszdev
