### ISSUE TITLE
Unable to centrally align the month in the picker in locale: 'en_UK'

### ISSUE THREAD

**Issue by MonicaAcha2103** [henninghall/react-native-date-picker#656]
**Describe the bug**
The space between the month and year is not equally spaced.
The month is always left aligned. No specific style props is provided to customise the month alignment

**To Reproduce**
pass the prop- locale= 'en_UK'

DateTimePicker
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
      locale= 'en_UK'
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [both Android or iOS]
 - React Native version [e.g. 0.71.3]
 - react-native-date-picker version [e.g. 4.4.2]
 

Android - 
<img width="267" alt="Screenshot 2023-05-18 at 1 42 59 PM" src="https://github.com/henninghall/react-native-date-picker/assets/22819187/c1154909-9133-40b9-a324-062dd8653618">

IOS - 
<img width="333" alt="Screenshot 2023-05-18 at 1 46 46 PM" src="https://github.com/henninghall/react-native-date-picker/assets/22819187/f0226262-851d-44d1-bc8d-e200396d7334">

**Comment by henninghall** [comment]
This is probably intended. Don't think it would be possible to change because of a limitation in UIDatePicker, the iOS component used under the hood.
