### ISSUE TITLE
is there a way I can change the divider's background color on ios?

### ISSUE THREAD

**Issue by LastStranger** [henninghall/react-native-date-picker#657]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
It is unfortunately not, it is a limitation of UIDatePicker, the component being used under the hood.
