### ISSUE TITLE
Force time picker to use Military Time(e.g 00:01 - 23:30) even though device setting is set to 12 hours

### ISSUE THREAD

**Issue by aliza-khu** [henninghall/react-native-date-picker#658]
Force application to use 24 hours time instead of 12 hours even though the device setting is set to 12 hours.

**Comment by henninghall** [comment]
Answered here https://github.com/henninghall/react-native-date-picker#how-do-i-change-the-1224h-or-ampm-format

**Comment by aliza-khu** [comment]
@henninghall, I am facing the issue of **Force time picker to use Military Time(e.g 00:01 - 23:30) even though device setting is set to 12 hours** in the latest iOS 16.5. Below are the configuration sets for the project.

**Packages Version**
"react": "18.2.0",
"react-native": "0.71.4",
"react-native-date-picker": "^4.2.6"

**Date Picker Configuration**
locale="en_GB"
is24hourSource="locale"

Can you please try to replicate the same from your end and share your suggestions to overcome this issue with me? Your efforts for this issue are most valuable to us.

**Comment by aliza-khu** [comment]
@henninghall, Can you please share your input on the above comment 👆? It's urgent to get it resolved.
