### ISSUE TITLE
XCODE Build fails with 2 duplicate symbols for architecture x86_64 and Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by shayelbaz1** [henninghall/react-native-date-picker#660]
**Describe the bug**
node 16.19.1, cd ios, pod deintegrate, pod install, run xcode, iPhone 11, 16.4.0
Build Faild on Xcode with this error:
2 duplicate symbols for architecture x86_64
Linker command failed with exit code 1 (use -v to see invocation)

**Expected behavior**
Build succeed and app running on iPhone 11 simulator.

**Smartphone (please complete the following information):**
 - OS: iOS
 - React Native version 0.67.5
 - react-native-date-picker version 4.2.13

**Comment by henninghall** [comment]
Could you provide a sample repo where this is reproducible? Thanks
