### ISSUE TITLE
RNDate picker tried to override RNDatePicker...If This Was Your Intention ,set canOverrideExistingModule = true

### ISSUE THREAD

**Issue by Vigneshwaran-crypto** [henninghall/react-native-date-picker#662]
If is install any type of sound npm package I got this error in react-native-date-picker

**Comment by bertdida** [comment]
I also have this problem today. Removing `@react-native-community/datetimepicker` on my package.json fixes my issue.

**Comment by Vigneshwaran-crypto** [comment]
Just Downgrade  this Package version `@react-native-community/datetimepicker`    will Solve the problem..

And Thank You @bertdida
