### ISSUE TITLE
Unable to use DatePicker on IOS

### ISSUE THREAD

**Issue by smiley717** [henninghall/react-native-date-picker#663]
**Describe the bug**
It works with android perfectly, just not working with ios. Does anyone help on this?

![image](https://github.com/henninghall/react-native-date-picker/assets/80674675/c541f4d9-8d8f-4a85-b2c1-191022cf91c1)

**Smartphone (please complete the following information):**
 - OS: Mac Ventura 13.4
 - React Native version 0.71.4
 - react-native-date-picker version: 4.2.13

**Comment by smiley717** [comment]
@henninghall  Can you check on this?

**Comment by smiley717** [comment]
Fixed it, it was a problem related to XCode 14.3 and IOS simulator 16.4.
https://github.com/facebook/react-native/issues/37817

**Comment by AlexandreHoumeau** [comment]
Hi, did you manage to make it work on IOS 16.4?

**Comment by smiley717** [comment]
Nope, it was just warning and could not spend so many times. It's fine with IOS 15 version.

**Comment by AlexandreHoumeau** [comment]
Ok thanks for your quick reply. Do you know if it would work on production with IOS 16?

**Comment by CHANDRAMOHANnegi** [comment]
Working on ios 15

**Comment by mcewball13** [comment]
Is there any resolution to this? I am having this issue running IOS 17 simulator. 
![Screenshot 2023-12-16 at 7 06 09 AM](https://github.com/henninghall/react-native-date-picker/assets/46138623/137e0779-7686-49bf-836c-5f7ecf61e68c)

**Comment by srithar21** [comment]
@smiley717 This issue still exist ion RN Version 0.69.0.

Can you pleae let me know solution for this?
