### ISSUE TITLE
Force time picker to use Military Time(e.g 00:01 - 23:30) even though device setting is set to 12 hours [New]

### ISSUE THREAD

**Issue by aliza-khu** [henninghall/react-native-date-picker#665]
**Describe the bug**
Force the application to use 24 hours time instead of 12 hours even though the device setting is set to 12 hours. But In iOS 16.5 the feature is breaking and showing the time format based on the device setting instead of configured force to use 24-hour time format.

**Expected behavior**
The application should use 24 hours time instead of 12 hours even though the device setting is set to 12 hours.

**To Reproduce**
Below is a sample of the code
```javascript

  render = () =>
    <DatePicker
            date={value}
            minimumDate={new Date(new Date().getFullYear(), 0, 1, 0, 0)}
            maximumDate={new Date(new Date().getFullYear(), 11, 31, 23, 59)}
            dividerHeight={StyleSheet.hairlineWidth}
            textColor={Platform.select({ android: '#222B45', ios: '#000' })}
            fadeToColor="#ffffff"
            minuteInterval={1}
            is24hourSource="locale"
            locale="en_GB"
          />
```

**Smartphone:**
 - OS: iOS
 - React Native version: 0.71.4
 - react-native-date-picker version: 4.2.6

**Screenshots:**
![IMG_3716](https://github.com/henninghall/react-native-date-picker/assets/112606371/6ab80f4e-1c3c-4cb1-b605-0b1119a247f7)
![IMG_3718](https://github.com/henninghall/react-native-date-picker/assets/112606371/87fd30c9-b1ac-478f-9d5a-cd80661f0e6f)

**Comment by aliza-khu** [comment]
@henninghall, Can you please look into this?

**Comment by RoshanPenielKyro** [comment]
@aliza-khu  I too got the same issue. I think this happens only in the latest version of iOS devices and it works fine in older version devices

**Comment by aliza-khu** [comment]
@RoshanPenielKyro, Yes it's only reproducing in the latest iOS Version rest older versions working fine. I hope @henninghall will enlighten the solution. @RoshanPenielKyro, Please do share the solution if you found any. Really need a conclusion or solution required.

**Comment by aliza-khu** [comment]
@henninghall, Awaiting for the solution to this!

**Comment by akhilsanker** [comment]
@henninghall , same issue here. Need a solution.

Thanks

**Comment by umarClickChain** [comment]
@henninghall waiting for the solution for this

**Comment by aliza-khu** [comment]
@henninghall, Can you please share any of the input you have for this issue?

**Comment by lovish888** [comment]
This issue seems to only exist for iOS 16.5. I have created a custom time picker using [react-native-segmented-picker](https://github.com/adammcarth/react-native-segmented-picker)

**Comment by perlasivakrishna** [comment]
Yes this is broken in native DatePicker component as well starting from iOS 16.5. not sure if this is a bug from apple or intended.
