### ISSUE TITLE
Can we hide Cancel Button on iOS & Android Device?

### ISSUE THREAD

**Issue by asadmumtaz92** [henninghall/react-native-date-picker#667]
***Can we hide cancel button on iOS & Android Device?***

<img width="376" alt="image" src="https://github.com/henninghall/react-native-date-picker/assets/44339021/d91dd003-e812-4402-96bf-f119feb12982">

```

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [e.g. 0.71.8]
 - react-native-date-picker version [e.g. 4.2.13]

**Comment by henninghall** [comment]
Only if you make your own modal with the inline variant date picker, see docs.
