### ISSUE TITLE
Could not find com.github.henninghall:numberpickerview:v1.1.5.

### ISSUE THREAD

**Issue by alizhan1** [henninghall/react-native-date-picker#668]
**Describe the bug**
When I am trying to build android apk, I am getting the following error.
```
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.henninghall:numberpickerview:v1.1.5.
     Searched in the following locations:

``` 
I have tried to use another repositories but none of those worked and jitpack is down since 9 month

**Comment by yurykorzun** [comment]
As a temporary solution, I had to patch node_modules/react-native-date-picker/android/build.gradle and replace implementation 'com.henninghall.android:NumberPickerView:1.1.5' with implementation 'com.github.henninghall:numberpickerview:1.1.5'

**Comment by henninghall** [comment]
@alizhan1 are you still having this issue or was it temporary?

**Comment by alizhan1** [comment]
@henninghall sorry forgot about the issue, I did not have time to wait because of the project deadline and I switched to another library. Thanks for resolving the issue, hopefully it will help other guys.

**Comment by ritesh-singh-quintype** [comment]
Still facing the same issue
