### ISSUE TITLE
Android DateTime picker bugs with minDate and maxDate

### ISSUE THREAD

**Issue by JoelJKoel** [henninghall/react-native-date-picker#670]
**Description of the bug**
Found a series of bugs when trying to use date picker on Android with DateTime mode regarding the minDate and maxDate props.
Without specifying minDate value the maximum time user can go back is 6 months.
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/37ccf814-49d8-4c38-96da-c4b1be47c6a5)
_Current date was 30. June._

If I specify minDate value for example selectedDate - 1 year and dont set a maxDate then when opening the date picker the default value will be the minDate value and maximum time I could select was minDate + 6 months. So comparing to current date I could select a date between -1 year and -6 months.
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/8c7f7b12-59f9-465b-b7cd-36318d65300c)
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/b6ae9fb6-71ff-4395-8cf2-097bb054a9df)
_minDate set as (selectedDate - 1 year), maxDate is undefined, tried to scroll to the furthest date in the future_

If I specify minDate value for example selectedDate - 1 year and maxDate as current date it works as expected initially. 
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/5682da29-860d-42d8-8d06-b7bf4e770722)
But once I select a different date in the past and reopen the picker (in this case current_date -23h57m) user can no longer select "Today" as a date.
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/87263b46-2dab-407a-9236-77c904a4a57b)

The issue is that I cant leave minDate undefined since I want user to be able to select a date from a calendar and then select a time period in regards to that selected date. If minDate is undefined they cant go back further than 6 months. But if I leave minDate undefined I run into the wrong default value and stuck with the past dates issue. And if I do set maxDate so they cant select dates in the future then in some situations after editing the current value they cant select current date ("Today") anymore.

**Expected behavior**
Similar behavior to iOS, you can freely set minDate and maxDate value without it altering the usability of the datepicker.

**Example code**

<DatePicker 
     date={new Date(props.date)}
     onDateChange={props.onChange}
     style={styles.datePicker}
     mode={'datetime'}
     is24hourSource="locale"
     fadeToColor="none"
     minimumDate={props.minDate || null}
     maximumDate={props.maxDate || null}
/>

**Smartphone (please complete the following information):**
    OS: Android
    React Native version 0.67.5
    react-native-date-picker version 4.2.12

**Comment by JoelJKoel** [comment]
For clarification the issue is not just "Today" date missing from picker selection, it can be any maxDate date value missing if the difference between minDate and maxDate is less than N days. For example minDate is set as _2023-06-26T09:14:00.000Z_ and maxDate is _2023-06-29T09:13:00.000Z_ as a result the 29 Jun selection is missing. 
![image](https://github.com/henninghall/react-native-date-picker/assets/133960329/f68bd0eb-7a0c-48ac-8467-ddf644d7bb94)
If I increase maxDate time to 9:14 the 29 Jun selection is there again.

**Comment by henninghall** [comment]
Hi, thanks for reporting this. What timezone is the simulator/phone using? Note that `2023-06-29T09:13:00.000Z` is UTC and the visible time in the picker is in the local timezone by default.

**Comment by JoelJKoel** [comment]
Hi! The simulator phone was using UTC+3 timezone.

**Comment by kaancembertas** [comment]
Hi, I am facing the same issue on android with minDate and maxDate

**Comment by Ethan-G** [comment]
I found the date picker will display the number of days equal to max-min/24, rounded DOWN. So if minDate is 1 second from now, and max is 3 days from now, it will only show 2 days. If max is 3 days and 1 second from now, behaviour is as expected.

(All Android, iOS is fine it seems).

**Comment by henninghall** [comment]
Thanks for helping out understanding this bug. I managed to reproduce it and fix it by https://github.com/henninghall/react-native-date-picker/pull/740. It is released in version 4.3.5.

Please let me know if you still experience anything unexpected after upgrading to 4.3.5.
