### ISSUE TITLE
Multiple installed date picker libs not supported (0.71.+ Android) 

### ISSUE THREAD

**Issue by dkahdwk** [henninghall/react-native-date-picker#671]
**Describe the bug**
Installing and running the library in an Android environment of 0.71 results in an error that does not cross the startup screen.

logcat:
```
2023-07-03 14:17:42.996 7034-7150/com.soldoc E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Native module RNDatePicker tried to override DatePickerModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:55)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
```

**Smartphone (please complete the following information):**
 - OS: Anroid
 - React Native version 0.71.7
 - react-native-date-picker version 4.2.13

**Comment by henninghall** [comment]
Hi, thanks for reporting this, are you having multiple date picker libraries installed?

**Comment by dkahdwk** [comment]
> Hi, thanks for reporting this, are you having multiple date picker libraries installed?

react-native-datetimepicker library is also installed, is it a problem that there are multiple date libraries installed?

**Comment by henninghall** [comment]
I think it should be supported to have multiple installed, it could be the reason to the error though. Could you try to uninstall `react-native-datetimepicker` temporarily just to see if that was causing the issue?

**Comment by dkahdwk** [comment]
@henninghall As you said, I don't think multi-installation is supported. Uninstalling the react-native-datetimepicker works fine.

**Comment by wmonecke** [comment]
I have the same issue.

As a temporary fix, you can go to:

`node_modules/react-native-date-picker/android/src/main/java` and open the `DatePickerModule.java`.

There you can add the following:

```java
  @Override    
    public boolean canOverrideExistingModule() {        
        return true;    
    }  
```

<img width="1091" alt="image" src="https://github.com/henninghall/react-native-date-picker/assets/24256469/cb56d40f-5fcd-4a43-ad02-d55335d8d7b9">

**Comment by tranminhnhat1005** [comment]
I removed `@react-native-community/datetimepicker` and it work. Hope it useful.

**Comment by DusanSpasojevic98** [comment]
This also works as a temporary fix #662

**Comment by kuchbhihosaktahai** [comment]
https://www.youtube.com/watch?v=W3m-8_QuC14&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=12

**Comment by henninghall** [comment]
Look at this and it seem to be some situations where multiple date picker packages might be colliding. I don't see a big reason to allow @react-native-community/datetimepicker to be installed at the same time, since the feature set is overlapping. 

I will treat it as a limitation of this package.
