### ISSUE TITLE
Add select year inside spinner for ios and android 

### ISSUE THREAD

**Issue by VictorPulzz** [henninghall/react-native-date-picker#673]
**Describe the bug**
When we have mode datetime, I can't select year.. It is extremely inconvenient to scroll all the days back 10 years....

**Expected behavior**
Have year inside roll

**To Reproduce**
Just install plugin

```javascript
export const App = () => {
  return (
    <DatePicker
        mode={'datetime'}
        theme="light"
        date={new Date()}
        onDateChange={handleConfirm}
        androidVariant="iosClone"
        style={{ marginVertical: 0 }}
        minimumDate={new Date('1920')}
      />
  )
}
```

**Smartphone (please complete the following information):**
 - OS: On IOS and Android
 - React Native version 0.71.8
 - react-native-date-picker version 4.2.6

**Comment by henninghall** [comment]
I recommend you change you UX to better handle this case. For instance by using separate date pickers for date and time.
