### ISSUE TITLE
Modal is not opening in IOS and Android Expo application "TypeError: Cannot read property 'openPicker' of null"

### ISSUE THREAD

**Issue by madlink** [henninghall/react-native-date-picker#674]
Opening a new issue because the original one #610  is closed but the problem is not fixed.

Steps:

1. npx create-expo-app date-picker-app
2. npx expo install react-native-date-picker
3. Use example https://github.com/henninghall/react-native-date-picker#example-1-modal
5. Once the picker is set as open you get the error "TypeError: _reactNative.NativeModules.RNDatePicker.openPicker is not a function (it is undefined" on both ios and android

**Comment by yauheni-charniauski-purposetech** [comment]
![image](https://github.com/henninghall/react-native-date-picker/assets/139142359/2243176d-d88f-47e0-b7f4-64116504e97f)

**Comment by henninghall** [comment]
As described in README, Expo Go is unfortunately not supported since this lib requires native code.

**Comment by komailabbas12** [comment]
@henninghall  i am facing this issue in react native cli. react-native version 0.72.4

**Comment by aqos156** [comment]
Any solution for react native cli? @komailabbas12 did you figure it out?

**Comment by ser-emejia** [comment]
what about android?
works fine in simulators but on device crash the app

im working with expo development build
