### ISSUE TITLE
Date picker not showing in Testflight app when run on MacBook

### ISSUE THREAD

**Issue by anniewey** [henninghall/react-native-date-picker#677]
**Describe the bug**
Date picker is not shown when run app on Testflight desktop version.

**Expected behavior**
Show date picker

**To Reproduce**
Add a datepicker in sample app and upload to testflight. Open the app and tap on date picker. An alert message, `Please select date` is shown instead of date picker.

**Version**
"react-native-date-picker": "^4.2.1",

**Comment by henninghall** [comment]
The version you're using are a few years old, please update the date picker version and we can reopen this issue if it still doesn't work.

**Comment by anniewey** [comment]
Thanks, i've tried to upgrade to the latest `4.3.0` but encounter this [issue](https://github.com/henninghall/react-native-date-picker/issues/404#issuecomment-1713061746). Hence, i've unable to check that as i've downgraded back to `4.2.1`.
