### ISSUE TITLE
Issue with intervals while having validations 

### ISSUE THREAD

**Issue by mohitharshan123** [henninghall/react-native-date-picker#681]
**Describe the bug**
Issue is when there are two time pickers for a start time and end time while having a validation that end time could not be before the start time

Interval : 30 mins 

Example:

Start time : 9:00 AM
End time: 12:00 AM

This should raise a validation error that end time could not be before the start time as the day starts at 12:00 AM.

There is an option to choose till 11:30 because the interval is set in 30 mins, but I want the end time to be at 12:00 midnight. So my bet is to use 1 min interval and set the start time at 9:00AM and end time at 11:59 PM. However I don't want to allow one minute intervals. 

Would it be nice to have an extra time option as 11:59 PM after 11:30 PM?

**Expected behavior**

When time interval is set to 30 mins,

Listed time periods would go towards the end of the day like 10:00 PM, 10:30PM, 11:00 PM, 11:30 PM, 11:59PM.

**Comment by mohitharshan123** [comment]
@henninghall

**Comment by henninghall** [comment]
Please fill in the issue template properly and I can take a look at this
