### ISSUE TITLE
Weird look of Date Picker on IOS

### ISSUE THREAD

**Issue by Kornelg96** [henninghall/react-native-date-picker#682]
**Describe the bug**
On iphone 13 Pro OS 16.6 the error does not occur.
On iphone 14 pro OS 16.6 date picker looks weird...

**Smartphone (please complete the following information):**
 - OS: IOS
        "react-native": "0.69.7",
        "react-native-date-picker": "^4.2.13",
![cc0f8fa6-706b-4a09-888c-e43eeb88f150](https://github.com/henninghall/react-native-date-picker/assets/62172008/b93095e8-5a37-4e74-9414-ab478ca87f8f)

![IMG_5410](https://github.com/henninghall/react-native-date-picker/assets/62172008/95b0bfbe-9e35-491a-9463-e78f776d1e2a)

code : 
```
const InlineDatePicker = ({date, onDateChange}) => {
    return (
        <DatePicker
            date={date}
            onDateChange={onDateChange}
            mode="date"
            locale="en-gb"
            androidVariant="nativeAndroid"
        />
    );
};

export default InlineDatePicker;

```
thanks for all answers maybe Im doing something wrong ..

**Comment by henninghall** [comment]
Try setting the text color or theme prop
