### ISSUE TITLE
Are there way to change background color of DatePicker components. 

### ISSUE THREAD

**Issue by ashangrajapaksha** [henninghall/react-native-date-picker#684]
**Describe the bug**
can't change background color on DatePicker .  only can change them as light and dark

**Expected behavior**
I want to change background color as my designed. 

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
Possible for inline mode, see readme for example
