### ISSUE TITLE
Title color can't change

### ISSUE THREAD

**Issue by ashangrajapaksha** [henninghall/react-native-date-picker#685]
**Describe the bug**
when we use theme as dark title color also dark. 

**Expected behavior**
I want to change title color as white.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
Right, you will need to create your own modal with the inline picker inside for that to work
