### ISSUE TITLE
Cannot build not using new arch with version 4.3.0

### ISSUE THREAD

**Issue by frederikreher** [henninghall/react-native-date-picker#693]
**Describe the bug**
I have an app that does not have new arch enabled. When building the app xcode complains with the following error: 
`Declaration of 'RCTConvert' must be imported from module 'React.RCTConvert' before it is required`

I downgraded `react-native-date-picker` to `4.2.14` and it builds flawlessly. 

Changing the import in `ios/DatePicker.m:12` to be `#import "React/RCTConvert.h"` seems to resolve the issue when building. But i have not tested this thoroughly - and I am not sure that you intend to support apps without new arch enabled. 

**Expected behavior**
That the library should support both enabling and disabling new arch. 

**Smartphone (please complete the following information):**
 - OS: IOS
 - React Native version 0.71.8
 - react-native-date-picker version 4.3.0

**Comment by henninghall** [comment]
@frederikreher Hi, thanks for reporting this! The intension is definitely to suport old architecture, also in 4.3.0 and forward.

I didn't manage to reproduce this when running 0.71.8, but made some changes though, could you try to install version `4.3.1-alpha.0` and see if that helps? If not, could you please provide your xcode, cocoapods and ruby version?

**Comment by frederikreher** [comment]
`4.3.1-alpha.0` unfortunately gives the same error.
<img width="1302" alt="Screenshot 2023-09-11 at 16 15 39" src="https://github.com/henninghall/react-native-date-picker/assets/10392734/1e64e3be-0680-4843-a8b1-20c4d29da196">

ruby: 3.1.3
cocoapods: 1.12.1
xcode: 14.2 (14C18)

**Comment by henninghall** [comment]
Thanks a lot, do you mind trying this out? `4.3.1-alpha.1`

**Comment by frederikreher** [comment]
> Thanks a lot, do you mind trying this out? `4.3.1-alpha.1`

That seems to have fixed it!

**Comment by henninghall** [comment]
Great, released the fix in version `4.3.1`

**Comment by frederikreher** [comment]
Thanks @henninghall. I really appreciate it!
