### ISSUE TITLE
[IOS] Date picker works well on virtual devices, but not on physical devices.

### ISSUE THREAD

**Issue by heeeete** [henninghall/react-native-date-picker#696]
code
-------------------------------------------------------------
```
const [date, setDate] = useState(new Date());
<Modal>

...

      <DatePicker
                    date={date}
                    onDateChange={setDate}
                    minimumDate={new Date()}
      />

...
</Modal>
```
-------------------------------------------------------------

The date picker works fine on a virtual device, but when I build and test it on my own device, I can't even pick a date and the initial date looks weird like that.

virtual device

<img src="https://github.com/henninghall/react-native-date-picker/assets/101648575/2eadadd3-c173-4128-9b84-2f7d4bcc6d00" width="40%" height="40%" alt="IMG_5906">

my device

<img src="https://github.com/henninghall/react-native-date-picker/assets/101648575/2c868744-8bed-428a-a91a-7447c5c90975" width="40%" height="40%">

**Smartphone (please complete the following information):**
 - OS: [IOS] simulator iphone 14 PRO (16.4), my iphone 12 (16.6)
 - React Native version [0.72.1]
 - react-native-date-picker version [4.2.14]

**Comment by henninghall** [comment]
Is dark mode enabled? Try setting the textColor prop if you are not supporting dark mode.

**Comment by heeeete** [comment]
> Is dark mode enabled? Try setting the textColor prop if you are not supporting dark mode in your app.

Solved, thank you! Can I ask you one more question? I'm Korean and the date comes out fine in Korean on the virtual device, but on the real device it comes out in English, what should I do?
