### ISSUE TITLE
Compilation failed; Execution failed for task ':react-native-date-picker:compileDebugJavaWithJavac' 

### ISSUE THREAD

**Issue by banghia112** [henninghall/react-native-date-picker#697]
**Describe the bug**
- React Native Info: 
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 44.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Documents/med247-app/node_modules/.bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/nghianguyen/.rvm/gems/ruby-3.0.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- I was building my react native app then i got this error: 
   
![image](https://github.com/henninghall/react-native-date-picker/assets/89189266/78b04ed0-cef3-45b3-b011-e1b6bc2a19ad)

making picker final in DatePickerModuleImpl.java seems to do the trick: 

![image](https://github.com/henninghall/react-native-date-picker/assets/89189266/ef505968-3367-4936-96f7-c1b975cf2062)

Is it a valid solution? Should i make a PR about this

PS: i don't know much about Java

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.63.4
 - react-native-date-picker version ^4.2.6

**Comment by Arturopaz19** [comment]
i have the same problem, any solution?

Smartphone (please complete the following information):

OS: Android
React Native version 0.63.5
react-native-date-picker version ^4.2.13

**Comment by henninghall** [comment]
Thanks for the PR @banghia112! The fix for this is now released in 4.3.3

**Comment by AngelDev0329** [comment]
I am facing this problem yet.
