### ISSUE TITLE
Android TalkBack reads nonsense

### ISSUE THREAD

**Issue by heorhii-ms** [henninghall/react-native-date-picker#703]
**Describe the bug**
Android TalkBack reads nonsense on changing time
[Video](https://www.loom.com/share/f45d9d1cb9684b949e4e226bf6ec8135?sid=efa83113-6c89-4039-8be0-ba9e2abb5304)

**Expected behavior**
Android TalkBack reads selected time correctly 

**To Reproduce**
Start on Pixel 2 simulator (Android 14)
On Xiaomi Redmi Note 9 Pro (Android 12) we have the same result
```javascript
         <DatePicker
              minimumDate={minimumDate}
              mode="time"
              minuteInterval={5}
              is24hourSource="device"
              androidVariant="nativeAndroid"
              date={time}
              fadeToColor={theme.colors.textPrimary}
              textColor={theme.colors.textPrimary}
              onDateChange={nextTime => {
                this._setTime(nextTime);
              }}
            />
```

**Smartphone (please complete the following information):**
 - OS: Android
 - "react-native-date-picker": "^4.3.3",
 
 System:
    OS: macOS 12.6.9
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 44.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 
    Yarn: 1.22.19 
    npm: 9.5.0 
    Watchman: 2023.05.08.00 
  Managers:
    CocoaPods: 1.12.0 
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18
  Languages:
    Java: 11.0.19
  npmPackages:
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4

**Comment by henninghall** [comment]
Hi, we are aware of this. It is being tracked in following issue:

https://github.com/henninghall/react-native-date-picker/issues/372

You can use isoClone for better compatibility with talkback. 

Feel free to help out with PR’s improving the support for talkback on the nativeAndroid variant ☺️
