### ISSUE TITLE
Current date in date mode has wrong color [iOS]

### ISSUE THREAD

**Issue by NikolakoG** [henninghall/react-native-date-picker#707]
When passing a color using textColor prop, in iOS implementation of the the library the current date has wrong color.
The Component is in 'date' mode.

The code below is the one from my project:

<DatePicker
   mode="date"
   date={date}
   onDateChange={datePicker}
   locale={locale}
   maximumDate={maximumDate}
   minimumDate={minimumDate}
   textColor={theme.colors.BLACK}
   androidVariant="nativeAndroid"
/>

where theme.colors.BLACK is an object passing 2 colors depending on the apps theme.

I checked library's code which is responsible for rendering the component in iOS and found out that if we add the code {color: props.textColor} in style of _toIosProps function in DatePickerIOS.js file that bug is fixed. (The alteration of the code is shown below)

  _toIosProps = (props) => {
    return {
      ...props,
      style: [styles.datePickerIOS, **{color: props.textColor},** props.style],
      date: props.date ? props.date.getTime() : undefined,
      locale: props.locale ? props.locale : undefined,
      maximumDate: props.maximumDate ? props.maximumDate.getTime() : undefined,
      minimumDate: props.minimumDate ? props.minimumDate.getTime() : undefined,
      theme: props.theme ? props.theme : 'auto',
    }
  }

Smartphone :
 - OS: iOS
 - iOS version 16.0
 - react-native-date-picker version 4.3.3

**Comment by henninghall** [comment]
Please add the code you're running when the error occurs + a screenshot of the unexpected behaviour

**Comment by NikolakoG** [comment]
I'm sorry, I accidently deleted the code I'm using. Here it is:

<DatePicker
            mode="date"
            date={date}
            onDateChange={datePicker}
            locale={locale}
            maximumDate={maximumDate}
            minimumDate={minimumDate}
            textColor={theme.colors.BLACK}
            androidVariant="nativeAndroid"
          />
          
and the unexpected behavior is shown in the screenshot
![simulator_screenshot_17668F83-16D2-4F83-86EB-409FC438D56A](https://github.com/henninghall/react-native-date-picker/assets/82265756/22996930-df8b-4a7e-a0a5-5a03178666b9)

**Comment by NikolakoG** [comment]
I'm sorry, I accidently deleted the code I'm using. Here it is:

<DatePicker
mode="date"
date={date}
onDateChange={datePicker}locale={locale}
maximumDate={maximumDate}
minimumDate={minimumDate}
textColor={theme.colors.BLACK}
androidVariant="nativeAndroid"
/>

and the unexpected behavior is shown in the screenshot
![Screenshot 2023-10-02 at 11 00 27 AM](https://github.com/henninghall/react-native-date-picker/assets/82265756/eeabd43e-5d57-40a9-9aca-f4e3675a8f73)

**Comment by NikolakoG** [comment]
If I set textColor as a hex color it works fine, if I use my variable which switches between two hex colors, the current date keeps rendering with the initial color. (In this case, black color)

**Comment by Lucifer24a** [comment]
> @henninghall
> 
> I'm getting a similar issue here, when I force the phone to use Dark mode on everything it changes the style of the date picker to this:
> 
> ![image](https://user-images.githubusercontent.com/36193643/272244908-f6e0ef61-2f8f-4b4f-b738-77f50bbc3293.png)
> 
> Usually it's like this with forced light mode:
> 
> ![image](https://user-images.githubusercontent.com/36193643/272245214-c005151e-a29c-4a75-b8ec-5b22c50ff478.png)
> 
> Is there any way I can override this style? Text color AND the **theme** prop does not work at all, I've no clue what to do.

textColor="#000000" is working for me

**Comment by finnbayer** [comment]
I came across this today on iOS 16. I cannot reproduce this behaviour on iOS 17 (Tested on iPhone12 Simulator iOS v.16.0 vs v17.0 as well as iPhone 12 on v16 and iPhone 12 mini on v17.4)

**Comment by henninghall** [comment]
textColor prop is no longer supported.
