### ISSUE TITLE
Feature Request: Enhanced Column Visibility Customization

### ISSUE THREAD

**Issue by KevinvdBurg** [henninghall/react-native-date-picker#710]
**Summary:**
Introduce the ability to hide specific columns in various modes (date, time, datetime) of the react-native-date-picker component for better flexibility and user experience.

**Background:**
The react-native-date-picker offers an extensive selection experience for date, time, and datetime. However, there are instances where developers might need a more streamlined selection process by showing only specific columns, thereby eliminating potential distractions.

**Details:**
For the **Date Mode**, the proposed enhancements are:

1. Hide the Day Column: Allow selection of just the month and year.
2. Hide the Day and Month Columns: Focus only on the year.
3. Hide the Year Column: Allow selection of just the day and month.

For the **Time** Mode, the enhancements can be:
Hide the Minute Column: Allow selection of just the hour.
Hide the Hour Column: Allow selection of just the minutes.

For the **Datetime Mode**, a combination of the above can be implemented, allowing developers to hide any of the date or time columns as per their requirements.

**Suggested API Changes:**
```
// Date Mode
<DatePicker
   mode="date"
   hideColumns={['day']}  // hides day column
/>

// Time Mode
<DatePicker
   mode="time"
   hideColumns={['minute']}  // hides minute column
/>

// Datetime Mode
<DatePicker
   mode="datetime"
   hideColumns={['day', 'hour']}  // hides day and hour columns
/>
```

**Benefits:**

- **Versatility:** With these changes, the component becomes much more versatile, catering to a broader array of use cases across different application needs.
- **Enhanced User Experience:** Tailoring the selection experience to the users' requirements can reduce confusion and increase efficiency.

**Potential Challenges:**

- The component's layout or design should remain responsive and aesthetic even when certain columns are hidden, especially considering various device dimensions and resolutions.
- Ensuring the underlying logic correctly processes the partial date/time information.

**Comment by henninghall** [comment]
Hi, I understand why this could be useful. Unfortunately it is out of scope of this package because of limitations in UIDatePicker, the iOS component this lib is based on.
