### ISSUE TITLE
AM & PM option not showing in devices like iphone 12, nord ce, vivo V2109 devices but working in other devices

### ISSUE THREAD

**Issue by PrathapKaraka** [henninghall/react-native-date-picker#713]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment]
It depends on the device language/locale and device preference (android)

**Comment by PrathapKaraka** [comment]
what if I want to keep AM & PM options for any kind of device both iOS & Android,  also AM & PM in a capital case too which props I need to use

**Comment by henninghall** [comment]
See readme
