### ISSUE TITLE
DatePickerIOS has been removed from react-native core (RN version 72.5)

### ISSUE THREAD

**Issue by petervn** [henninghall/react-native-date-picker#722]
**Describe the bug**
Invariant Violation: DatePickerIOS has been removed from react-native core. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'. See https://github.com/react-native-datetimepicker/datetimepicker

React native version: 72.5

```

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [72.5]
 - react-native-date-picker version [4.3.3]

**Comment by henninghall** [comment]
DatePickerIOS is not used in this repo
