### ISSUE TITLE
important bug from dates after 1969 onwards. 

### ISSUE THREAD

**Issue by LluisR** [henninghall/react-native-date-picker#724]
**Describe the bug**
We have detected a rather important bug from dates after 1969 onwards. 

**Expected behavior**
The package works very well indeed. However, we have detected a rather important bug from dates after 1969 onwards. If we try to enter dates older than 1970, the value returned by the onConfirm function is the wrong day. 
For example, if we enter 27/07/1969, the value returned is 26/07/1969. 
The months entered are also important, because if we enter 27/01/1969, the result is correct (27/07/1969) but if we enter 27/06/1969 the result is 26/06/1969, the same happens from March to October. January, February, November and December seem to work correctly. 

Anyone else with this problem? We are having a lot of trouble with this...

**To Reproduce**
Enter a date after 1969 in the months between March and October.

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - React Native version 0.71.11
 - react-native-date-picker version 4.3.3

**Comment by oscar-fk** [comment]
Which iOS?

**Comment by zvonimirr** [comment]
@oscar-fk iOS 17.0

**Comment by henninghall** [comment]
I've tried but can't reproduce the issue. Please provide example code or repo if you are seeing this issue.

Code tested:
```jsx
      <DatePicker
        date={new Date('1969-07-27')}
        mode="date"
        onDateChange={date => {
          console.log(date.toISOString());
        }}
      />
```

**Comment by zvonimirr** [comment]
Hi @henninghall it seems that the issue is somewhat randomly occuring.
I tried testing with June 22nd 2000 and it gave me June 21st 2000 as a result.

**Comment by zabojad** [comment]
I'm having the same issue :(...

**Comment by henninghall** [comment]
If anyone can provide a fully working example where this is reproduced we can reopen this.

**Comment by TFRadicalImaging** [comment]
Why this is closed if still happening?

**Comment by zvonimirr** [comment]
If anyone is still struggling with this after `timeZoneOffsetInMinutes` and just need the date (without the time and all the fun stuff):
```js
// Remove the time & timezone from the date
const isoDate = date.toISOString().split("T").at(0);
const realDate = new Date(isoDate);
```

This seemed to fix it for us. I suppose same could be done even if you need the time by deleting the timezone part from the ISO string.

**Comment by rohit-gh** [comment]
Request to open this. This is still not resolved. on date confirm, it picks one day previous date.
Tested this on timezone `Asia/Kolkata` , iOS 18 simulator on Expo Dev.
