### ISSUE TITLE
Version 4.3.3 is not working properly with IOS version 17.1.2

### ISSUE THREAD

**Issue by priteshmindcrew** [henninghall/react-native-date-picker#733]
the library is working fine till IOS version 17.1.1 but it is not working fine with the IOS version 17.1.2 in this the fonts are not visible

**Comment by gunjankumar58** [comment]
It is not woking 
"react-native": "0.67.4",
"react-native-date-picker": "4.3.5",

Error Log:

Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS

None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  
  TypeError: null is not an object (evaluating 'NativeModule.openPicker')

<img width="323" alt="Screenshot 2023-12-29 at 12 23 37 PM" src="https://github.com/henninghall/react-native-date-picker/assets/22020048/2d73fdc4-e845-4973-9f49-474b27443d4d">

**Comment by gunjankumar58** [comment]
This is also reported in this thrread.
https://github.com/facebook/react-native/issues/37817

**Comment by fysidm** [comment]
Same error with expo, and it occurred in both iOS and Android.

"expo": "~49.0.15",
"react-native": "0.72.6",
"react-native-date-picker": "^4.3.5",

Here is the example from README:
[Snack Example](https://snack.expo.dev/ESZXNSDsO)
