### ISSUE TITLE
Android maximumdate

### ISSUE THREAD

**Issue by raginisahu** [henninghall/react-native-date-picker#75]
when I am using maximum date in android so the previous date is not showing.

**Comment by henninghall** [comment]
Hi! Can you please post a minimal example of how to replicate the issue?

**Comment by raginisahu** [comment]
when I am using DateTime mode in android so not able to get previous year dates. 
eg. only showing 3 Jan to till now date.

**Comment by henninghall** [comment]
The default minimum date is 6 months before maximum date. You can solve this by setting a minimum date. But you probably don't want that since the user should not need to scroll that much to find the desired date, if they do you are probably using the wrong mode or picker library 🙂
