### ISSUE TITLE
Show full day only

### ISSUE THREAD

**Issue by venux92** [henninghall/react-native-date-picker#753]
**Describe the bug**
This is not a bug.

I'm just wondering is this is possible to display only the `day` as below

![Screenshot 2024-01-10 at 11 11 41 pm](https://github.com/henninghall/react-native-date-picker/assets/20675272/ff32b850-0bdd-41eb-b461-cc788c9661cc)

When I set to `mode: date` I need to select the `day`/`month`/`year` separately.

Thanks

**Comment by henninghall** [comment]
Not possible with this lib

**Comment by venux92** [comment]
@henninghall thank you for the quick reply.
