### ISSUE TITLE
Slow responses on Android

### ISSUE THREAD

**Issue by LaikaTheSpaceDog** [henninghall/react-native-date-picker#754]
**Describe the bug**
When using the date picker on Android, the response times are very slow and the picker seems to lag behind. Looking back through your old Issues I found [this one](https://github.com/henninghall/react-native-date-picker/issues/98) where it looks like this issue existed previously but was fixed in version `2.7.0`, however we are experiencing this issue on the latest version `4.3.5`.

**Expected behavior**
The response times should be smooth and immediate like on iOS

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
const DateTimePressable = ({ maximumDate, mode, selectedDate }) => {
    const [pickerDate, setPickerDate] = useState(selectedDate ?? new Date());

    return (
        <DatePicker
          minimumDate={new Date()}
          maximumDate={maximumDate ?? new Date(2100, 1, 1)}
          date={new Date(pickerDate)}
          onDateChange={(dateEvent) => {
            setPickerDate(dateEvent);
          }}
          mode={mode ?? 'datetime'}
        />
    );
}
```

**Smartphone (please complete the following information):**
 - OS: Android 14
 - React Native version 0.73.2
 - react-native-date-picker version 4.3.5

**Comment by henninghall** [comment]
Thanks for reporting this. Try to decrease the allowed span when using datetime mode, there is no reason to allow 100 years of dates to be picked when in datetime mode.

**Comment by Josh2941** [comment]
@henninghall I am facing the same slowness in my Android app too. Its evidently notable when we slide and choose PM in AM/PM slider and quickly press confirm, the response stays in AM. But if I slide to PM and give it a couple of seconds and then press confirm, its responding PM. This is a really critical issue on a very common use case. I have provided my code below.

       `<DatePicker
                modal
                mode={mode}
                minimumDate={minimumDate ?? new Date()}
                open={visible}
                date={date ?? new Date()}
                title={placeholder}
                onConfirm={onConfirmDateTime}
                onCancel={() => setVisible(false)}
          />`
