### ISSUE TITLE
Not Fabric (new architecture for React-Native) Compatible.

### ISSUE THREAD

**Issue by mrfrigerio** [henninghall/react-native-date-picker#759]
I'm trying to use this library on a new project using "expo": "~50.0.5" and "react-native": "0.73.2" with newArchitecture enabled but this library doesn't works.

Minimum code to reproduce:
`<DatePicker
              date={new Date()}
onDateChange={(newDate) => {
                // do something
              }}
              androidVariant="iosClone"
            />`

**Comment by mrfrigerio** [comment]
I've tested only on Android

**Comment by henninghall** [comment]
Missing issue template
