### ISSUE TITLE
minuteInterval not working

### ISSUE THREAD

**Issue by bilaluplogic** [henninghall/react-native-date-picker#76]
I have two queries
  1.I am set `minuteInterval={15}` in android but this not working
  2.Can't change border colour.Kindly check the screenshot
![date_border_issue](https://user-images.githubusercontent.com/36961222/60703800-4eb89400-9f20-11e9-8658-49e6e2610e02.png)

**Comment by henninghall** [comment]
I am pretty sure you have posted the question to the wrong repo. Please double check 😀
