### ISSUE TITLE
Import error (demo code)

### ISSUE THREAD

**Issue by antoinemacia** [henninghall/react-native-date-picker#764]
Hello!

Im simply following your modal example on expo web after installation but getting the following error

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: : <Text />. Did you accidentally export a JSX literal instead of a component?

Check the render method of `DatePickerWrapper`.
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]: Expo web (is it not meant to work on web maybe?)
 - React Native version - 0.73.2
 - react-native-date-picker version - 4.3.6

**Comment by henninghall** [comment]
Web is not supported unfortunately.

**Comment by syirilrakhulh** [comment]
So it's meaning when we run dev on web (but we only release on ios and android) we need to add condition to not render on web?

**Comment by henninghall** [comment]
Yes
