### ISSUE TITLE
Switching between AM and PM does not return the new time unless Confirm is pressed for a couple of seconds

### ISSUE THREAD

**Issue by cosminpwd** [henninghall/react-native-date-picker#773]
**Describe the bug**
I'm using a modal picker to select the time.

When updating a previously picked time I just change the AM/PM value and tap **Confirm**. After that I get the original time in `onConfirmDate()`. I have to keep pressing **Confirm** for a couple of seconds so the new time is returned.

**Expected behavior**
A short tap on Confirm should update the time when switching between AM/PM.

**To Reproduce**
```
<DatePicker
    modal
    mode="date"
    androidVariant="nativeAndroid"
    is24hourSource="locale"
    open={showDatePicker}
    date={selectedDate}
    onConfirm={(date) => onConfirmDate(date)}
    onCancel={() => {
      setShowDatePicker(false);
    }}
/>
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.73.5
 - react-native-date-picker version 4.3.7

**Comment by henninghall** [comment]
Try version 4.4.0 for on improvement on this topic
