### ISSUE TITLE
maximumDate can make date picker difficult to use

### ISSUE THREAD

**Issue by megantaylor** [henninghall/react-native-date-picker#775]
**Describe the bug**
On both iOS and Android, i can get into a situation where i open the DatePickerModal, start to change the date (month first) and the spinner will just scroll back to the month from the date prop. 

**Expected behavior**
I expect to be able to change month day and year values before the spinner tries to reset based on maximumDate. Or, the spinner doesn't react to my input, but the Confirm button is disabled.

**To Reproduce**
```javascript
 <DatePicker
      modal
      mode="date"
      title={props.title}
      open={props.isOpen}
      date={new Date(Date.now())}
      onConfirm={props.onConfirm}
      onCancel={props.onCancel}
      maximumDate={new Date(Date.now())}
    />
```

**Smartphone (please complete the following information):**
 - OS: issue occurs on Android and iOS
 -  "react-native": "0.73.2",
 - "react-native-date-picker": "4.3.5"

**Comment by henninghall** [comment]
Hi, thanks for reporting this. This is a limitation/feature of the underlying UIDatePicker so that is how it is expected to work.
