### ISSUE TITLE
[Android] dark mode not fully supported

### ISSUE THREAD

**Issue by hel-kalinina** [henninghall/react-native-date-picker#783]
The dark mode doesn't affect the color of the title and buttons (they appear unreadable) on android
<img width="302" alt="Screenshot 2024-03-16 at 09 56 59" src="https://github.com/henninghall/react-native-date-picker/assets/128246254/1f28c576-07d8-4fad-8a5c-cec5f9bd4969">

OS: Android
React Native version: "0.73.6"
react-native-date-picker version: 4.4.0

**Comment by henninghall** [comment]
Duplicate. of https://github.com/henninghall/react-native-date-picker/issues/720
