### ISSUE TITLE
locale not working in Android

### ISSUE THREAD

**Issue by minhDaiVatek** [henninghall/react-native-date-picker#784]
**Describe the bug**
i use this code to select data with Korea language. it's working well in IOS, but not working in android

**Expected behavior**
Work both platform

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
   <DatePicker
        modal
        mode="date"
        open={true}
        date={new Date()}
        theme="dark"
        locale={'KOR'}
        onConfirm={(_date: Date) => {         
        }}
        onCancel={() => {        
        }}
      />

}
```

**Smartphone (please complete the following information):**
 - OS: Android and IOS
 - React Native version:  "0.73.6",
 - react-native-date-picker version:  "^4.4.1",

**Comment by minhDaiVatek** [comment]
![Screenshot 2024-03-18 at 16 03 03](https://github.com/henninghall/react-native-date-picker/assets/162103221/23923c1c-56eb-4aea-a2fb-ecc02ad09da0)
And how can i update language "Select Data" "Confirm" and "Cancel" text

**Comment by henninghall** [comment]
@minhDaiVatek does it work if you use `ko-KR` instead of `KOR`?

**Comment by minhDaiVatek** [comment]
Oh, sorry, it work. thank you so much
