### ISSUE TITLE
DatePicker Picker cancel button event not call at very first app installed.

### ISSUE THREAD

**Issue by Qurat-ul-ainn** [henninghall/react-native-date-picker#790]
When the app is first installed, the Model Picker cancel button event may not be triggered. Additionally, if the user opens the picker but cancels without selecting a date, the picker model closes, but the cancel button code doesn't execute. Subsequent attempts to open the picker fail until the app is force-refreshed. This issue affects the functionality of the cancel button and requires app refresh to resolve

**Comment by henninghall** [comment]
Please include the issue template, and I will be able to take a look at this.

**Comment by himanshuLB** [comment]
@henninghall This still does not work.

  onCancel={() => {
              console.log('cancel is pressed');
              setOpen(false);
            }}
            
            This is not fired in some cases.

**Comment by Qurat-ul-ainn** [comment]
> @henninghall This still does not work in android.
> 
> ```
>         onCancel={() => {
>           console.log('cancel is pressed');
>           setOpen(false);
>         }}
> ```
> 
> This is not fired in some cases.



> @henninghall This still does not work in android.
> 
> ```
>         onCancel={() => {
>           console.log('cancel is pressed');
>           setOpen(false);
>         }}
> ```
> 
> This is not fired in some cases.

yeah its not working i make my customise DateTime picker
