### ISSUE TITLE
[ios] When `minimumDate` changes, `onDateChange` isn't fired

### ISSUE THREAD

**Issue by thomasttvo** [henninghall/react-native-date-picker#794]
**Describe the bug**
When `minimumDate` changes, it may alter the currently selected value if the value is smaller than the new minimum. When this happens `onDateChange` isn't fired

**To Reproduce**

```javascript
    <DatePicker
	  minimumDate=(min) // change this from a value smaller than the current selection to value larger than that
      onDateChange={date => this.setState({ date })}
    />
```

 - OS: iOS (not sure about Android, there might be an issue there too)
 - React Native version: 0.73.2
 - react-native-date-picker version: 5.0.0 and 4.2.13, not sure about other versions

**Comment by henninghall** [comment]
Thanks for reporting this. This behavior is intended. You could write your own logic for handling this situation.
