### ISSUE TITLE
Incorrect Date Returned When Setting Maximum Date

### ISSUE THREAD

**Issue by sacim41** [henninghall/react-native-date-picker#798]
**Describe the bug**
When setting a maximum date and selecting a date beyond that limit, the returned value is consistently one day before the selected date. For instance, if I select April 16, 2024, the returned value is April 15, 2024.

**Expected behavior**
I want the selected date to be returned accurately without any alterations or changes.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {
  const onChange = (selectedDate: Date | undefined) => {
    const currentDate = selectedDate || date || new Date();
    console.log(currentDate)
    setDate(currentDate.toISOString());
  };

  render = () =>
    <DatePicker
                modal
                testID='datePicker'
                open={showDatePicker}
                date={date ? new Date(date) : new Date()}
                onConfirm={(date) => onChange(date)}
                mode='date'
                maximumDate={new Date()}
                onCancel={() => {
                  setShowDatePicker(false)
                }}
              />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android-13 or iOS- 17.2]
 - React Native version - 0.73.4
 - react-native-date-picker version - 5.0.0

**Comment by henninghall** [comment]
Keep the date as Date in the state, not string (isostring). See examples in readme.
