### ISSUE TITLE
props buttonColor is not working for Android

### ISSUE THREAD

**Issue by rohitnegi0017** [henninghall/react-native-date-picker#799]
**Describe the bug**
buttonColor is not working for Android

**Expected behavior**
It should change the color for cancel and confirm button.

import React, { useState } from 'react'
import { Button } from 'react-native'
import DatePicker from 'react-native-date-picker'

export default () => {
  const [date, setDate] = useState(new Date())
  const [open, setOpen] = useState(false)

  return (
    <>
      <Button title="Open" onPress={() => setOpen(true)} />
      <DatePicker
        modal
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
        }}
        onCancel={() => {
          setOpen(false)
        }}
       buttonColor={'#dd00ff'}
      />
    </>
  )
}

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.68.5]
 - react-native-date-picker version [5.0.1]

**Comment by henninghall** [comment]
Thanks for reporting this, it is fixed in version 5.0.2

**Comment by L-Chew** [comment]
Doesn't seem like buttonColor is a prop of react-native-date-picker anymore?

**Comment by L-Chew** [comment]
All good now - realized I was using a prior version that didn't include buttonColor prop. 

Is there a way to change the title color? When using dark theme, the title is in black.  I was able to update the cancelButton and confirmButton using buttonColor.

<img width="326" alt="image" src="https://github.com/user-attachments/assets/545fead3-83c9-4d4f-9a38-387d4e1b72ba">
