### ISSUE TITLE
Header for picker

### ISSUE THREAD

**Issue by vvusts** [henninghall/react-native-date-picker#81]
Hi,

Is it possible to set header button confirm/cancel?

**Comment by henninghall** [comment]
Yes, but you will have to do that with other components like Button or TouchableHighlight.

**Comment by vvusts** [comment]
@henninghall Thank you for quick response but I am curious about approach.
I don't see properties for this so can you show me some direction how to set header with buttons?

**Comment by henninghall** [comment]
Sorry but your question doesn't make much sense to me. Could you describe in more detail what you are trying to achieve?

**Comment by vvusts** [comment]
@henninghall  "cancel" and "done" buttons like on this screenshot.
![DatePicker](https://user-images.githubusercontent.com/25580183/61080070-8645a580-a424-11e9-8ccb-5fe1b972ea3f.png)

**Comment by henninghall** [comment]
Okay, yes you definitely want to add the buttons outside of the picker component. Use for example Button component https://facebook.github.io/react-native/docs/button.html . Use the onPress callbacks to do what you want.
