### ISSUE TITLE
Wrong time selected on samsung phone

### ISSUE THREAD

**Issue by milkmouth** [henninghall/react-native-date-picker#818]
**Describe the bug**
 Selected 00:00, received 23:54

Update: The value displayed by the selector is inconsistent with the value received by onConfirm

https://github.com/henninghall/react-native-date-picker/assets/17698980/91d0e996-47ea-4a70-8dbd-f4e1de110b81

**Expected behavior**
 Select 00:00, receive 00:00

**To Reproduce**
```javascript
import moment from 'moment';
import DatePicker from 'react-native-date-picker';
export default class App extends Component {

  const [timeToPickerOpen, setTimeToPickerOpen] = useState(false);
  const [timeFrom, setTimeFrom] = useState(new Date(moment().endOf('day').format('YYYY-MM-DD HH:mm:ss')));
  const [isEn, setIsEn] = useState(false);

  render = () =>
    <DatePicker
      modal
      open={timeFromPickerOpen}
      date={timeFrom}
      mode="time"
      locale={isEn ? 'zh-Hant' : 'en'}
      title={null}
      confirmText={'CONFIRM'}
      cancelText={'CANCEL'}
      onConfirm={timeFrom => {
        setTimeFromPickerOpen(!timeFromPickerOpen);
        setTimeFrom(timeFrom);
        alert(timeFrom)
      }}
      onCancel={() => {
        setTimeFromPickerOpen(!timeFromPickerOpen);
      }}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.72.3
 - react-native-date-picker version 5.0.2

**Comment by JackJBlundell** [comment]
I am also facing this issue! I am sure it is to do with TimeZone - But when i print my date it is one hour off from what is shown in the date picker - Every time i pick a new time it is one hour off! 

Did you solve this?

**Comment by henninghall** [comment]
@JackJBlundell how do you print it? make sure you print it in your/your phone's local time.

**Comment by milkmouth** [comment]
timeZoneOffsetInMinutes={moment().utcOffset()}
