### ISSUE TITLE
Add ios's Custom Locale or i18n support

### ISSUE THREAD

**Issue by PigeonMuyz** [henninghall/react-native-date-picker#828]
**Describe the bug**
The react-native-date-picker component does not display in Chinese on iOS. The date picker shows English labels instead of Chinese.

**Expected behavior**
The date picker should display labels in Chinese when the device's language is set to Chinese.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
      //Like this: Locale={'schinese'|| 'tchinese'|| other}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: iOS
 - React Native version: 0.73.4
 - react-native-date-picker version: 5.0.4

**Comment by simon-assistiq** [comment]
What was your fix here?
