### ISSUE TITLE
[Android] App crashes on release mode RN 0.73.8

### ISSUE THREAD

**Issue by angelinaromashkoo** [henninghall/react-native-date-picker#830]
**Describe the bug**
App crashes when displaying the date picker modally only on Android (OS 11) in release mode. We are using react-native version 0.73.8 and the library version 4.3.3. We got this error in AppCenter: 
com.facebook.react.modules.core.ExceptionsManagerModule.reportException
ExceptionsManagerModule.java, line 65
com.facebook.react.common.JavascriptException: TypeError: undefined is not a function This error is located at: in DatePickerAndroid in DatePickerWrapper

**Expected behavior**
App shouldn't crash.

**To Reproduce**
```javascript
import {DateTime} from 'luxon';

export default function App() {

 const [dateOfBirth, setDateOfBirth] = useState('');
 const today = DateTime.local().setLocale(i18next.language);
  const minDate = today.minus({years: 7}).toJSDate();
  const maxDate = today.minus({years: 100}).toJSDate();

  render = () =>
   <DatePicker
        modal
        mode="date"
        locale={i18next.language}
        open={datePickerOpen}
        date={dateOfBirth !== '' ? DateTime.fromISO(dateOfBirth).setLocale(i18next.language).toJSDate() : minDate}
        onConfirm={onSelectDateOfBirth}
        onCancel={toggleDatePicker}
        maximumDate={minDate}
        minimumDate={maxDate}
      />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android, OS 11]
 - React Native version [0.73.8]
 - react-native-date-picker version [4.3.3]

**Comment by henninghall** [comment]
Try the latest version of this library please
