### ISSUE TITLE
AM/ PM not changing on onConfirm method.

### ISSUE THREAD

**Issue by Shweta-UMR** [henninghall/react-native-date-picker#845]
I am using this to pick a time in the app, but when I only change the AM to PM or vice versa, the time doesn't update correctly.

 <DatePicker
      modal
      open={open}
      date={time}
      mode={mode}
      androidVariant="nativeAndroid"
      is24hourSource="locale"
      onConfirm={selectedTime => {
        const newTime = new Date(selectedTime); // Force selection to a new Date instance
        console.log('🚀 ~ newTime:', newTime);
        setTime(newTime);
      }}
      onCancel={() => setOpen(false)}
      locale="en"
    />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.72.4]
 - react-native-date-picker version [e.g. 5.0.2]

**Comment by henninghall** [comment]
- Please provide a screen cap
- Why "Force selection to a new Date instance"? onConfirm should return a date object. 
- "selectedTime" should be provided to the date prop.

Incomplete example - closing
