### ISSUE TITLE
How to change gradient color top/bottom Android

### ISSUE THREAD

**Issue by MobileMon-Majestic** [henninghall/react-native-date-picker#846]
how to change the gradient color?

![Screenshot 2024-08-08 at 2 52 50 PM](https://github.com/user-attachments/assets/c66f28f1-9f41-4903-9fe2-22c1362b55b5)

**Comment by MobileMon-Majestic** [comment]
this has been completed?

How do i change the gradient?

**Comment by henninghall** [comment]
Closed due to incomplete issue template. Please use latest version of the package.
