### ISSUE TITLE
Pressing on selected date/time on iOS opens Numpad which cannot be disabled

### ISSUE THREAD

**Issue by ayushcarrier** [henninghall/react-native-date-picker#849]
**Describe the bug**
Pressing on selected date/time on iOS launches number pad to edit the current date/time which is undesirable in some scenarios (obscures view in Landscape mode)

**Expected behavior**
Prop to disable Numpad in datepicker on iOS.

**To Reproduce**
Press on selected date/time on iOS to activate the numpad.

```javascript
  const [date, setDate] = useState(new Date());

  return (
    <View>
      <DatePicker
        modal
        open
        mode="datetime"
        date={date}
        title={'title'}
        onConfirm={(date): void => {
          setDate(date);
        }}
      />
    </View>
  );
```

**Smartphone (please complete the following information):**
 - OS: iOS
 - React Native version 0.72.12
 - react-native-date-picker version 5.0.4

https://github.com/user-attachments/assets/c42164e4-5f56-41b2-9ff6-1fd58b58019a

**Comment by henninghall** [comment]
Duplicate issue

**Comment by ayushcarrier** [comment]
@henninghall please provide link to the duplicate issue so I can follow.
