### ISSUE TITLE
The Picker text is not visible in Android's Dark mode

### ISSUE THREAD

**Issue by Alexkin26** [henninghall/react-native-date-picker#857]
**Describe the bug**
The Picker is not visible when the Android's theme is set to dark mode.

**Expected behavior**
Picker's background color must be white and Picker's text color must be black

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
<DatePicker
  date={fecha}
  onDateChange={() => setFecha}
  locale="es"
/>
```

**Smartphone (please complete the following information):**
 - OS: Android 13
 - React Native version 0.75.2
 - react-native-date-picker version 5.0.7
 
![screencap-2024-09-09T065211 319Z](https://github.com/user-attachments/assets/a8fc5cc0-0d5a-461a-bb12-6d76255aa5be)

**Comment by henninghall** [comment]
As expected. Use the theme prop if your app doesn't support dark mode.

**Comment by Alexkin26** [comment]
theme prop is available when modal prop is set ONLY!

**Comment by AsifNoushad03** [comment]
If the text in your DatePicker is not visible in Android's dark mode, you can force it to use the light theme by setting
 **theme='light'**

**Comment by rvera** [comment]
I also ran into this issue and can confirm this can be fixed by setting the property `theme="light"`. This contradicts the README, so the documentation is incorrect and out of date.

**Comment by henninghall** [comment]
Thats right, the readme was incorrect, theme prop is supported both inline and in modals nowadays. The readme is now updated.
