### ISSUE TITLE
Unable to force light mode

### ISSUE THREAD

**Issue by TimHi** [henninghall/react-native-date-picker#866]
The app I'm working on does not offer a dark mode, hence I need to ignore the system set dark mode. In Android it's looking like this:

<img width="149" alt="Screenshot 2024-10-21 at 13 13 22" src="https://github.com/user-attachments/assets/dbf897a0-f55e-4a67-9f08-9f22eabeb6e1">

So far I've tried to edit the styles.xml. Neither `forceDarkAllowed` or the `timePickerDialogTheme/datePickerDialogTheme` seem to. make any difference.

```xml
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:spinnerItemStyle">@style/SpinnerItem</item>
        <item name="android:spinnerDropDownItemStyle">@style/SpinnerDropDownItem</item>
        <item name="android:timePickerDialogTheme">@style/DialogDatePicker.Theme</item>
        <item name="android:datePickerDialogTheme">@style/DialogDatePicker.Theme</item>
    </style>

    <style name="DialogDatePicker.Theme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorAccent">@color/primary_blue</item>
        <item name="android:textColor">@color/primary_dark</item>
        <item name="android:textColorPrimary">@color/colorBottomNavigationNotification</item>
    </style>
```

I'm on the latest version 8.2.0. Is there something I'm missing?

**Comment by Pefaur** [comment]
You tried setting the "theme" prop to 'light' on the DatePicker component to switch it to light mode?

```javascript
<DatePicker theme="light" />
```
The theme of the modal. "light", "dark", "auto". Defaults to "auto".

**Comment by henninghall** [comment]
Not entirely sure what you mean, version 8.2.0 doesnt exist. And changing android theme manually like that is no longer recommended for this lib. Try the theme prop like @Pefaur mentioned with the latest version.

**Comment by TimHi** [comment]
... I've meant to open the issue at [the community package](https://github.com/react-native-datetimepicker/datetimepicker) it's been a long day.
