### ISSUE TITLE
android build fails in windows

### ISSUE THREAD

**Issue by mingxin-yang** [henninghall/react-native-date-picker#87]
It work well in my macOS, but appear error in Windows. I have android sdk 27 in my computer.
```
* What went wrong:
A problem occurred configuring project ':react-native-date-picker'.
> Failed to find target with hash string '27' in: C:\Users\hqsong\AppData\Local\Android\Sdk
```

**Comment by henninghall** [comment]
Try if any of the solutions in these threads solves your problem: 
https://github.com/facebook/react-native/issues/5442
https://stackoverflow.com/questions/41044385/react-native-failed-to-find-target-with-hash-string-android-23-react-native
https://stackoverflow.com/questions/32731858/react-native-target-with-hash-string-android-x-not-found

**Comment by mingxin-yang** [comment]
@henninghall It does't work

**Comment by henninghall** [comment]
Allright, unfortunately I don't have windows access so I can't help you out, but please share your solution here when you find it 🙂

**Comment by henninghall** [comment]
@mingxin-yang Which version of react native and react-native-date-picker do you run? Have you been able to solve it? 🙂

**Comment by mingxin-yang** [comment]
@henninghall This problem should be the cause of the computer, there is no problem on another computer.

**Comment by henninghall** [comment]
Allright, closing this issue then.
