### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by Voidozzer** [henninghall/react-native-date-picker#88]
Hi there. Below is code sample used to generate DatePicker.

`<DatePicker
        date={new Date('2001-07-06')}
        mode="date"
        locale="us"
        maximumDate={maximumDate}
        minimumDate={minimumDate}
        onDateChange={onDateChange}
   />`

Timezone on phone is set automatically (Cupertino), 24 hours switch is off. Picker shows July 5 2001. When adding `timeZoneOffsetInMinutes={7 * 60}` everything works as expected. Not sure if that's a bug, or I'm missing something.

**Comment by henninghall** [comment]
Hi @Voidozzer! 

I think the problem might be that you initialize date to `new Date("2001-07-06")` which will become UTC time. Try to use set the initial date in the correct timezone, for instance `new Date("06 Jul 2001 00:00:00 GMT-0700")`

`new Date()` will also work if you want the current date.
