### ISSUE TITLE
Unable to resolve react-native-datepicker-x in 2.0.0 version

### ISSUE THREAD

**Issue by jfrense** [henninghall/react-native-date-picker#9]
I get the following error when trying to implement your component:

`Unable to resolve module 'react-native-date-picker-x' from '/Users/xxx/xxxx/xxxx/node_modules/react-native-date-picker/DatePickerAndroid.js': Module does not exist in the module map`

looks like to me in your DatepickerAndroid.js file you are still trying to import based on the old name:

```
import {
    Platform,
    NativeModules,
    NativeAppEventEmitter,
    Text,
    requireNativeComponent,
    ViewPropTypes,
    StyleSheet,
    DatePickerIOS,
} from 'react-native';
import React, { Component } from 'react'
import PropTypes from 'prop-types';
import { DatePicker } from 'react-native-date-picker-x'; <---------- old import?
...
```

**Comment by henninghall** [comment]
Thanks for reporting this! This is fixed in version 2.0.1
