### ISSUE TITLE
After update to rn 0.60.3 app is crashing on android

### ISSUE THREAD

**Issue by tmmgn** [henninghall/react-native-date-picker#90]
When trying to open picker everytime get crash without errors on android. On ios everything just fine. Tried versions 2.5.0 and 2.5.1, crashes still remains

**Comment by tmmgn** [comment]
in adb LogCat found this when opening datepicker
`07-18 12:57:54.488 32734 32734 E AndroidRuntime: java.lang.NoSuchFieldError: No static field empty1 of type I in class Lcom/henninghall/date_picker/R$id; or its superclasses (declaration of 'com.henninghall.date_picker.R$id' appears in /data/app/com.borealiscustom-sGRu-A_vhj9m65yW1DCfPg==/base.apk!classes2.dex)`

**Comment by henninghall** [comment]
Hi @tmmgn, thanks for reporting this. I have tried but I don't manage to reproduce the issue. Which android version and phone model are you using?

**Comment by tmmgn** [comment]
found out problem was because of my styles.xml rewrites your picker styles and thats why i got this error, when changed styles all seems to work great
