### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown timezone: Africa/Lagos

### ISSUE THREAD

**Issue by jerryheir** [henninghall/react-native-date-picker#92]
Hi, I am a React native developer from Lagos, Nigeria in Africa, and I am using react-native-date-picker v2.2.1, RN v0.59.9. 
During development, even when I run react-native run-android on a physical device, it runs very well but when I build my app to an APK, and I try to use the app, it crashed.
It doesn't do this on iOS and so I checked logcat and I got the error.
```PID: 15418
    java.lang.IllegalArgumentException: Unknown timezone: Africa/Lagos
        at net.time4j.tz.l.a(Unknown Source:255)
        at net.time4j.tz.l.a(Unknown Source:15)
        at net.time4j.tz.l.a(Unknown Source:1)
        at net.time4j.d.a.g.a(Unknown Source:0)
        at net.time4j.d.a.g.a(Unknown Source:22)
        at net.time4j.a.a.run(Unknown Source:14)
        at java.lang.Thread.run(Thread.java:764)
```

I think it's an issue on android that is specific to my location. Please what is the solution or work around to this?

**Comment by jerryheir** [comment]
In development, it works fine, but when I build APK, and navigate to screen with date picker. The App crashes to that error.
It works well in development and production for iOS

**Comment by henninghall** [comment]
Hi! I am pretty sure this is an issue with Proguard since it only happens in a released apk and you see that the class/package name has only single letters in the error message. Try ignoring time4j dependency in Proguard! 

Also please post your solution here and I will update the docs 🙂

**Comment by jerryheir** [comment]
Hi I did what you asked I disabled proguard and used R8 and I still got the same issue. And then I decided to disable all minifiers and it worked well on release. So the problem is with the minifier as a whole. How can I solve this please because it works now but the app is ridiculously larger now

**Comment by jerryheir** [comment]
And my Java knowledge is lower than that of a beginner

**Comment by henninghall** [comment]
You denfinately shouldn't need to turn it off completely. Try too exclude the affected files as described here: https://developer.android.com/studio/build/shrink-code#keep-code

R8 uses the proguard config file to exclude files/packets.

**Comment by jerryheir** [comment]
I created a proguard-rules.pro file in the android folder of react-native-date-picker and used the following

**Comment by henninghall** [comment]
Thats great!
