### ISSUE TITLE
onDateChange returns wrong date before 1580s

### ISSUE THREAD

**Issue by felixchan** [henninghall/react-native-date-picker#97]
To reproduce, start the initial date at 2019.

Go backwards until you hit *around* 1582, 1581 .
As you go before 1580, the date will continue to become more inaccurate.

Notice that the date returns is incorrect (by ~10 days) around this time.

```
  _onChange = (event: Event) => {
    const nativeTimeStamp = event.nativeEvent.timestamp;      //event.nativeEvent.timestamp is returned incorrectly around 1581
    this.props.onDateChange &&
      this.props.onDateChange(new Date(nativeTimeStamp));
    this.props.onChange && this.props.onChange(event);
  };
```

**Comment by henninghall** [comment]
Since you also opened an [issue for DatePickerIOS](https://github.com/facebook/react-native/issues/26023), it seems like this is a bug with the underlying DatePickerIOS, is that correct?

**Comment by henninghall** [comment]
Seems to be a bug in either [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios) or [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker)
