### ISSUE TITLE
Android error in RN 0.60.4

### ISSUE THREAD

**Issue by nodahikaru** [henninghall/react-native-date-picker#99]
In android, I got this error. 
![Screenshot_1566276348](https://user-images.githubusercontent.com/15790981/63318367-d3346a00-c348-11e9-9388-8c942e167728.png)

- RN 0.60.4
- react-native-date-picker 2,5.0
- Java 8

**Comment by henninghall** [comment]
Hi, thanks for reporting this! What is your width value set to?

**Comment by nodahikaru** [comment]
@henninghall What do you mean by width? 
Is there any props to set width in Android?

**Comment by henninghall** [comment]
Sorry, I thought you where setting the width and that was causing the issue. Could you provide a full example of how to replicate the issue?

**Comment by yernandus** [comment]
Same here, but it says "value for width cannot be cast from string to double"

**Comment by yernandus** [comment]
![Screen Shot 2019-08-23 at 14 24 02](https://user-images.githubusercontent.com/4067414/63578156-b353af00-c5b1-11e9-9afb-6f6c6899ff43.png)

**Comment by yernandus** [comment]
"react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-date-picker": "2.6.1",

**Comment by henninghall** [comment]
@yernandus can you send sample code or prop values of your implementation?

**Comment by yernandus** [comment]
> @yernandus can you send sample code or prop values of your implementation?

So the problem was  using '100%' for the width in the style

**Comment by henninghall** [comment]
Ah, all right. Unfortunately, widths and heights in percentages are not supported at the moment. I have now clarified this through some error messages from v2.7.0.

**Comment by itsramiel** [comment]
setting minWidth: '100%' works 😉
